### ISSUE TITLE
Deleting torrent crashes the app

### ISSUE THREAD

**Issue by jyoonPro** [XITRIX/iTorrent#101]
When I add one torrent and delete it, the app closes. At first I thought this was a feature; however, upon further inspection, I noticed that `tableView()` in TorrentListController+TableView.swift throws an index out of bounds exception. The code is attempting to access a non optional array `torrentSections` at index `section` which does not exist. So I suggest changing the code to something like below:

<img width="694" alt="Screen Shot 2020-05-20 at 12 59 12" src="https://user-images.githubusercontent.com/7097891/82403651-4e72aa00-9a9a-11ea-8a56-7d1cd30c7618.png">

**Comment by jyoonPro** [comment]
I'm not sure what the other two arguments do, but I assume that it's safe to remove them as well.

**Comment by XITRIX** [comment]
Thanks for suggestion, added it into DEV branch, this two arguments decides does the section should have a header.
But I'm sure why this crash could happen, cause number of sections gets right from the `torrentSections.count`:

![image](https://user-images.githubusercontent.com/9553519/82489579-91f50480-9aea-11ea-95e6-777c75a1ab2c.png)
