### ISSUE TITLE
Torrent Description Changes

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#102]
Three times now everything describing a torrent on the top-level page changed to exactly mirror another running torrent. They couldn't be told apart until they were opened revealing the scrolling title differentiating the two. At first it was specific to the same torrent but the third time was a different file. Rehashing fixed it each time. It's not a big deal, just thought the info may be helpful.

iTorrent 1.8, iPhone 7 Plus, iOS 13.4.1 Public beta (I would have 13.5, but to update it I need to turn off iTorrent for a day (or two) to turn on Wi-Fi.)

**Comment by XITRIX** [comment]
Now I'm learning the new ways to refresh data inside table lists for further refactoring it, cause now, an algorithm is a little unstable and can cause such problems.

**Comment by XITRIX** [comment]
Torrent list controller was fully rewritten, check it in the latest Dev builds.
