### ISSUE TITLE
iTorrent switches to mobile data during download

### ISSUE THREAD

**Issue by kaskurkada** [XITRIX/iTorrent#103]
Second time in a row, after upgrading to version 1.8, once the download completed (some 6 GB file), I was informed of minimum mobile data remaining. Looked through mobile data settings - for sure, 470 MB was on iTorrent count. Previously I already had same issue - wifi is in place, the signal is very strong, download speed was some 29-39 MB/s, wifi was never off. Once finished - iTorrent used mobile data, quite a lot.
Not sure how is this possible, because it is the only program that behaves like this. It now happened just because I went fresh ios install with new Unc0ver jailbreak and forgot to switch mobile data off for iTorrent, based on previous experience.

Iphone 6s Plus, 13.5, jailbroken with Unc0ver 5.01. Same was happening while on 13.4.1 jailbroken with checkra1n, also 13.5 jailbroken with checkra1n - basically it does not related to ios version or jailbreak tool.

**Comment by XITRIX** [comment]
Hmm... I don't know how is it possible, iTorrent just a normal iOS app, that don't use any private APIs, so iOS should manage its behaviour like any other app. I think the only way to avoid such problem is disabling cellular data inside Settings app. Later I'll try to add cellular disabling setting inside app.

**Comment by kaskurkada** [comment]
Hi Daniil,

Ok, this would be a solution, though the behaviour of the app is very
strange. I just now easily recreated issue:

Mobile data (again eaten, I reseted it before download):



On 2020-05-30, at 12:22, Vinogradov Daniil <notifications@github.com> wrote:

﻿

Hmm... I don't know how is it possible, iTorrent just a normal iOS app,
that don't use any private APIs, so iOS should manage its behaviour like
any other app. I think the only way to avoid such problem is disabling
cellular data inside Settings app. Later I'll try to add cellular disabling
setting inside app.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/XITRIX/iTorrent/issues/103#issuecomment-636304313>, or
unsubscribe

**Comment by shengchl** [comment]
Try disabling Wi-Fi Assist in Cellular settings. Maybe the problem is with your Wi-Fi connection and iOS switches to cellular from time to time during download.

**Comment by kaskurkada** [comment]
The wifi assist already was disabled. And wifi is in perfect condition -
must be some other reason



On 2020-05-31, at 13:30, shengchalover <notifications@github.com> wrote:

﻿

Try disabling Wi-Fi Assist in Cellular settings. Maybe the problem is with
your Wi-Fi connection and iOS switches to cellular from time to time during
download.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/XITRIX/iTorrent/issues/103#issuecomment-636452196>, or
unsubscribe

**Comment by SkipperQ93** [comment]
Happened with me as well. Had to disable cellular for iTorrent from iOS settings.

**Comment by kaskurkada** [comment]
Thank you for feedback, hopefully it can be fixed. It is not just my imagination at this point.

**Comment by XITRIX** [comment]
I've made some researches about it and I found nothing about disabling cellular data within app. iOS should switch connection types by it self and developers have no power to control it.
The only thing in theory I could make is permanent checking of connection type, and if cellular is active just pause all the torrent session, but I'm afraid it could add more problems that profits.
So if you have limits on your cellular connection, it's better to disable it in iOS Settings app.
I'll close that issue for now, if someone will find any valuable information about how it could be solved, feel free to reopen it.

**Comment by kaskurkada** [comment]
Hi,

Agreed, thank you.

Martynas

On 2020-06-06, at 15:03, Vinogradov Daniil <notifications@github.com> wrote:

﻿

Closed #103 <https://github.com/XITRIX/iTorrent/issues/103>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/XITRIX/iTorrent/issues/103#event-3414641967>, or
unsubscribe

**Comment by kaskurkada** [comment]
Hi! I’ve been using iTorrent app on my jailbroken phone, but now got iph 12 pro max - is the app only meant to run on jailbroken devices? Tried installing dev version from app center - did not succeed. 

Martynas

**Comment by XITRIX** [comment]
No, it should work on any iOS device, currently I have iPhone 8P with iOS 14.3b2 with no jailbreak and app works fine.

**Comment by kaskurkada** [comment]
Tried with Cydia Impactor and succeeded, thank you!

**Comment by XITRIX** [comment]
AppCenter is my build server, you could download ipa from it with computer, or you could use Jailbroken device with AppSync, cause it will not check app’s sign.

**Comment by kaskurkada** [comment]
By the way, even on the new iphone 12 pro max, iTorrent still uses mobile data - I downloaded 1,2GB file, 554MB were downloaded as mobile data. I then restricted iTorrent using mobile data, but I’m just saying that the problem is real.

**Comment by kaskurkada** [comment]
Hi! 

I have upgraded to 14.3 (clean install) and the app no longer works (installed with Cydia impactor, developer account). Is it something wrong with me only or it doesn’t work on 14.3? What about 14.4?

**Comment by XITRIX** [comment]
It works on my iPhone with 14.3, and also should work on 14.4.
Try to delete iTorrent folder from Files app, may be there is broken config file or something like that...

**Comment by kaskurkada** [comment]
There is no iTorrent folder from what I see via Files app... Maybe that's
the reason? Installation went smoothly with no errors, as always.
I tried fresh ios 14.3 install, then istalled iTorrent - same, briefly
flashes and closes. No ios settings altered, this is after fresh install,
no other apps installed. Same with fresh 14.4 install. What additional file
browsers can be used to access program folders (or to search for them)?
I thought maybe something wrong with my dev account, but should not be - it
worked just ok days ago.

**Comment by kaskurkada** [comment]
By the way, i'm using version 1.8.3 as the most recent. Is there any newer
beta version available? Just without installing provisioning profile?

**Comment by XITRIX** [comment]
That's ok not having this folder if that was fresh install.
Yes, 1.8.3 is the latest version right now, and there should not be any problem with it.
Could you try to use another Apple ID with impactor? Also, could you describe, what kind of (not working) you have? Is it instant closing, alert with error, or may be something else?

**Comment by kaskurkada** [comment]
It just briefly flashes and exits, no error notifications. Here’s video

**Comment by kaskurkada** [comment]
Hi, any app I load with Cydia imoactor, crashes same way as Itorrent. What does it mean? I’m not a developer and bought dev account just for this only reason - to sideload ipa files. So far it worked great, now something has changed. Did I exceed some number? My phone is the only device I used to install ipa files. I feel lost totally.

**Comment by XITRIX** [comment]
Usually the same problem when there is the problem with signing certificate. You could try to open your developer console -> certificates, and remove impactor's certificate, then remove an app from phone and reinstall it. Impactor should create a new certificate. Maybe this could help to solve the problem.

**Comment by kaskurkada** [comment]
Tried to install iTorrent via Xcode, I get a single error after which build fails:

**Comment by kaskurkada** [comment]
Here is another screenshot:

**Comment by XITRIX** [comment]
Sorry but I cannot see any screenshot from you.
![image](https://user-images.githubusercontent.com/9553519/106952444-2ddea300-6742-11eb-853c-058aae75b7e4.png)

**Comment by kaskurkada** [comment]
By the way, even though currently the app does not launch at all, I now
remembered, that previously, when I upgraded to ios 14.3 via online update,
it still worked, but - it did dispay the warning that the system is newer
than required. Same was after I upgraded via online update to ios 14.4.
Once I made a fresh reinstall via itunes, it now doesn't work at all. So it
was some kind of warning previously, but after clicking OK, it still would
work. After clean reinstall from ios 14.2, it no longer works.

**Comment by XITRIX** [comment]
I think something happens with your certificate on Apple Dev. Could you attach your errors from XCode? I'll help you to solve them.

**Comment by kaskurkada** [comment]
How about this idea - could I somehow share with you my macbook screen live
(maybe via skype)? I can speak russian quite well.  It just about timing -
now my macbook is at my daughter's posession - she's having school online
until 13.00 (Moscow time 14.00).
And I am sending you pictures with this email too.

**Comment by kaskurkada** [comment]
Solved Deepdiv error, now this:

**Comment by XITRIX** [comment]
Please, attach your screenshots on github website, I cannot see your images that attached with email.

**Comment by kaskurkada** [comment]
Hi!

Finally managed to install iTorrent on my device - used the app Sideloadly
- it worked. I'm so happy.

**Comment by XITRIX** [comment]
happy for you, enjoy the app!
