### ISSUE TITLE
[Request] - RSS support

### ISSUE THREAD

**Issue by rluvaton** [XITRIX/iTorrent#104]
Can you please add our RSS Support like [qBittorrent](https://www.qbittorrent.org) have.

This is from their website:
> Integrated RSS feed reader and downloader

**Comment by XITRIX** [comment]
Never used RSS, first of all I'll try to learn something about it

**Comment by XITRIX** [comment]
RSS implemented, try it by downloading latest Dev build from AppCenter, I need some review on it.

**Comment by rluvaton** [comment]
> RSS implemented, try it by downloading latest Dev build from AppCenter, I need some review on it.

You’re awesome man!, updating right now
