### ISSUE TITLE
Please add a selection option when adding torrent files to iTorrent.

### ISSUE THREAD

**Issue by ghost** [XITRIX/iTorrent#105]
I understand that this isn’t necessarily an issue, but I believe this would be a great function that (for some reason) isn’t there.
When updating iTorrent, it is a frustrating task to resume previous progress. It is easy to move files back to the iTorrent folder, but hard to move their metadata back. Moving the _Config folder doesn’t do anything. Instead, the app requires you to select the torrent files one-by-one, which is difficult when you have been downloading several torrents.
I believe that a selection option for torrent files would be a great addition to iTorrent.
Thank you.

**Comment by XITRIX** [comment]
Sorry, but I don't get, what do you mean "resume previous progress". Do you mean, that you download an app from another source, and it installs as another app, so you need to transfer previously downloaded files to another app, or I don't get it?

**Comment by ghost** [comment]
> Sorry, but I don't get, what do you mean "resume previous progress". Do you mean, that you download an app from another source, and it installs as another app, so you need to transfer previously downloaded files to another app, or I don't get it?

Sorry, I have just realized that I didn’t need to do the method I was previously doing and that iTorrent updates replace the app. I’m closing the issue.
