### ISSUE TITLE
WebDAV Support

### ISSUE THREAD

**Issue by SkipperQ93** [XITRIX/iTorrent#107]
I am unable to start WebDAV server. As soon as I enable it, it disables automatically.

![image](https://user-images.githubusercontent.com/22097793/83797044-a3254000-a6aa-11ea-8cdf-6407fdf15159.gif)

**Comment by XITRIX** [comment]
Sure, it's bug, i'll fix it in next update.
Thanks.

**Comment by XITRIX** [comment]
Fixed it in Dev branch. I'll update dev build in several days.
