### ISSUE TITLE
Torrent traffic no longer goes through vpn on 1.8

### ISSUE THREAD

**Issue by Bkmd100** [XITRIX/iTorrent#109]
My isp throttles torrent download speeds, so I have to use a vpn to get a reasonable download speed.
I noticed that my speed is throttled after updating to 1.8 even with vpn on, using http://checkmyip.torrentprivacy.com/ shows that my browsing ip is my vpn’s while torrenting ip is my isp’s.
Downgrading to previous versions fixes to issue.

**Comment by XITRIX** [comment]
I already wrote a large piece of text of why it is impossible, but then I checked it with your website and realised that it really not works...
I have no idea why the hell is it possible, I'll try to update libtorrent in next release, hope it will fix that problem.

**Comment by 141** [comment]
I use NordVPN on a cellular connection and v1.8 is showing the real IP on my jailbroken phone. I suspect non-jailbroken devices could be safe, but jailbroken devices it's not on the right internet interface. Please place a warning on the main download for v1.8 that it's not suitable for jailbroken devices that use a VPN for safety. 1.7.4 hotfix is tested and safe. Libtorrent 1.2.6 settings are likely to blame.

**Comment by XITRIX** [comment]
It's a little bit strange. My cellular operator bans all p2p connections so I cannot download any torrent using cellular without VPN, but with VPN it works fine, so could it tells that VPN is working?
Also LibTorrent 2.0 already has a release candidate version, maybe updating to it will fix that problem...

**Comment by 141** [comment]
It's probably only leaking the real IP to the tracker, but no other connections can connect to you on the real IP. Leaking the real IP at all is the problem.
The latest version of qbittorrent uses libtorrent 1.6 and it has no issue on a computer.

**Comment by XITRIX** [comment]
Checked the latest version of qbittorrent with libtorrent 1.2.6 and it HAS the same problem, while previous versions with 1.1... doesn't, so the only way is to wait libtorrent's fix.
<img width="1519" alt="Снимок экрана 2020-06-29 в 00 53 58" src="https://user-images.githubusercontent.com/9553519/85959158-5b40c280-b9a3-11ea-9444-22358952c930.png">
In next update I'll implement proxy option, so may be you can try to use it instead of broken vpn connection (you already could try it by downloading Dev version of app from [AppCenter Link](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public))

**Comment by 141** [comment]
Until you understand the problem with libtorrent 1.2.6 can you revert to 1.2.3 or whatever was used previously? V1.2.3 doesn't have the issue 1.2.6 has, so if that still causes an issue it's not libtorrent.

I tested the windows qbittorrent v4.2.5 (on win10) with default settings on a wifi connection, and I had no problems with a leaked real IP. I retested on three different sites for leaks, but there was none.

Tested on a wired connection with a different computer and still qbittorrent 4.2.5(with default connection settings) for win64 is safe with NordVpn. Here's the two additional sites I tested both on: https://torguard.net/checkmytorrentipaddress.php https://ipleak.net/

**Comment by XITRIX** [comment]
Ok, I'll test it with previous versions, I think libtorrent could have problems with "linux" part of code, macOS and iOS uses the same shared code as linux, and only windows uses it's own c++ libs, which (maybe) has no such problem.

**Comment by 141** [comment]
I tested 1.8.1 (July) on all three testing sites as before and it failed again. Instead of giving me back my VPN address, it's giving me an IP from my cellular provider. That basically geo-locates me and isn't acceptable. I'm currently on the Checkra1n jailbreak on ios 12.4.4. Still thinking 1.2.3 is the safe libtorrent to use.

**Comment by ImOldGregg** [comment]
Same, I'm on a non jail broken device and it literally shows my ip AND cellular ip when checking.

**Comment by XITRIX** [comment]
I’ll downgrade libtorrent if it will not brake anything in next release (or update to 2.0 if it will be released)

**Comment by ImOldGregg** [comment]
Sounds good! Thank you! It's always something, am I right? 😭

**Comment by XITRIX** [comment]
Yep, unfortunately it's true T_T

**Comment by ImOldGregg** [comment]
Libtorrent 1.2.8 has been released, not sure if the issue will be fixed in this version or not.

**Comment by ImOldGregg** [comment]
Just curious when the next build would be out. Not trying to rush, I'm still using 1.7.4 hotfix just fine.

**Comment by XITRIX** [comment]
![image](https://user-images.githubusercontent.com/9553519/90828671-1869ee00-e347-11ea-9199-885226b914e0.png)
New version has been released right now, I'll check if that bug was fixed and then update iTorrent release

**Comment by ImOldGregg** [comment]
Awesome! I'll be looking forward to it!

**Comment by ImOldGregg** [comment]
Just joined Patreon to help a little.

**Comment by XITRIX** [comment]
Thanks for your support!

**Comment by XITRIX** [comment]
![E20664A2-04CD-4325-B5E7-826A5E654AAE](https://user-images.githubusercontent.com/9553519/90835612-bfee1d00-e355-11ea-9237-ea3ce0d665ee.jpeg)
v1.2.9, still not fixed((

**Comment by ImOldGregg** [comment]
Well that sucks 😭

**Comment by XITRIX** [comment]
Created an issue for libtorrent arvidn/libtorrent#5027

**Comment by XITRIX** [comment]
#129

**Comment by ImOldGregg** [comment]
They didn't help too much did they 😂 hopefully you'll get it figured out. If you need any beta testing let me know.

**Comment by XITRIX** [comment]
True:) But now I know about network interfaces, I’ll try to implement some kind of priorities of them, and also there could be a new option like “download with VPN connection only”.
May be I’ll release 1.8.2 version without this fix, cause it already have a lot of other bug fixes, so may be it will be a feature(fix) for 1.8.3, but I’m not sure yet...

**Comment by ImOldGregg** [comment]
A better site to test torrent ip is https://ipmagnet.tap3.eu/
When I test with that site on 1.8.1 it gives me multiple ip's. One is my original, one the VPN address, and anther random address.

**Comment by XITRIX** [comment]
Wow, great, thanks for it!

**Comment by ImOldGregg** [comment]
Also I know this is in the wrong category but downloaded torrent files now open correctly in iTorrent, no need to use chrome browser anymore. I'm running iOS 14 beta 5.

**Comment by XITRIX** [comment]
No, I'm a big idiot, there was a problem cause I used .open rule to open files, and with resigned apps this is the problem, but if .import rule is using, it will be fine. I fixed it in yesterday commit, so the next update will fix that problem at all.

**Comment by ImOldGregg** [comment]
Hey, it's all good. I'm just glad someone's committed to making a torrent app for iOS. 😁 I just wish I could help more but I know nothing about the coding aspect of it.

**Comment by ImOldGregg** [comment]
Hey I know you already know this but the new version is still pulling ip's from all network interfaces instead of the default or main. It lists my WiFi ip, cellular ip, and VPN ip (when VPN is on). Figured I'd go ahead and post before somebody else does hopefully they'll read this before commenting. Using https://ipmagnet.tap3.eu/ for testing.

**Comment by XITRIX** [comment]
Yes, as I told, 1.8.2 does not have any fixes of this problem, I'll try to implement such options in next update, and may be libtorrent will change some settings for it

**Comment by XITRIX** [comment]
@ImOldGregg, I've implemented an option to chose interface to use. You could try it in latest dev build, find in Settings -> Connection Settings -> Interface. Need some tests from you.

**Comment by ImOldGregg** [comment]
Sure thing man. What do I need to do to sign up for dev build?

**Comment by ImOldGregg** [comment]
I unfortunately was not able to install from the dev center.

**Comment by XITRIX** [comment]
Because that link only for jailbroken devises, you should download it with PC and install with cydia  impactor

**Comment by rvb1k** [comment]
Or use [AltStore](https://altstore.io/)

**Comment by ImOldGregg** [comment]
Ok, so I've tested using PIA VPN app on iOS 14. When you choose the all option like before it will show the public, VPN, and cellular ip addresses. Choosing Primary will show just the public IP address. VPN only does not respond with an ip. I have also checked each interface in the manual options but none of the show the VPN up address coming from the PIA app.

I have noticed that the last iteration that works like it should says its signed with libtorrent while the newer versions are signed with your app model. Not sure if that means anything since I'm not a coder. Maybe there was an order of flow that was swapped since updating libtorrent. I'm not sure.

Last known working with VPN:
![image](https://user-images.githubusercontent.com/64284396/94295946-a9744c00-ff27-11ea-85ac-e04f39fd9956.jpeg)

Last dev build:
![image](https://user-images.githubusercontent.com/64284396/94295996-bd1fb280-ff27-11ea-8492-cf84def06cfb.jpeg)

**Comment by ImOldGregg** [comment]
Hey just making sure you saw my last post. It's heading in the right direction I think, just needs some tweaking. Hope my info helps. Message if you need more.

**Comment by XITRIX** [comment]
Hi, yes, I saw it, that version was before libtorrent changed it’s interface policy, earlier it worked with one interface only, but later it was changed to use all of available interfaces, so now we should setup it manually.
Try to check interfaces list before vpn enabled, than enable it and check again, new interface should appear, try to use it.

**Comment by ImOldGregg** [comment]
These are the only interfaces that show in the manual list.

![image](https://user-images.githubusercontent.com/64284396/95614802-b9625480-0a2c-11eb-9e0c-be85d434d5fe.jpeg)

![image](https://user-images.githubusercontent.com/64284396/95614789-b23b4680-0a2c-11eb-8d6b-c8d1e3382fac.jpeg)

![image](https://user-images.githubusercontent.com/64284396/95614778-acddfc00-0a2c-11eb-806f-51b6a726eda6.jpeg)

**Comment by ImOldGregg** [comment]
When I test each one individually i can only get my public on en0 and my cellular on pdp_ip0.
All of the other interfaces do not respond when testing. If I choose the All option it gives me all three ip addresses, the public,VPN, and cellular.

**Comment by ImOldGregg** [comment]
All of the interfaces show the same whether I'm on my public ip or connected to a VPN. I never seen a new interface show up after connecting to my VPN.

**Comment by ImOldGregg** [comment]
Running iOS 14.0.1 and using Private Internet Access VPN and Synology VPN for testing.

**Comment by ImOldGregg** [comment]
Still no luck on getting it to find the correct interface?

**Comment by 141** [comment]
@ImOldGregg If the phone is jailbroken and you have terminal(and netstat) installed, do a "netstat -i" before and after the vpn connection started. There will be a second ip listed(not your given ip) in the interfaces the second time and that's your vpn connection interface. Most likely it's ipsec0. Furthermore, try stopping all connections in the app, connect to ipsec0, close and remove the app from memory, and relaunch and see if it's still using ipsec0. Then test if everything is okay. At least you can eliminate variables and know more.
I have not been using this app, so I'm going according to what I see from NordVPN's connection.

**Comment by ImOldGregg** [comment]
Still haven't forgot to test, just been busy 😭 Gonna try to test and get you some results soon.

**Comment by ImOldGregg** [comment]
Tested the 1.8.4 dev2 build just now and PIA VPN finally registers on the utun8 interface. I'm able to get all torrent traffic thru just the VPN address finally. Probably still needs more testing but just wanted to let you know its good results so far 🙌

**Comment by XITRIX** [comment]
That's great news!
I'm not sure that I'll be able to make some kind of automatic interface selection, but if someone really worries about ip leaking, he could use manual interface selection.

**Comment by ImOldGregg** [comment]
I have to correct myself, its not utun8 that PIA uses but rather the last available utun interface. I checked today and utun8 was gone from the list. Last was utun7 and setting to that worked just fine.

**Comment by 141** [comment]
I have installed and just starting to test Version 1.8.4-dev.2 (21.0). The connections to choose from I see has been dumbed down, and by default it will give away the real IP. Once the setting is changed to VPN Only the TCP and UDP connections are fine and safe.
Once the changes are in the production release this bug is gone, but it would be lovely, if it detects a VPN, to either choose that or prompt to choose that. Also, it's troubling that it's leaking the real IP when on a VPN connection, using the default All setting. I am really puzzled why it leaks in the All setting.

I guess I'll be using the app, due to the Transmission 3.0 release for iDevices is not connecting to UDP trackers.
So, I'll be active again here.

**Comment by ImOldGregg** [comment]
I'm assuming its going to be hard to set an automatic setting with it going thru iOS. My VPN lets me use IPSec, wireguard, or openVPN protocols and the interface they use is different especially wireguard which can use any number of the tun# options. It will usually try the last available one though but not always. Anytime I restart iOS I have to manually play with it to show the correct tun and set to it. Keep in mind i know absolutely nothing about coding for iOS tho these are just what I've noticed so far and my assumptions 😭🤦‍♂️😂

**Comment by XITRIX** [comment]
The same as I know nothing about networking) It was really strange to me that iOS app could use any other network interface than iOS provides.
As autosetup I tried to allow all utun interfaces, but some VPNs creates another interfaces.
As I understand qBitTorrent works the same way on macOS, so I think I can't do nothing more, than allow to choose interface manually.

**Comment by XITRIX** [comment]
Ok, some progress information.
Now I'm in progress of changing the core of iTorrent from libTorrent to libTransmission. 
No leak on transmission at all.
That will be a separate app but with same code base, the only change will be is iTorrent-Framework, so I'll be able to support and update both apps simultaneously. There is a chance that I'll allow to change iTorrent's core inside the app, but I don't know who the hell needs it, so may be not.
Lots of stuff already done, it could download torrents and magnets already.
But there are also lots of things to be done and polished, so I'm not sure about release date.

**Comment by ImOldGregg** [comment]
Looking forward to it! Let us know if you need any testing.

**Comment by oppalla** [comment]
than you so much @XITRIX for working on this issue.
I'm using an old iPhone 5s jailbroken to download some low seed torrents...
but, I've checked with the last released version of the app and it was leaking my real ip.
then I've read this topic, and downloaded last 1.8.4-dev.3 build from appcenter.
now, it show my real ip + the VPN ip.

the thing is that I cant change interface mode under network settings.
equal happen to proxy settings.
I click mode, select VPN, but it don't change and dont show changing on mode, under network.
same thing happens with proxy settings, if I try to set SOCKS5, i click it but nothing happen.

maybe it's an issue with ios 12? i'm running 12.5.1...
any help will be appreciated!! thks!!

**Comment by XITRIX** [comment]
No, it's not because of iOS version, have you tried to select port manually?

**Comment by oppalla** [comment]
> No, it's not because of iOS version, have you tried to select port manually?

no, not in fact.
now that you said, I've tried to change port number, changed to 6861 to 6871.
closed and opened the app, nothing changed. I can't select other mode than ALL in "select interface mode"
and cant select any proxy type other than NONE in Proxy type.

should I change ports to any specifically number and check it again?
thanks for the fast answering :)

**Comment by XITRIX** [comment]
That's strange, I'm pretty sure that it worked in previous versions, I'll try to check it later, but I cannot promise that it will be soon, I have not enough time to work a lot on itorrent right now.

**Comment by oppalla** [comment]
> That's strange, I'm pretty sure that it worked in previous versions, I'll try to check it later, but I cannot promise that it will be soon, I have not enough time to work a lot on itorrent right now.

sir, mr. @XITRIX, I just have to say thank you for supporting us.
I will try my best to help you solve any issues that my help can be valuable...
for you to visualize what is happening, I made a screen rec for you to see...
you can watch here: https://drive.google.com/file/d/1UGDsWEINloCwTW2ebFg6Se8uZR4gTi3Y
also, I'm sorry for the delay in answering!

**Comment by ImOldGregg** [comment]
Try installing 1.7.4 hotfix version and let us know of the results on a VPN test. Use this site since it will provide multiple IP leaks thru torrent if there are any. http://ipmagnet.services.cbcdn.com/

**Comment by oppalla** [comment]
I use https://ipleak.net, which is also a great leak tester.

with version 1.7.4 hotfix, in both services, ipleak.net and ipmagnet.services.cbcdn.com the only showing IP is the VPN one.
thanks for the info @ImOldGregg !!!

hope to have this old feature once again on the next updates, if @XITRIX finds some time for it!!!
thank you all

**Comment by oppalla** [comment]
@ImOldGregg does this version 1.7.4 just allows one downloading torrent per time? :(
I use it to keep downloading low seed torrents, so there will be no point on using for only one torrent per time..

**Comment by socksprox** [comment]
How can I see if my ip is leaked or not?
