### ISSUE TITLE
RSS bugs

### ISSUE THREAD

**Issue by rluvaton** [XITRIX/iTorrent#110]
[Bug preview](https://youtu.be/is5vZMiD2l8)

When tapping on RSS item it doesn’t download, when clicking on open in safari it added the item but not downloading

#104

**Comment by XITRIX** [comment]
Can you give me this RSS feed to test it?
I watched the video, I don't really think that it should download by tapping on the item, cause usually there is an html page with description, which could contains links on torrent files.
I am new to RSS so could not understand of how it should to work, but if it should download magnet links by tapping on item, I could add checking the type of safari link, and if it is magnet or torrent files, allow app to suggest to download it

UPD.
I found that RSS Feed and added Rick and Morty for example, sure, app should ask to download files automatically and I'll add it, but for now I added it by "open in safari" and download started.
![photo_2020-06-15_09-55-20](https://user-images.githubusercontent.com/9553519/84626737-55040e00-aeee-11ea-9515-18652917a3d3.jpg)

UPD2.
Tried another magnet, it spend for 5 minutes to fetch magnet link, and finally downloaded it, so you should just wait.

**Comment by rluvaton** [comment]
[RSS Link]()

**Comment by XITRIX** [comment]
Implemented torrents auto detection in RSS posts, check it in Dev build
