### ISSUE TITLE
Feature(s) Request: Port Selection and Check

### ISSUE THREAD

**Issue by jojobrogess** [XITRIX/iTorrent#111]
I was wondering if you could add a port selection and port check feature. 

If you could also add download and upload Speed limitations into individual torrents instead of just in system wide settings, that would be awesome. Oh and can you allow for custom speed limitation values as well; you have it set for 128, 256, 384... for KB/s and 1, 2, 3... for MB/S. I would like to allocate (let’s say as an example) 100KB/s system wide and then choose for one torrent to have 15KB/s and another to have 30KB/s and one 55KB/s. 

I was also wondering if you could add way to limit the connected seeders and peers per torrent and also system wide. It seems like there’s no option for it, but I could have missed it. 

I know it’s a lot, but take it with a grain salt. This thing works beautifully regardless. 

Thanks to everyone for all your hard work!

**Comment by XITRIX** [comment]
No problem for port selection I think. I am now working on huge networking overhaul, which includes lots of settings for connections types and protocols, I think I could add port selection as well. 
Also I think I'll add custom global speed limitations, it's not very hard.
But with individual limitations not in next update, but in future I think I'll add it.
For seeders and peers limitations I cannot answer for sure, cause don't know how to do it for now.

**Comment by XITRIX** [comment]
Port selection and custom speed limitations has been implemented in latest Dev build

**Comment by jojobrogess** [comment]
Sorry for the late reply! I saw that you got this implemented like the next day. THANK YOU! 
It has really been helping out, especially the port selection. 
Really loving the work you’ve done here! 
Port check verification would still be nice if you could implement it.
I got around it by just changing the port to one until I saw the speeds that felt appropriate for my network.
Thanks again bro! Seriously.

**Comment by XITRIX** [comment]
I'll try to find the way to check the port connection, thanks for nice words)
