### ISSUE TITLE
No downloading

### ISSUE THREAD

**Issue by adinatsu** [XITRIX/iTorrent#112]
I am using latest ios on ipad air 3 ( non jailbreaked )
I downloaded the itorrent app from ignition ans then chose 2 dollar membership for add free version 

After successfully doing that i tried to add magnetic links from safari and it opened in itorrent and kept showing OBTAINING METADATA and nothing happened 

I tried other websites for torrents but gave same result plus when i download torrent files in safari i cant open them in itorrent and cant add them ... it just gives me option to rename them and nothing else .... 

Need help

**Comment by XITRIX** [comment]
Hi, now I am developing an update, which enables custom connection protocols (like DHT or uTP), it should solve all the problems with unstable download starting. 
With file opening there is the problem in iOS 13, apple's default apps cannot open files in resubscribed apps (i.e. by Ignition), you should download torrents using custom apps like Google Chrome, or just copy the direct link and paste it in app.
I don't know which version Ignition distributes, the best way to install iTorrent is download the ipa from releases or Dev build from AppCenter, and install it using Cydia Impactor or AltStore.
Thank you for your support for iTorrent development.

**Comment by adinatsu** [comment]
I re installed the app from ignition and it works no problem thx 
And yes the ignition is have latest app 1.8 version
