### ISSUE TITLE
Slow and no download speed plus vpn issue

### ISSUE THREAD

**Issue by adinatsu** [XITRIX/iTorrent#113]
When i start downloading a file it starts just fine and after some time download speed becomes low ( around 1 kb ) and i cannot start torrents from magnetic links when i am using vpn ... i have to turn vpn off and then click on magnetic link to start downloading torrent otherwise if i click on magnetic link with vpn on it just stays on obtaining metadata and nothing else... i have even enabled background data on and still my download speeds go out after some minutes 
Plz help me with these 2 issues

**Comment by XITRIX** [comment]
Hi, try to install latest Dev build, you can find the AppCenter link on main page. I have implemented lots of network "buffs" and features that could solve your problem.

**Comment by adinatsu** [comment]
Can it be installed without cydia or altstore cos my pc is dead and i wont have my laptop till next month ?

**Comment by XITRIX** [comment]
Sorry, but I don't know any way to do this, it's only an ipa file. You could try to find service which could resign apps online, but I'm not good at sideloading.
