### ISSUE TITLE
Update for iOS14

### ISSUE THREAD

**Issue by skim325** [XITRIX/iTorrent#119]
Since iOS14/iPadOS14 beta is out, any plans to support it soon? 
After updating, my app stopped launching, and downloading the latest Dev build via AppCenter throws “unable to install iTorrent. Please try again later” error message

**Comment by XITRIX** [comment]
I already installed iOS 14 on my primary iPhone and current version of iTorrent works pretty well wothout any issues. You should use AppCenter download link only with jailbroken device with AppSync installed, or with your PC to download ipa file to install it by Cydia Impactor or AltStore. In another case, you'll get an error cause this ipa file subscribed with my own setificate.
Later I'll rebuild app using latest xCode, but now, UIKit have several issues, so I'd like to wait until they'll be fixed.
