### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by iarmawn** [XITRIX/iTorrent#12]
Hi i have this errors when i try to compile it . (i'm using iTorrent.xcworkspace)
1-Duplicate interface definition for class 'MarqueeLabel'
2-Property has a previous declaration (8 of this error)
3-could not build Objective-C module 'MarqueeLabel'

**Comment by XITRIX** [comment]
Specially for the test I redownloaded whole the project, just run "pod install", and hit "play" button in Xcode, and it has build successfully. 
What version of Xcode you are using?

**Comment by XITRIX** [comment]
I'll close this issue because you are not answer for a long time, be free to reopen this issue

**Comment by iarmawn** [comment]
Hi again 
sorry for my absent 
i run xcode 9.4.1
i run in another error this time !
i have 22 errors in "Apple mach-o linker error" group
