### ISSUE TITLE
iOS 13.6 Crashes/Won’t open

### ISSUE THREAD

**Issue by evanthewalrus** [XITRIX/iTorrent#123]
Would really like to use the app but it crashed whenever I launch it. Thanks!

**Comment by rvb1k** [comment]
Please can you provide the crash log? (Settings -> Privacy -> Analytics and Improvements -> Analytics Data.) Then copy and paste it to ghostbin.co

**Comment by XITRIX** [comment]
Feel free to reopen this issue, but for now I will close it since you didn't answer
