### ISSUE TITLE
Feature request: Add a 0kb/s upload option 

### ISSUE THREAD

**Issue by mehdialonso** [XITRIX/iTorrent#126]
I have a slow adsl connection which is capped at 128kb/s upload and 512kb/s download speed, so uploading really affects downloading speed and make it really unusable, using itransmission I have that option to completely disable uploading Which makes my dl speed better.
It would be great to have that option in iTorrent as well, thank you.

**Comment by jojobrogess** [comment]
In general settings, 
Under “Background Downloading” you can toggle to allow or disable seeding. 
KEEP IN MIND, that even if you disable seeding, you will still see that you’re uploading a couple kbps or bps to your peers. That is normal. 

SIDE NOTE:
I have a connection like that, allowing seeding will help improve and keep your download speed to stay at max. 
I was never able to download at my connections maximum download speed if I completely stopped uploading altogether. I’d say cap your upload speed at either 20kbps or 30kbps. But do what you want lol 

If you want to set the download or upload speed to a specified amount then go to general settings and under “Speed Limitation” select download or upload. When the menu pops up click on the +- button to the top left and enter the speed amount. I literally just asked for this request and it was implemented in less than a day.. 
He replied in like 5 hours.

**Comment by jojobrogess** [comment]
Ohh and if you try to set the speed limitation value to “0” it won’t disable it, that value is for “unlimited”.  Would be best to toggle option like I stated above.

**Comment by jojobrogess** [comment]
Alright. I’m an idiot. Got home from work and tried to test my solution aaand it doesn’t work in that way. I apologize for my misjudgment. 
Toggling background seeding does does not affect the overall upload speed in that way. 
Lowest value I was able to get was 1024 B/s by inputting the value “01”. But inputting “2” gives the output of 2KB/s.

**Comment by XITRIX** [comment]
As @jojobrogess said, 0 speed limitation is "unlimited" limitation, also toggle for allow seeding, is only for background mode. I'll try to find the correct way to disable seeding, but now, the only way is to set seeding limitation to "1", also @jojobrogess, your "01" trims to "1" , so it was 1024b/s
