### ISSUE TITLE
[Request] Ace stream support

### ISSUE THREAD

**Issue by ed2007** [XITRIX/iTorrent#128]
Для полного счастья нехватает поддержки ace.

**Comment by XITRIX** [comment]
Если вас интересует просмотр видеофайлов параллельно с их загрузкой, то это возможно и сейчас:
- В настройках загрузки включите последовательную загрузку
- Сверните iTorrent, найдите файл через приложение Файлы
- Откройте его через любой сторонний плеер, например VLC

**Comment by ed2007** [comment]
Спасибо за ответ и великолепную программу! Я имел ввиду онлайн трансляции вида acestream://ebace2db83260b4d6097f0a52e8........
И еще подвопрос - последовательная загрузка файлов облегчает работу флешпамяти?

**Comment by XITRIX** [comment]
Ознакомлюсь с ними тогда, но пока ничего не обещаю.
По идее не должно никак на память влиять, хотя я не особо подкован в этом вопросе. Может только на скорость загрузки повлиять, особенно если на раздаче лицей больше чем сидов, так как торрент начнёт качать не части которые проще всего скачать, а по порядку.

**Comment by XITRIX** [comment]
К сожалению не думаю что смогу добавить поддержку Ace Stream в обозримом будущем, так что я пока закрою это ветку.
