### ISSUE TITLE
add_tracker

### ISSUE THREAD

**Issue by BJJFly** [XITRIX/iTorrent#13]
Currently support add_tracker ？ I Uncomment  the code, turned on this feature, add_tracker_to_torrent return 0, but did not add successfully

**Comment by BJJFly** [comment]
Tracker  has always  seeders = -1， peers = 0。  Is it normal？ 
because   TorrentStatus     numSeeds    numPeers   Always have data >0

**Comment by XITRIX** [comment]
I had commented it just because of this strange reaction, also -1 and 0 is just a placeholders for future if an author of libtorrent will add an ability to get seeds and peers from tracker.
It is possible that I had not understand something and it allows to get them, but now I don’t know how
