### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#131]
Not sure why or how to fix. Hope this picture helps.
![26557AA0-8316-40A9-BFD9-182AA029EA48](https://user-images.githubusercontent.com/16293689/91249243-57af8a80-e70b-11ea-9cd6-44be1ebdc046.jpeg)

**Comment by XITRIX** [comment]
You are using XCode 11, but I already implemented updates for iOS 14 using XCode 12 beta.
In this case XCode 11 is not supported anymore.

**Comment by gotzlotz** [comment]
Ok, will download the beta

**Comment by gotzlotz** [comment]
Had to pod update and get Xcode 12. Fixed.
