### ISSUE TITLE
1.8.2 doesn't show up in Files app

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#132]
After upgrading to 1.8.2, I can no longer access iTorrent within the Files app. Also, when sharing a file to a third-party app, what used to be instant, now takes up to a minute. I tried 1.8.2 (Hotfix), but that will not install at all (it won't install over the old app and when the old app is deleted first, Hotfix is shaded and says, "Try again later" when clicked. I reinstalled 1.8.1 and everything works again.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by XITRIX** [comment]
It was broken while I tried to fix torrent files opening from Files app and safari... 
I'll try to fix it in day or two, also I'll delete this release until I'll fix it

**Comment by XITRIX** [comment]
Reuploaded 1.8.2 with fixes

**Comment by SydneyUrshan** [comment]
1.8.2 with fixes wouldn't install over the old app (1.8.1). I deleted 1.8.1 and have the same problem as above. The app (1.8.2 with fixes) is shaded and when clicked it says, "Unable To Install "iTorrent" Please try again later."

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by XITRIX** [comment]
How did you install an app?

**Comment by SydneyUrshan** [comment]
Via App Center like all the others. I reinstalled 1.8.1 with no problem. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gotzlotz** [comment]
Is there a way to re-enable files app support in the most resent dev build?

**Comment by XITRIX** [comment]
If you are taking about 1.8.4-dev1 it should work. I had not disable Files app in that version, also it works on my iPhone

**Comment by gotzlotz** [comment]
Your right, I restarted my phone and it was in the files app again. Sorry 😅
