### ISSUE TITLE
Can’t link Patreon Account

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#134]
After I press the allow button, I get a safari can’t open page error while trying to connect to 127.0.0.1.

**Comment by XITRIX** [comment]
True... Are you on iOS 14?

**Comment by gotzlotz** [comment]
Yes, forgot to mention that

**Comment by XITRIX** [comment]
My iPhone on ios 14 also cannot link, but iPad on ios 13 works perfectly... Unfortunately I updated my iPhone to ios 14.2 but it still have no xCode support files in public, so I cannot debug it. I need to wait them to fix that problem, it will takes several days I think...

**Comment by gotzlotz** [comment]
That’s cool....take your time.

**Comment by XITRIX** [comment]
OMG!!! iOS 14 just uses the same port (55555) for unknown things and so iTorrent cannot bind it to link patreon account.
Apple says that it is a bug, but it is still not fixed, so I'll need to change the port, but old versions of iTorrent will lose an ability to link to Patreon....

**Comment by XITRIX** [comment]
Fixed, unfortunately, all previous versions lost an ability to link to Patreon.
