### ISSUE TITLE
iTorrent через App Clip

### ISSUE THREAD

**Issue by max000n** [XITRIX/iTorrent#135]
Возможно ли сделать запуск iTorrent через App Clip?

**Comment by XITRIX** [comment]
А можно чуть поподробнее расписать сценарий? Я пока не до конца понял что такое app clip, и тем более, как это связать с торрентом.

**Comment by max000n** [comment]
App Clips позволяет запускать приложения без их установки на iPhone.
По ссылке на сайте, т.е скорее всего без участия AppStore.
Пример: https://firigames.com/phoenix2

**Comment by XITRIX** [comment]
Звучит как запуск не подписанного кода, чего эппл бы ни в коем случае не допустил, скорее всего ios всё равно выгружает его с appstore просто без лишних манипуляций. Я посмотрю как оно работает, но думаю можно не надеяться на запуск неодобренного эпплом ПО, такого как торрент.

**Comment by XITRIX** [comment]
Именно, app clip хранится в app store и на устройстве открывается через специальную ссылку на app store, что в рамках приложения не находящегося в магазине просто не имеет смысла. Если я что то не так понял и в чём то ошибся, поправьте меня, но пока я закрою этот тикет, ибо реализовать это не представляется возможным.
