### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by ronadur** [XITRIX/iTorrent#136]
Ios 14.2 is not opening the app

**Comment by XITRIX** [comment]
![EF5F76FF-0F00-49CB-B00B-24B4FA629E73](https://user-images.githubusercontent.com/9553519/95012765-e0dbaa80-0643-11eb-9bca-8bfc3a95fd38.jpeg)
Opening.
Maybe your certificate has been revoked.
If you’ll find out the reason feel free to reopen this issue.
