### ISSUE TITLE
Hi, bro!

### ISSUE THREAD

**Issue by ghost** [XITRIX/iTorrent#137]
I have some problems with an app.
Pls tell me what to do!
It says: Can't install. Try again later![image](https://user-images.githubusercontent.com/72579136/95534676-17704700-09ef-11eb-96db-f8bc24ff5baf.png)

**Comment by XITRIX** [comment]
Привет, как ты устанавливаешь приложение? Эта ошибка означает, что либо у ресурса подписавшего его отозвали сертификат, либо подпись не предназначена для этого устройства.

**Comment by ghost** [comment]
Скачиваю с этого сайта: https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public
Сертификат я скачивал и подверждал в настройках

**Comment by XITRIX** [comment]
Не уверен какой именно ты сертификат скачал, но по данной ссылке можно скачать либо ipa с компьютера, для установки любыми известными способами, либо с jailbreak’ом и установленным AppSync (тогда iOS не будет проверять сертификат и установит приложение), я не предоставляю ссылок для установки приложения прямо с телефона без jailbreak’а. В гугле можно поискать сервисы предоставляющие возможность установить сторонние приложения, но рекомендовать какой либо я не рискну ибо сам ими не пользуюсь. Лично я бы ставил при помощи Cydia Impactor либо AltStore

**Comment by ghost** [comment]
Спасибо за разъяснение!
