### ISSUE TITLE
[Request] Integrated Browser in iTorrent

### ISSUE THREAD

**Issue by lmmensely** [XITRIX/iTorrent#138]
I think it would be great if the application had a built-in browser and that it had tabs, & from there iTorrent will download any type of files no matter the format😂😂

**Comment by XITRIX** [comment]
I already tried to integrate build in browser to download torrent files, but there were a problems, so I disabled it until I'll fix it. 
And no, iTorrent means that in downloads torrents) To implement downloading another files all application architecture must be rewritten, so it will not happen.
