### ISSUE TITLE
& What if iTorrent was integrated into the iOs Share Menu

### ISSUE THREAD

**Issue by lmmensely** [XITRIX/iTorrent#139]
Ok Let Me Explain ... If iTorrent Was Integrated IOs Contextual Menu & It Became An IOs Download Manager By Default ..... 😋, This Application Has A Lot Of Potential Since The Option You Included Of RSS Gives Me The  Idea that a lot can be done with it🙈🙈

**Comment by XITRIX** [comment]
As I explained earlier it will not be possible to integrate download manager in it, not in nearest future, so I will close this issue.
