### ISSUE TITLE
crash by  save_fast_resume

### ISSUE THREAD

**Issue by BJJFly** [XITRIX/iTorrent#14]
I found this function will lead to the app crash

                          {
                                "instruction_addr": 4355495076,
                                "object_addr": 4349476864,
                                "object_name": "iTorrent",
                                "symbol_addr": 4355495056,
                                "symbol_name": "libtorrent::session_handle::pause()"
                            },
                            {
                                "instruction_addr": 4349522416,
                                "object_addr": 4349476864,
                                "object_name": "iTorrent",
                                "symbol_addr": 4349522336,
                                "symbol_name": "save_fast_resume"
                            },.

**Comment by XITRIX** [comment]
Can you tell me how did you get it?

**Comment by BJJFly** [comment]
I am still recording this issue through more logs
