### ISSUE TITLE
Bundle ID

### ISSUE THREAD

**Issue by tyrrtechinc** [XITRIX/iTorrent#140]
When creating a custom icon, the app tries to open the bundle id as a torrent or magnet link.
![IMG_8549](https://user-images.githubusercontent.com/73202887/96654628-c1ae6f80-1309-11eb-9d3b-602220f62086.JPG)

**Comment by XITRIX** [comment]
Could you please describe all steps to reproduce? I am not an expert in jailbreak so it will be hard to answer.
