### ISSUE TITLE
Unable to install iTorrent 1.8.3 with 3uTools on iOS 14.2 (iPhone 12 Pro)

### ISSUE THREAD

**Issue by LetsGoRedWings** [XITRIX/iTorrent#145]
Hello - generally, are people able to installs iTorrent via 3uTools?

I've done some Googling on IPA sideloading, and it looks like it can be done, but I haven't added any certificate to my device so it's not clear to me if I need an Apple Developer account/certificate to install iTorrent via 3uTools to achieve this.

Also, do you have a Paypal/Patreon page I can make a donation to? Thanks,

**Comment by gotzlotz** [comment]
Not sure how to use 3uTools but do you have a Mac? If so you can use Xcode to either compile it and install or sideload. Try google sideload google with Xcode if you can compile it on your own.

**Comment by XITRIX** [comment]
The best ways I prefer to sideload apps are Cydia Impactor or AltStore. They are easy to use and you don’t need to have Apple developer account.
Yes, I have a Patreon page, you can find it [here](https://www.patreon.com/xitrix), thanks!
If you’ll have any questions, feel free to ask, but for now I’ll close this issue.

**Comment by LetsGoRedWings** [comment]
Alright so I installed Big Sur (!!) and Xcode 12.2 just now and I'm using this method to get the app on the device - https://docs.monaca.io/en/products_guide/monaca_ide/deploy/non_market_deploy/#install-using-xcode

The message I receive is "The certificate used to sign "iTorrent" has either expired or has been revoked. An updated certificate is required to sign and install the application."

From what I remember, you have to may have an Apple Developer account to notarize a binary - this is obviously different than submitting an app to the app store. This would facilitate easy side-loading via Xcode.

I would be willing to pay the cost of an Apple Developer account ($99 USD/year) to facilitate the easy method to sign the binary (drag and drop via Xcode -> Devices) - https://blog.codemagic.io/how-to-code-sign-publish-ios-apps/

The distribution IPA hosted on github can then be minted to include the signing certificate - https://dantheman827.github.io/ios-app-signer/

Let me know if this is something you would be interested in pursuing and a payment address.

I also donated to the Patreon as well :)

**Comment by LetsGoRedWings** [comment]
Scratch that, I ended up using Signulous - https://www.signulous.com/

Using iTorrent now for large LAN file transfers from server -> iOS device. Works great!
