### ISSUE TITLE
Не могу установить

### ISSUE THREAD

**Issue by nonStop46** [XITRIX/iTorrent#148]
![image](https://user-images.githubusercontent.com/74851555/99897536-3f6bef00-2cab-11eb-9d3d-7f91c9291cd0.jpeg)

**Comment by nonStop46** [comment]
Вечная проблема, раньше с ITransmission, теперь с itorrent. Из-за чего это? Сначала работает, через пару дней захожу-все, не работает. В сети не нашёл инфы, решил сюда написать. То ли я криворукий, то ли Apple блочит приложения...

**Comment by XITRIX** [comment]
Честно, впервые вижу подобную ошибку, ни малейшего понятия не имею, что она может значить.
От куда и как ставили приложение?

**Comment by nonStop46** [comment]
Прошёл по ссылке на последний релиз в appcenter, оттуда установил. Иконка приложения серая, при попытке запуска такая ошибка.

**Comment by nonStop46** [comment]
С сайта app.emu4ios.net тоже пробовал, та же история

**Comment by XITRIX** [comment]
Почитайте про Sideload на iOS девайсы, ссылка на AppCenter указана только для того, что бы через компьютер скачать последний тестовый билд и установить его, ну а как бонус она так же работает на устройствах с Jailbreak и AppSync, однако изначально так не задумывалось.
Что предоставляет сайт emu4ios я так же не знаю. Единственный рекомендуемый мной способ установки это самостоятельная переподпись ipa файла и его дальнейшая установка, с этим вам помогут приложения Cydia Impactor или AltStore. Есть и другие, но эти проверенные мной лично.
Вы конечно можете найти сайт с которого действительно можно скачать рабочее приложение прям на телефон, но такие обычно перестают в скором времени работать, так как Apple отзывает их подпись, ну а так же им никто не мешает встроить вирусное ПО в приложение.
Если будут ещё вопросы, спрашивайте, я пока закрою данный issue.
