### ISSUE TITLE
libtorrent 2.x

### ISSUE THREAD

**Issue by pangoo-reuse** [XITRIX/iTorrent#149]
please build to  libtorrent 2.x

**Comment by XITRIX** [comment]
I will

**Comment by alannzi** [comment]
> please build to libtorrent 2.x

**Comment by steve1234512** [comment]
I haven't a clue how to download any onto torrent on my iPhone 
I wish someone would help plz 😀

**Comment by Godfather1968** [comment]
￼I feel your pain my man dear lord it's terrible with iPhone￼. I'll get it download it for a day and it'll disappear by morning￼

**Comment by steve1234512** [comment]
That’s exactly what happens 
Ok at least I’m not the only one 
Thanks

**Comment by kovalensky** [comment]
News?

**Comment by XITRIX** [comment]
@kovalensky, [latest](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public) builds are already using libtorrent 2.0 so you are free to use it

Yea, need to close that issue
