### ISSUE TITLE
（keep）block the state of the metadata

### ISSUE THREAD

**Issue by BJJFly** [XITRIX/iTorrent#15]
Is there a limit on the number of tasks in the downloading, I found some strange phenomenon, if I have four magnet tasks in the downloading, when adding the 5th magnet, it will （keep）block the state of the metadata, but if I delete a downloading In the task, the fifth task will immediately enter the state of the downloading. I don't know if there is a limit on the number, or the delete operation triggers some other functions, making the metadata task enter the downloading state.

**Comment by XITRIX** [comment]
Yes, I think there is some limit on torrent downloading, because there is “Queue” state. I have not thought about it earlier, so I’ll read a manual for libtorrent, and will implement the ability to change the limit in settings if it is possible

**Comment by BJJFly** [comment]
Yes, I verified it many times and found a limit problem. I found that I can start the task by calling start_torrent (ha.hash).

**Comment by BJJFly** [comment]
Also, if I have a magnet link, how can I get it into downloading as soon as possible, I found the same magnet, using utorrent client can quickly complete the metadata step, but itorrent will take more time.

**Comment by XITRIX** [comment]
Sorry, but it is already a question to LibTorrent, I am not the creator of this library, I am just using it, so I don't know why Metadata state is so slow.
