### ISSUE TITLE
AppleTV Support

### ISSUE THREAD

**Issue by ghost** [XITRIX/iTorrent#152]
Hi! 

First of all, thank you for the amazing work and this really great product and continuous maintenance! 

I'm an iOS dev and started experimenting with AppleTV. 
I created an AppleTV target in your app and wanted to create some UI for the it, but the static framework is only supporting iOS targets. 

If it's not a huge task to do, could you rebuild your framework with AppleTV platform support?

Thanks!

**Comment by XITRIX** [comment]
Ok, I’ll try

**Comment by XITRIX** [comment]
https://github.com/XITRIX/iTorrent_Framework/releases/tag/1.9-b1
Builded 2 variants of Framework: tvOS only and Universal one, don't know how to test if them works, but I think they should.
I'll close this issue for now, if there will be any problem feel free to reopen it.
I'm looking forward for any progress!

**Comment by ghost** [comment]
Thank you very much! 
I'll try my best and keep you updated if I could make any usable TVOS version of it!
