### ISSUE TITLE
RSS Error

### ISSUE THREAD

**Issue by iYodah** [XITRIX/iTorrent#153]
Error received when adding RSS feed.

Device info: iPhone 7+, iOS 13.3, unc0ver 5.2, signed with own certs

ERROR

The operation couldn’t be completed.
(iTorrent.RssModel.Error error 0.)

Fix this and I’ll gladly drop a donation.

Edit: attached screenshot, also want to mention I may have a signing solution for you.
![D20B6870-BD36-4B25-8B40-02C2A946CA7B](https://user-images.githubusercontent.com/36976509/101141570-7a8eec00-35e2-11eb-903b-9e73f4c38b42.png)

**Comment by XITRIX** [comment]
Could you attach your rss url?
I use rss everyday and it works without any problem.
What kind of signing solution do you have?

**Comment by iYodah** [comment]
https://www.torrentday.com/t.rss?1;2;3;7;21;24;25;26;31;33;34;44;45;46;48;u=2278225;tp=77e1b0a20c77f0314b8d296f217fe276

I happen to own a signature service lol

**Comment by XITRIX** [comment]
Wow, that's great, it would be awesome to have some kind of "official" way to install iTorrent without PC.
I'll try to fix that problem in next week, I have no enough time to work on iTorrent, but I don't think it is something hard to fix.

**Comment by iYodah** [comment]
Sounds good to me. Feel free to drop me an email and we can discuss a possible partnership for iTorrent. Yodah [at] iCloud [dot] com

**Comment by XITRIX** [comment]
Fixed. Check the latest dev build. I sent you a mail.
