### ISSUE TITLE
Can’t install on iPad 8th gen due to udid issue

### ISSUE THREAD

**Issue by dnavigator** [XITRIX/iTorrent#154]
Someone add udid of iPad 8th gen udid to the ipa file

**Comment by XITRIX** [comment]
What kind of "udid of iPad 8th gen" you are talking about? 
Udid is the unique ID of EVERY device, not of certain model.
iTorrent supports every iDevice with iOS 9.3+ on board, and it should not be modified to support your device. 
If you are trying to install iTorrent by AppCenter link without jailbreak, you are doing wrong. This link is only for devices with AppSync installed. If not, you should use AltStore or Impactor to install this app.
