### ISSUE TITLE
Pick where torrent files are saved? (OneDrive, iCloud, etc)

### ISSUE THREAD

**Issue by Sorn1961** [XITRIX/iTorrent#155]
Hi, is it possible for iTorrent to allow users to enter a path where torrent files are saved to by default (instead of in the iTorrent folder on the device)? Such as cloud services (onedrive, icloud, etc).

**Comment by XITRIX** [comment]
Yes, I think iOS supports such feature, I’ll try to add it.

**Comment by tonysprenk** [comment]
Would be very interested in this. Would be nice to be able to save to a local file server through the files app.

**Comment by XITRIX** [comment]
v2 added support this feature
