### ISSUE TITLE
Can't build it. 

### ISSUE THREAD

**Issue by mrozado** [XITRIX/iTorrent#16]
MarqueeLabel and firebase make it imposible to build it.

**Comment by XITRIX** [comment]
Have you builded pods before compiling?

**Comment by mrozado** [comment]
Yes I did.

<img width="693" alt="screenshot 2018-11-01 at 11 26 09" src="https://user-images.githubusercontent.com/426661/47857671-05300c00-ddc9-11e8-96c8-67e74cf47f80.png">

**Comment by XITRIX** [comment]
I have recloned this repo, to check compilation without any changes, and it compiles without any problems, have you opened xcworkspace? (not xcodeproj)
And if yes, can you send a screenshot with this error?

**Comment by mrozado** [comment]
Hi there! I was not opening the xcworkspace. Now it's building like a charm. 

Thanks!
