### ISSUE TITLE
No Notifications

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#160]
Not getting any notifications with the latest dev build on iOS 14.3.

**Comment by XITRIX** [comment]
That's strange, I have lots of notifications from iTorrent every day (RSS).
What kind of notifications you don't have?

**Comment by gotzlotz** [comment]
Finished downloading.

**Comment by XITRIX** [comment]
Ok, I'll check it.
I think it's true, cause I thought I just missed them, but maybe I really broke them.

**Comment by XITRIX** [comment]
Fixed.
