### ISSUE TITLE
iTorrent AltStore Source

### ISSUE THREAD

**Issue by noah978** [XITRIX/iTorrent#161]
So I've been trying to get more of the open-source iOS app developers to consider making their own [AltStore Source](https://noah978.github.io/AltStore-Docs/Sources) before the feature eventually releases to the public build (No ETA on that as of right now) of [AltStore.](https://altstore.io)

But if you are interested in generating an AltStore Source, the devs behind UTM put together a combination of a github workflow and Node.js to convert github releases into the complete AltStore Source.

You can check out the [repo for it](https://github.com/osy/altstore-github) and the [UTM app it's used with](https://github.com/utmapp/altstore-repo/tree/gh-pages).

Even if you aren't a fan of the automated approach, it would still be nice to have an iTorrent AltStore Source in the future.

**Comment by XITRIX** [comment]
Great idea, I already made my local AltStore source, just for test purposes, but link source with github releases is much cooler. 
Thanks for examples, I'll try to implement it!

**Comment by ideologysec** [comment]
@XITRIX any progress on this?

**Comment by noah978** [comment]
It'd still be a good idea to make your own AltStore source for automatic releases so that you can fully control the appearance in AltStore, but I will note that https://quarksources.github.io is now checking the iTorrent github releases (along with a slew of other apps) every half hour and will pull updates into the AltStore Source automatically,

**Comment by david-ns** [comment]
@XITRIX now that AltStore PAL is available, are you planning to notarize the app and distribute it through that alternative store?

**Comment by XITRIX** [comment]
I've bought subscription for AltStore PAL today and right now in the process of reading documentation of how could I publish my app in thirdparty marketplace, so yes, I definitely going to try :)

**Comment by danielgarciagarcia** [comment]
Hey @XITRIX any progress on this notarization topic? :) Thanks for your great work!

**Comment by XITRIX** [comment]
> Hey @XITRIX any progress on this notarization topic? :) Thanks for your great work!

From my side everything is done, waiting for AltStore third party sources release

![IMG_2120](https://github.com/XITRIX/iTorrent/assets/9553519/ffc30a83-18ed-4641-919d-471c094b1b98)
