### ISSUE TITLE
[Request] Options to change limitation of simultaneous downloads

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#162]
In most cases, only three torrents can be downloaded at one time. There have been times I got it up to 20–25 at once, however, it takes strategy (and time) not unlike a Rubik's Cube or chess. Then in the event of a crash or reboot, it goes back to three downloading with the remaining torrents placed on pause. Sometimes a pesky torrent that has been going for weeks gets down to the last few seconds, then bumped to pause making it necessary to manually pause everything (except two others) to finish, usually taking hours more, or longer, because of a lost window of opportunity. Basically, torrents with few seeds tie up the three maximum allotment making it so I have to ultimately forego them altogether for more active ones. With the limitation of simultaneous downloads removed, I can add less active torrents and let them go for weeks or more without worrying about them tying things up.

**Comment by XITRIX** [comment]
Added options to change limitations for queue inside settings in Dev branch.

**Comment by SydneyUrshan** [comment]
This feature works great. I ran a lot of simultaneous torrents, some successfully for over a month without any crashes from it (the only crashes were sometimes when deleting files which happened before this addition). Though this may be a moot point now if the app was discontinued per my other issue posted earlier.
