### ISSUE TITLE
itorrent does not open. In ios 14.5 beta version. Why is that so...

### ISSUE THREAD

**Issue by starmanya** [XITRIX/iTorrent#165]
latest itorrent does not open. In ios 14.5 beta version. Why is that so...

this is video link. plz..

https://youtu.be/J35VfPkjWck

**Comment by XITRIX** [comment]
Have you tried to reinstall it?

**Comment by starmanya** [comment]
> Have you tried to reinstall it?

I've reinstalled several times.

**Comment by starmanya** [comment]
14.4 version ipad also does not work.

**Comment by starmanya** [comment]
I install ipa using 3utools. Is there any other way?

**Comment by XITRIX** [comment]
Your "crash" not looks like crash, cause app closes before it even start loading, it's more like broken signing certificate, but I cannot do anything about that, sorry. I could suggest you to install app using Cydia Impactor or AltStore, it is the only way I could guarantee for successful install.

**Comment by starmanya** [comment]
thx for reply...😭
