### ISSUE TITLE
the app cannot be installed because its integrity could not be verified

### ISSUE THREAD

**Issue by Signup-pawan** [XITRIX/iTorrent#168]
Hello, I was trying to install this app through [Diawi](https://www.diawi.com/) on my iPad and after some time it is showing the error as mentioned in the title.

Can anyone please help to resolve this error?

**Comment by XITRIX** [comment]
If you have not resigned ipa file with your own certificates, it will not install. I'm not familiar with Diawi, but I think it's distribution utility, not sideloading, so it will not resign an app.
Use Cydia Impactor or AltStore to install iTorrent.
