### ISSUE TITLE
iTorrent

### ISSUE THREAD

**Issue by max000n** [XITRIX/iTorrent#17]
Спасибо, отличное приложение.
Пожелания:
1. Приоритеты при скачивании
2. Отключение раздачи
3. Импорт всех файлов в плеер/файл
4. По возможности хотелось бы видеть изменения в интерфейсе, на подобии не вышедшей версии iTransmission9
![bc91a418-b937-45ed-88c7-7e27afb2ff3f](https://user-images.githubusercontent.com/44770168/47991851-5824fe80-e0fc-11e8-8f73-6e936ecf7aaf.png)

**Comment by XITRIX** [comment]
Спасибо за отзыв и пожелания, пройдусь по ним по порядку:
1) Я хочу добавить эту опцию, только не совсем понимаю как её сделать для мобильного интерфейса, но что нибудь придумаю
2) Так имеется переключать для раздачи, который, между прочим, по стандарту выключен, а значит и раздача не идёт. Даже лимит на раздачу можно выбрать
3) Обязательно добавлю
4) Не совсем понимаю что вам не нравится в нынешнем интерфейсе, тут я старался как мог, а так же я попробовал найти iTransmission 9 про который вы говорили, но всё что я нахожу это 5ю версию, если вы из будущего, поделитесь ipa-шечкой))

**Comment by max000n** [comment]
1. Как вариант через свайп на каждом файле
2. Даже при выключенной раздачи она к сожалению происходит.
3. Отлично, а то действительно не хватает этого)
4. Интерфейс нравится, единственно приходится делать много действий, чтобы совершить что-то, поэтому и предлагаю вариант интерфейса iTransmission9. У меня нет ipa iTransmission9, пару лет назад проходил набор тестеров, но из теста он так и не вышел.

**Comment by XITRIX** [comment]
А у вас стоит версия 1.6? Просто я не буду отрицать что раньше был баг с раздачей, когда она шла даже после завершения, но я это исправил в последней версии и сейчас состояние Готово(Finish) это именно остановленная загрузка и раздача, скорости по нулям

**Comment by max000n** [comment]
Да у меня версия 1.6. Подскажите, где можно взять актуальную версию?)

**Comment by XITRIX** [comment]
Так она и есть актуальная)
Я не сразу понял про что вы, я подумал что у вас раздача идёт даже после окончания загрузки торента, а не во время загрузки, так как раньше был именно такой баг. Это правда что я не отключал раздачу во время загрузки, но на то как мне кажется была причина, если не ошибаюсь, подобной опции не было в библиотеке libTorrent, которую я использую, однако я проверю ещё раз.
Переключатель "Раздача" сейчас ответственен за остановку торента и фоновой работы по его завершении, и если раздача разрешена, то по завершении загрузки приложение продолжит раздавать файлы

**Comment by Joy096** [comment]
Годное приложение, спасибо! Пару предложений, что хотелось бы увидеть: 
- последовательная загрузка частей торрента, чтобы можно было, к примеру, фильм смотреть пока он скачивается. В utorrent на ПК это настраивается через пункты в доп. настройках
bt.sequential_download и bt.sequential_files (первая настройка при включении заставляет µTorrent скачивать части строго последовательно, от первой к последней, вторая указывает клиенту скачивать по порядку файлы)
- регулировка количества одновременно скачиваемых торрентов

**Comment by XITRIX** [comment]
Спасибо за высказывание пожеланий:
1) Я был бы рад добавить такую опцию, но она вероятно потребует вмешательства в библиотеку libTorrent, хотя возможно это можно реализовать без её изменения, посмотрю что к чему, а последовательное скачивание файлов, это можно, думаю добавлю в ближайших обновлениях.
2) Я, кажется, уже давно добавил функции для настройки этого параметра и просто забыл его добавить в настройки, добавлю

Edit—-
Я посмотрел документацию, там можно выставить порядок скачивания кусков файла, только теперь мне не понятно, это стоит сделать отдельной настройкой к торенту, или настройкой к файлу, или вообще автоматически применять если формат файла mp4/mkv и и.п.

**Comment by Joy096** [comment]
Я думаю стоит сделать настройкой к торрент - клиенту чтобы не заморачиваться, на скорость это никак не влияет насколько я знаю, а кому не нужно будет - отключат. У меня на ПК эта настройка стоит для всего и никаких проблем.

**Comment by XITRIX** [comment]
Да, думаю так будет проще всего

**Comment by max000n** [comment]
Подскажите, когда планируется выпуск новой версии? А также если возможно список нововведений.

**Comment by XITRIX** [comment]
На данный момент уже готово:
- Выбор приоритета для файлов
- Групповая отправка файлов
- Небольшие фиксы в локализации

Пока не выкладываю их, так как не совсем уверен в их удобстве и просто тестирую
Позже добавлю всё остальное о чём говорилось в этом issue, но на данный момент я сильно занят, по этому примерную дату назвать не могу

**Comment by max000n** [comment]
Спасибо за комментарий. Ждём новых версий)

**Comment by Kyogre** [comment]
хотелось бы иметь возможность копировать данные из полей в информации о торренте, например "хэш", "комментарий" и прочие

**Comment by max000n** [comment]
Подскажите, что ожидать в новой версии и когда релиз?

**Comment by XITRIX** [comment]
На данный момент я нашёл работу, по этому работа над приложением приостановилась, думаю, если будет время поработать над ним, добавлю поиск по торенам в загрузке и копирование информации из полей, вероятно попробую ещё обновить libtorrent, но по срокам ничего сказать не могу, на данный момент приложением я сам же пользуюсь на постоянной основе и каких то идей для нововведений, кроме поиска, мне не приходило

**Comment by max000n** [comment]
По возможности обнови торрент клиент под iOS 13, не добавляет торрент файлы через сафари. Добавление файла происходит только через вставку прямой ссылки.
