### ISSUE TITLE
Large Torrent Crashes

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#170]
It may not be possible to remedy, but this torrent crashes as soon as I attempt to cherry-pick a file from it, usually when I open the Files section. I did manage to get one file after crashing 3–4 times. I have downloaded large torrents in the past (140GB), but this one is 3.4TB. As always, thanks for all of your hard work!

https://www.btmet.com/item/5960f0b3d6fa7f017122f0036c4079b71ddd3e94

iTorrent 1.8.4-dev.1, iPhone 7 Plus, 256 GB, iOS 14.4

**Comment by XITRIX** [comment]
Fix has been merged, will be available in next dev build.
