### ISSUE TITLE
Cannot install app

### ISSUE THREAD

**Issue by danteaaron** [XITRIX/iTorrent#175]
App download appears greeted out on some screen, and when clicked, error message says "This app could not be installed because its integrity could not be verified."

**Comment by XITRIX** [comment]
How did you install it?

**Comment by LilDooDoo** [comment]
Thanks for replying! I installed I through the download link on Appcenter (dev build) as I was not able to figure out how to install the .ipa file for the stable build. Was this the correct way?

**Comment by danteaaron** [comment]
> How did you install it?

Thanks for replying! I installed I through the download link on Appcenter (dev build) as I was not able to figure out how to install the .ipa file for the stable build. Was this the correct way?

**Comment by XITRIX** [comment]
No, it will only work on jailbroken device with AppSync installed, the right way to install app without jailbreak is using Impactor or AltStore. You could find more information about them in Google.
If you'll have more questions feel free to ask here, but for now I'll close that issue.
Good luck!
