### ISSUE TITLE
Data consuming

### ISSUE THREAD

**Issue by Pundainayai** [XITRIX/iTorrent#177]
I been using iTorrent for a while now and I have noticed everytime I use iTorrent it uses my cellular data instead of Wifi.

I personally toggled off cellular data for iTorrent and it still manages to use my cellular data.

I know I can turn off my data when downloading but then I cannot receive picture messages and etc

**Comment by marcoms** [comment]
I think I've noticed this too, I'm hesitant to use the app now.
