### ISSUE TITLE
I can’t get itorrent on my iPhone

### ISSUE THREAD

**Issue by steve1234512** [XITRIX/iTorrent#178]
Can anyone help plz

**Comment by steve1234512** [comment]
I normally download through app valley
But only lucky if I catch it when it allows you to 
Their must be a better and forever way

**Comment by XITRIX** [comment]
Duplicate of #175

**Comment by steve1234512** [comment]
Sorry to be a pain and I’m not very techy 
Love to be able to have itorrent as much as poss 
Is there a way of doing so 
Thanks 
Steve

**Comment by XITRIX** [comment]
I attached an issue where I already told how to install iTorrent.
Search in google apps Impactor and AltStore.
If you'll have more questions feel free to ask!

**Comment by Godfather1968** [comment]
What about IOS?
