### ISSUE TITLE
The AppCenter profile refuses to install

### ISSUE THREAD

**Issue by mcandre** [XITRIX/iTorrent#179]
When I tap `Install` on the downloaded AppCenter profile, it launches the AppCenter website. But it refuses to actually install the profile locally. It loops like that forever. The profile never fully completes installation.

When I navigate to my apps, the list is empty and it says "No apps available for your device". I'm not sure what to make of that message. Does it mean that the profile needs to be completed? Does it mean that truly no iPad apps from AppCenter are available at all for my device?

I can even see my iPad listed as a device now. But still, the profile is not installed locally.

This failure of the AppCenter profile installation prevents the iTorrent application from running.

I tried uninstalling and reinstalling iTorrent.

I tried rebooting. All that does is delete the profile entirely, and so I have to redownload it. Same problem as before.

I tried setting Safari as my default browser.

I tried disabling desktop view.

I tried both the light and dark themed two AppCenter sites.

**Comment by XITRIX** [comment]
AppCenter link will work only with jailbroken devices with AppSync installed. Otherwise you could use AppCenter to download latest dev version of ipa file and install it with Cydia Impactor or AltStore.
