### ISSUE TITLE
Torrents Have Stopped Downloading In Background

### ISSUE THREAD

**Issue by LynetteCullens** [XITRIX/iTorrent#18]
I’ve enabled background downloading. It still doesn’t work. When I switch apps without closing the torrent app, the download re hash.

**Comment by XITRIX** [comment]
It could crash on entering into background because of “strange” torrent file or broken savestate file.
Try to remove _Config folder, I hope it will fix your problem, but save torrent files from it, if you’ll need them

**Comment by XITRIX** [comment]
If you still have this problem, you’re welcome to reopen this issue
