### ISSUE TITLE
Wanna help with tr

### ISSUE THREAD

**Issue by MortazaMinoz** [XITRIX/iTorrent#180]
How can I help u to add Arabic language to the app?

**Comment by XITRIX** [comment]
Hi, thanks for the desire to translate iTorrent.

To do that, you need to add new language into project settings, and translate 2 files: 
- Localizable.strings
- Main.storyboard (Main.strings)

It will be better if you'll start your translation into Dev branch, cause it contains new options and settings, that also needed to be translated.
