### ISSUE TITLE
Installing 

### ISSUE THREAD

**Issue by brad1983** [XITRIX/iTorrent#183]
Is there any way to load this ipa and get more than a week or two ? Or from other sites? I love this app, can’t live without it!

**Comment by gotzlotz** [comment]
> Is there any way to load this ipa and get more than a week or two ? Or from other sites? I love this app, can’t live without it!

I like appdb. It’s like $20 a year.

**Comment by brad1983** [comment]
How long will the app work before needed to be signed again?

**Comment by gotzlotz** [comment]
1 year

**Comment by brad1983** [comment]
And I can load the ipa through appdb, then install it without a pc?
I will need the pro version I assume…

**Comment by gotzlotz** [comment]
Yep…also I believe is some were in there. Not sure what version.

**Comment by brad1983** [comment]
Thanks for the help, I don’t think it will work. I didn’t get the pro, but it should install for atleast 7 days. It says something about the integrity could not be verified and shows a grey app. If I can’t test it I don’t think I will risk the pro fee. Thanks again for the help

**Comment by gotzlotz** [comment]
No problem, I’ve been using the service for 5 years. If that helps any.

**Comment by brad1983** [comment]
I decided to buy the pro and try it lol!

**Comment by brad1983** [comment]
I had to set me device as not jail broken, but I got it!

**Comment by gotzlotz** [comment]
Nice…

**Comment by brad1983** [comment]
Thanks again!
