### ISSUE TITLE
"iTorrent Is No Longer Available"

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#184]
This is the message I get now when I click on the app. Is it an error or did you discontinue the app?

Besides the occasional crash when deleting files, the app has been working excellent until now.

In any case, thank you.

**Comment by XITRIX** [comment]
No, I'm not discontinue the app. What kind of message is it? Does it appears after, or before launching? Does this message prevents app from launching or not?

**Comment by SydneyUrshan** [comment]
What a relief!

I get the message when I directly click on the app itself with an "OK" option (I cannot proceed with anything until I click it). I could still use the (running) app when accessed via the app selector, but I can no longer access the app now because I relaunched it. I also restarted the phone and reinstalled the app. I didn't delete the app (yet) because once I do, I will lose a lot of work. Luckily, as I go, I save sequentially completed files to another app (nPlayer) and upload to storage from there in the event of catastrophes and to prevent lengthy hashing after crashes.

**Comment by XITRIX** [comment]
I think it's because signing certificate was outdated.

**Comment by SydneyUrshan** [comment]
Will you be updating the certificate? Is there anything I can do to help?

**Comment by XITRIX** [comment]
Send me your UDID.

**Comment by SydneyUrshan** [comment]
Sent via Patreon, thanks!

**Comment by brad1983** [comment]
This is a great app

**Comment by XITRIX** [comment]
Issue resolved
