### ISSUE TITLE
[Request] File Location Selection

### ISSUE THREAD

**Issue by SkipperQ93** [XITRIX/iTorrent#187]
I have been using your application for quite some time and it's been amazing in all aspects. I like to organize files when it comes to a large number of files. For torrent app on mac I simply create subfolders (like movies, tv, apps) inside torrent directory. I did not find such a feature here. Is this something that can be implemented?

**Comment by XITRIX** [comment]
I think it's not impossible, unfortunately, I have not enough time to develop new features for iTorrent right now, but this request definitely will be in my todo list.

**Comment by bogdanlivadaru** [comment]
I am also looking forward to this feature to make use of my home NAS server.

**Comment by ArtemDyachuk** [comment]
I'd like to chime in. This would be a killer feature with new USB-C iPhones and iPads.
Especially for devices with less built-in storage.

Either to "Select Default Location" or an option to Select destination for every upload.
Subbed.

**Comment by XITRIX** [comment]
Implemented in v2
