### ISSUE TITLE
iOS 15 support

### ISSUE THREAD

**Issue by brad1983** [XITRIX/iTorrent#188]
I upgraded too soon and looks like I can’t use itorrent. Is there a fix or am I way too early? Will this be supported for 15?

**Comment by gotzlotz** [comment]
It’s not the app. It’s all side loaded apps in general. If you compile with Xcode it will work.

**Comment by brad1983** [comment]
I don’t know how to do that. I download from here and then load it through appdb

**Comment by gotzlotz** [comment]
I used Appdb also. I think they posted on there twitter that they would update the service for iOS 15 soon.

**Comment by brad1983** [comment]
Great thanks!

**Comment by gotzlotz** [comment]
Appdb was updated
