### ISSUE TITLE
How To download without signing, myself .

### ISSUE THREAD

**Issue by Akczht** [XITRIX/iTorrent#189]
I want to know how can I install it and forget it needs to ve signed again , except the alt store method , I just want it to be like any other appstore app , can this app be snuck into appstore and installed quietly.

**Comment by gotzlotz** [comment]
Don’t think it can sneak into the appstore. I use Xcode to compile it and install. If you don’t want to use xcode then I would try Appdb.

**Comment by Akczht** [comment]
@gotzlotz does xcode method require , signing the app .

**Comment by gotzlotz** [comment]
Yes, but everything requires signing the app. If you don’t have a developer account it will sign it for 7 days with your Apple ID. After 7 days you just have to do it again with Xcode.

**Comment by Akczht** [comment]
@gotzlotz Thanks! , any other way to get torrent in ios with the apps from appstore ?

**Comment by gotzlotz** [comment]
Don’t think so.

**Comment by KevinBlue18** [comment]
@Akczht Apple doesn't allow torrent clients in the App Store.
