### ISSUE TITLE
Crashes on Large Files Hashing

### ISSUE THREAD

**Issue by syto203** [XITRIX/iTorrent#19]
Downloading a 30GB file, after it passed 19GB the app crashed. re-launched the app and started rehashing; however, the app either crashes or downloads really slow 10-15KB.

**Comment by XITRIX** [comment]
I'm not sure, cause I'm not the developer of the torrent engine, but I'm afraid it could use RAM for hashing. Can you give me an example of this torrent file with "problem"?
