### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by TD540** [XITRIX/iTorrent#191]
<img width="439" alt="Screenshot 2021-07-01 at 22 47 08" src="https://user-images.githubusercontent.com/286605/124187564-4cad4f80-dabe-11eb-9123-7d76bfde2bb0.png">

deployment target set to 12.3 and a bunch of other targets are upgraded

but building failed

where is "Type 'String' has no member 'all'" coming from ?

using macOS 12 dev b2, xcode 13 b2, iOS 15 b2

**Comment by lslqtz** [comment]
You just need to solve the first error, change the value (.all) to UserPreferences.interface

**Comment by wtrocki** [comment]
Seen that as well. It works after. Would this require PR?

**Comment by XITRIX** [comment]
You should build "Dev" brunch, it builds without any problem

**Comment by branimir29** [comment]
After changing .all as suggested I get different set of errors trying to Build:

Incorrect argument label in call (have 'downloadLimit:uploadLimit:enableDht:enableLsd:enableUtp:enableUpnp:enableNatpmp:interfaceType:portRangeFirst:portRangeSecond:proxyType:proxyRequiresAuth:proxyHostname:proxyPort:proxyUsername:proxyPassword:proxyPeerConnection:', expected 'downloadLimit:uploadLimit:enableDht:enableLsd:enableUtp:enableUpnp:enableNatpmp:outgoingInterfaces:portRangeFirst:portRangeSecond:proxyType:proxyRequiresAuth:proxyHostname:proxyPort:proxyUsername:proxyPassword:proxyPeerConnection:')

Any suggestions how to fix this?
