### ISSUE TITLE
Why it crashes？

### ISSUE THREAD

**Issue by 2856571872** [XITRIX/iTorrent#197]
![image](https://user-images.githubusercontent.com/10896490/129673916-9990804a-294f-4857-ba14-cdb3b0f8f251.png)
torrentLocalPath  
"/var/mobile/Containers/Data/Application/A8CC1F82-58BF-4375-835E-4A31D1DF1467/Library/Caches/DiskFiles/faeeb9594b3d4c4594ef311e5fbe48c8.torrent"

**Comment by 2856571872** [comment]
Thread 1: EXC_BAD_ACCESS (code=1, address=0x1f)

**Comment by XITRIX** [comment]
Need more context.
How to reproduce?
Attach torrent file if crash specific to it.

**Comment by 2856571872** [comment]
> Attach torrent file if crash specific to it.
I tried a lot of torrent files and they crashed. The file path is real and valid. Why does it crash when I join the download queue. Is there a problem with the SDK method call?

**Comment by XITRIX** [comment]
Tell me steps for reproduce, I have no problems with torrent adding.
As I see, the code on screenshot is not mine, so how I could tell you “why it’s crashing”?

**Comment by 2856571872** [comment]
> Tell me steps for reproduce, I have no problems with torrent adding.
> As I see, the code on screenshot is not mine, so how I could tell you “why it’s crashing”?

I think so too, maybe there is a problem with my calling method.
The way to reproduce is very simple, I integrated ITorrentframework into my project
1. Download the torrent file
2. 
`

            let temp = TorrentSdk.getFilesOfTorrentByPath(path: torrentLocalPath)!

            let files = temp.files

            files.forEach { $0.priority = .normalPriority }

            if let hash = TorrentSdk.getTorrentFileHash(torrentPath: torrentLocalPath) {

                TorrentSdk.addTorrent(torrentPath: torrentLocalPath, states: files.map { $0.priority })

                TorrentSdk.startTorrent(hash: hash)

            }
` 
3."TorrentSdk.addTorrent" crashed
I think I may have missed some configuration. I am also looking at the ITorrent APP to find the problem, thank you very much for your answer
