### ISSUE TITLE
Do we need an update ?

### ISSUE THREAD

**Issue by Akczht** [XITRIX/iTorrent#198]
Hey! , XITRIX are you planning to update the app ? are you working on something big ? whatever you're doing . Just don't abandon the project .

**Comment by XITRIX** [comment]
Hi, right now I'm working on Moonlight-Switch project, iTorrent will be updated for new versions of iOS, but for now I have not enough time to make any new features for it.

**Comment by Akczht** [comment]
felt good to hear back
