### ISSUE TITLE
File Picker Crash

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#2]
App crashes after file picker when adding a torrent via Safari.

**Comment by XITRIX** [comment]
I know that sometimes that problem appears, but I have no idea how to catch it.
I'll try to fix it as soon as possible.

**Comment by gotzlotz** [comment]
It’s been happening with every torrent and magnet link added via safari. I’m using the ipa version.  I will try to use Xcode to compile it and see it it still happens.

**Comment by XITRIX** [comment]
It would be great, because I have this problem very rarely, and I cannot catch it with xcode

**Comment by gotzlotz** [comment]
I’ve installed it with Xcode and still get the crash. Seems to do it from a closed state like after a restart or a few hours after it’s been idle. I have a iPhone X. Not sure it that will help.

**Comment by XITRIX** [comment]
I think I had fixed it

**Comment by gotzlotz** [comment]
Been using it for 24hr, No crash. Thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lil27** [comment]
😂1
