### ISSUE TITLE
не начинается загрузка некоторых торрент-файлов

### ISSUE THREAD

**Issue by Kyogre** [XITRIX/iTorrent#20]
Большинство торрентов скачиваются нормально, но попадаются и такие, которые через itorrent не начинают скачиваться вообще, хотя мгновенно стартуют через utorrent на Windows. Пример такого торрент-файла выслал тебе в qms на 4pda.

**Comment by XITRIX** [comment]
Хмм... и правда не работает. Торентовый движок так то я брал готовый, по этому с ходу думаю не смогу понять в чём проблема, но могу попробовать обновить его до актуальной версии, может поможет.

**Comment by fomalsd** [comment]
По-прежнему это так, некоторые торренты отказываются качаться наотрез, хотя на ноуте рядом подцепляются быстро. 
Может, снова обновить libtorrent? сегодня вышла версия 1.2.2, например

**Comment by XITRIX** [comment]
В версии 1.2 сильно поменяли логику некоторых важных функций, ввиду чего приложение начинает очень коряво работать, из-за этого я временно откатил версию обратно, так как нет особо много времени разбираться в том, что поменялось. Если будет время, постараюсь обновить до актуальной версии.

**Comment by XITRIX** [comment]
Добавил поддержку https протокола для трекеров, теперь должны скачиваться абсолютно любые торрент файлы
