### ISSUE TITLE
iTorrent Needs to Be Updated for iOS 15

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#203]
I just installed iOS 15.0 and now receive the following error when clicking on the app:

"iTorrent Needs to Be Updated
The developer of this app
needs to update it to work with
this version of iOS.
OK"

As always, thanks for the great app and all your efforts.

**Comment by XITRIX** [comment]
I have already updated it to iOS 15 using Xcode 13, update it with latest dev version.
