### ISSUE TITLE
How to export/stream video to other apps or player?

### ISSUE THREAD

**Issue by pushkin2023** [XITRIX/iTorrent#205]
Hi, what is the possibility to share the downloaded files to a player?
Thanks!

**Comment by XITRIX** [comment]
Open torrent details -> Files and click share icon, you'll be able to send it to another app (VLC i.e.).
You also could find downloaded files in Files app

**Comment by pushkin2023** [comment]
That's how i tried but i don't have the VLC app in the Share dialog, i also have self build VLC version and neither that appears. but if i share a video file from some other app, i can see both VLC apps in the share view. So i'm not sure where and what the problem is..
Is there any 'limitations' regarding the file share..? I also tried with different video files avi, mpeg, mkv..

Thanks

**Comment by XITRIX** [comment]
No, there is no limitation inside app, but theoretically there could be a problem, if ipa file was incorrectly signed, but I'm not an expert in that sort of questions.
Anyway, downloads should be inside of Files app, there should not be a problem to share them from it.

**Comment by pushkin2023** [comment]
I have the ipa signed with dev certificate. The thing with Files App is that is available from ios 11, and i aim for lower ios, since i have a bunch of devices..

**Comment by XITRIX** [comment]
Oh, in that case I'm not sure what I could suggest to you...
I'm not sure if there are any differences in file sharing in older ios versions
