### ISSUE TITLE
integrity could not be verified on 26 Sep built

### ISSUE THREAD

**Issue by cmichaelhk** [XITRIX/iTorrent#206]
Hello 
I am new to itorrent.
When I install the app via appcenter, it said “this app cannot be installed because its integrity could not be verified”

ios15, 
iTorrent
Version 1.8.4-dev.3 (21.0)
Sep 26, 2021 at 17:41
11.33 MB

INSTALL
iOS 15 UI fix

**Comment by XITRIX** [comment]
If you are trying to install it via AppCenter, it could only be installed on Jailbroken devices with AppSync with this way.
If you are not jailbroken, you should download an ipa file and install it via any third party installer (AltStore i.e.)
