### ISSUE TITLE
[Request] Support Multi Add Tracker

### ISSUE THREAD

**Issue by chen-jie** [XITRIX/iTorrent#207]
It would be really helpful if you could Support  Multi Add Tracker list like this [https://github.com/XIU2/TrackersListCollection](https://github.com/XIU2/TrackersListCollection) .
Thanks A lot

**Comment by XITRIX** [comment]
I'm working on another project right now, so no any new features in near future, but when I'll continue iTorrent developing, I think I'll add it.

**Comment by mahee96** [comment]
Ah, man, me too a frustrated user when multi-line-input was not available for adding trackers in bulk. 

But good thing, I have created a pull request #269 for this feature.
Have tested it to be working. Create a latest build from source until next release is available.

Good day.
