### ISSUE TITLE
1.8.4-dev.3 (Still) Leaks My IP Address 

### ISSUE THREAD

**Issue by der1agibert** [XITRIX/iTorrent#208]
I use AirVPN on my iPad Air 4 (iOS 15.0) and double-checked my connection via the torrent address detection on ipleak.net. Unfortunately, iTorrent 1.8.4-dev.3 again somehow gives out my real IP. After intially having started with the latest stable release 1.8.3 displaying the same flaw, the most recent version of iTorrent that worked for me and did not leak was the 1.7.4 (Hotfix) one (much obliged, @ImOldGregg: https://github.com/XITRIX/iTorrent/issues/109#issuecomment-821930026). I simply wanted to give updating another try today but for now it seems I will need to roll back. Any clue what might cause the issue and how it can be fixed? Can I somehow contribute as a complete programming lay-man or provide any more information on the matter?

Nevertheless, thank you so much for this project, @XITRIX! Without it, I would have not been able to fully switch to universal tablet use ditching my traditional MacBook set-up!

**Comment by XITRIX** [comment]
Hi, I think it's impossible to fix without downgrading libtorrent, cause starting from (I forgot the version) it uses all network interfaces, not the primary one, so it tries to connect also bypassing VPN. I'm not actively developing iTorrent right now, so I'm not sure that I'll be able to fix that soon. Anyway thanks for your concern about this problem.

**Comment by U-Gautam** [comment]
hello, has the solution been found for this problem or is this still there. Thanks

**Comment by owaisnaim** [comment]
> hello, has the solution been found for this problem or is this still there. Thanks

It's still present.

**Comment by socksprox** [comment]
How can I see if my ip is leaked or not?

**Comment by XITRIX** [comment]
Should not leak in v2
