### ISSUE TITLE
Hot linking magnet/urls

### ISSUE THREAD

**Issue by rolandz** [XITRIX/iTorrent#21]
Excellent torrent downloader for IOS 9.3.5 and later (ipads etc.)

Just needs direct "Open in" from browser url/magnet links.

TIA..

**Comment by rolandz** [comment]
Heads up. Uninstalled buggy iTransmission (faulty background mode) and "Open in" iTorrent is back. Once again this is the best torrent downloader on IOS yet. You can even watch videos / listen to music in the foreground while its doing its work in the background. One issue though is some torrents fail to start, which are downloading in Tixati Windows.

**Comment by XITRIX** [comment]
Hi, I’m glad you figured out with your problem. 
I know about that some torrents fail to start downloading, but it is the problem of libtorrent I am using in this app, so I’ll try to update it to the latest version in the nearest future, may be this bug will be fixed.
