### ISSUE TITLE
Sequential download as Default 

### ISSUE THREAD

**Issue by UprisingPulse** [XITRIX/iTorrent#210]
Can you make Sequential download as an option for all torrents in settings? it's better than enabling it individually for each torrent because sometimes it skips the first segments since the torrent starts downloading directly.

**Comment by XITRIX** [comment]
Sequential download is pretty harmful for torrent network so does not even presented in some torrent clients like Transmission. I understand why users can need it, so iTorrent provide such option, but I would prefer to avoid adding it as an option for default behaviour
