### ISSUE TITLE
Free storage not true

### ISSUE THREAD

**Issue by LukasMFR** [XITRIX/iTorrent#213]
I don't know if it's a bug or an iOS thing but I have 64.46 GB available on my iPad but iTorrent says that I have 2.68 GB available. I will test to download a file and see if it's just a reading issue.

**Comment by trip2bikram** [comment]
Its same problem on iPhone too. Did you get any fix for it?

**Comment by LukasMFR** [comment]
Well basically even if it tells me that I don't have enough space and tap "Still download" pop up. It will download like normal

**Comment by d-dandrew** [comment]
Always shows 2.68GB free space on my device
I sideloaded iTorrent 1.9 on ios16.5

**Comment by LukasMFR** [comment]
Not sure but maybe that is because iOS reserve some spaces for "temp" kind of files. But like I said I can bypass that by clicking on the popup

**Comment by XITRIX** [comment]
Duplicate of #309
