### ISSUE TITLE
Hey Just something to tell you

### ISSUE THREAD

**Issue by Akczht** [XITRIX/iTorrent#214]
https://developer.apple.com/support/unlisted-app-distribution/

**Comment by XITRIX** [comment]
Hi, thanks, but it's about commercial apps for internal usage, It's not about apps that violates Apple's rules

**Comment by Akczht** [comment]
oh ok

**Comment by Akczht** [comment]
> Hi, thanks, but it's about commercial apps for internal usage, It's not about apps that violates Apple's rules

[Legislation forcing Apple to allow iOS sideloading](https://9to5mac.com/2022/02/03/app-store-open-markets-act-senate-advance/) is this helpful now

**Comment by XITRIX** [comment]
Yea, I've seen it, if Apple will allow sideloading it will be great :)

**Comment by Akczht** [comment]
😎
