### ISSUE TITLE
Unable to install on iOS 15.4 via AppCenter

### ISSUE THREAD

**Issue by Faisalthe01** [XITRIX/iTorrent#216]
I'm trying to install Version 1.8.4-dev.3 (21.0) via AppCenter but keeps getting integrity error. Is there a way i can download the dev ipa file?

**Comment by XITRIX** [comment]
You could install from AppCenter only if your iOS device is jailbroken, otherwise you should download ipa and install it with any third-party ipa installer, like AltStore

**Comment by Faisalthe01** [comment]
> You could install from AppCenter only if your iOS device is jailbroken, otherwise you should download ipa and install it with any third-party ipa installer, like AltStore

Yes that was my original question, where is the latest iOS 15 IPA file?

**Comment by XITRIX** [comment]
Try to set "Desktop mode" in Safari before downloading, it should allow you to download ipa file

**Comment by Faisalthe01** [comment]
@XITRIX thanks but tried that, the desktop version doesn't load maybe i need to use a computer

**Comment by XITRIX** [comment]
Yea... The last time I tried desktop mode, it works, maybe you really need to use pc...

**Comment by Faisalthe01** [comment]
@XITRIX so i tried to download it via PC and then installed it using InstallOnAir but it still gives that integrity error


![CBC3636C-8898-4736-9899-2E84E0E06A77](https://user-images.githubusercontent.com/62862684/152906287-f6b72760-0d65-4ecf-9454-54c8194728fc.jpeg)

**Comment by XITRIX** [comment]
Does InstallOnAir resign app? I don't think so, the same result you'll get trying to install it directly from AppCenter. Try to use AltStore, it resigns an app with your certificates, so you could install and run it
