### ISSUE TITLE
Download speed stuck at 2kb/s

### ISSUE THREAD

**Issue by sofiacif** [XITRIX/iTorrent#217]
I tried to restart my iPad, restart the download and nothing
All the downloads are stuck at this speed, even after trying a VPN

**Comment by LukasMFR** [comment]
Same happens to me, it starts at 35 mbps and then slows down to unusable speed. Maybe it’s ISP throttling

**Comment by theclaw37** [comment]
Same for me. It's definitely not ISP throttling. I'm pulling 400-500Mbps on my mac on wifi through the same connection. Something is wrong with iTorrent.

**Comment by LukasMFR** [comment]
Well sometimes it happens and sometimes it works fine. I reboot the iPad and sometimes it works again.
