### ISSUE TITLE
pod install SwiftyXMLParser [BUG] Bus Error at 0x00000001003e0000   

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [XITRIX/iTorrent#218]
`pod install`

<img width="732" alt="Screenshot 2022-04-03 at 13 03 50" src="https://user-images.githubusercontent.com/3391456/161422308-50a5188a-43be-42d4-b38f-5dd12bffcabf.png">

Just downloaded latest and tried to build. Any solutions?

p.s. for all my iOS developer live 10+ years, I really hate cocoapods..

**Comment by Anywhere-Music-Player** [comment]
Okay, this fixed for some reason and my try's.. 
Next, anyway I can't build this: 

> iTorrent % pod install                            
Analyzing dependencies
Pre-downloading: `SwiftyXMLParser` from `https://github.com/yahoojapan/SwiftyXMLParser.git`
objc[27543]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1da82deb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105fe04f8). One of the two will be used. Which one is undefined.
objc[27543]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1da82df00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105fe0548). One of the two will be used. Which one is undefined.
objc[27543]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1da82df50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105fe0598). One of the two will be used. Which one is undefined.
objc[27543]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1da82dfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105fe05e8). One of the two will be used. Which one is undefined.
objc[27543]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1da82dff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105fe0638). One of the two will be used. Which one is undefined.
objc[27543]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1da82e040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105fe0688). One of the two will be used. Which one is undefined.

**Comment by XITRIX** [comment]
I think you have M1 device, right? Better completely uninstall Cocoapods and reinstall it via Homebrew for arm

**Comment by XITRIX** [comment]
Also you should build Dev branch, I don't think master will compile anyway

**Comment by Anywhere-Music-Player** [comment]
Yes, M1 Pro. I uninstalled all cocoa pods, then launched "brew install cocoapods".
Finally. Thanks!
