### ISSUE TITLE
Лучший торрент

### ISSUE THREAD

**Issue by ZJ-Adram** [XITRIX/iTorrent#22]
Превосходное приложение, наконец-то появился торрент на iOS, помимо устаревшего iTransmision, который уже банально не подходит под размер экрана 6 айфона и дальше. В благодарность даже рекламу не выключаю)

Из основных пожеланий:

1. Добавить ещё недобавленные  функции из iTransmision, чтобы совсем его догнать

2. Последовательная загрузка (как в юторренте)

Кстати, iTorrent  подписали сертификатом и опубликовали в одном телеграмм канале, так что его уже может любой желающий скачать в одно нажатие, а также его на сайте theux собираются выложить, подписав сертификатом действием на целый год.
 
![b053ddaa-4f13-4e39-a12b-edc60ec7d2cc](https://user-images.githubusercontent.com/45251252/51053500-a7574600-15fb-11e9-98bf-7bfca66100f9.png)
![aa27116e-9b40-4631-b870-b14ff5996156](https://user-images.githubusercontent.com/45251252/51053502-a7efdc80-15fb-11e9-83d2-a1d7fb6c9777.png)

**Comment by XITRIX** [comment]
Спасибо большое за отзыв, очень приятно читать такое!)
По поводу функций из iTransmissions, я по большей части именно с него функционал и слизывал, я что то пропустил?
И под последовательной загрузкой подразумевалось скачивание файлов с приоритетом по очереди или скачивание файла от начала к концу, что бы можно было фильмы смотреть во время их загрузки?
За информацию про ресурсы подписавшие моё приложение спасибо, так же знаю что подписанное приложение есть на сайтах appdb.to и на builds.io, возможно мне стоит на них ссылки на главной странице написать

**Comment by ZJ-Adram** [comment]
1. По поводу функций из iTransmision. Если прям по порядку идти, то нельзя копировать данные торрента (кто-то уже писал)
Нельзя получить magnet-ссылку на торрент, отстутствует кнопка приватности (что она вообще делает, у меня в iTransmision она не работает?) ![f52f3217-9d2d-4cc3-b537-b8626a8774bc](https://user-images.githubusercontent.com/45251252/51088291-a6e7b800-177f-11e9-95d3-a4ac8c43f2d6.jpeg)
Нельзя посмотреть расположение файлов в файловой системе (полезно для джейлбрейкнутых) ![32674722-3181-464f-8b9e-64c6ba7b92fb](https://user-images.githubusercontent.com/45251252/51088318-f5955200-177f-11e9-931a-65934c3e5117.jpeg)
И, наконец, отсутвует меню пропускных способностей 
![8f4e722f-bfe2-4b47-a2d1-56b380fdce45](https://user-images.githubusercontent.com/45251252/51088336-30978580-1780-11e9-8186-3b8a4a414878.png)
2. Забыл сообщить, что баг нашёл: при отправке торрента из загрузок firefox в iTorrent, в iTorrent файл не появляется. Не знаю, с чьей это стороны проблема? iTorrent или Firefox. В другие программы из firefox нормально отправляется.
![default](https://user-images.githubusercontent.com/45251252/51088432-6852fd00-1781-11e9-923a-a43d99708e43.gif)
3. И хотел спросить: был назван сайт с приложениями appdb.to. Это точно безопасно, что он хочет мне профиль для контроля над устройством поставить? 
![Uploading 105E7AA9-95EC-4C9F-8A89-1C9C1350A8EA.png…]()

**Comment by XITRIX** [comment]
Magnet-ссылку добавлю
Private я тоже не знаю что делает, так что я не знаю что в него добавлять)
Расположение файлов я даже не могу представить зачем надо смотреть, мне кажется информация практически бесполезная, но занимающая много места, возможно добавлю как опцию в настройках
Ограничение скоростей - это да, надо будет добавить
Про копирование из Firefox не знаю, из Safari, Files, VK и ряда других приложений всегда открывалось без проблем, позже проверю что не так с Firefox 
На счёт appdb не знаю, за безопастность ресурса ручаться не буду, однако знаю что многие требуют установить сертификат, так как именно он позволяет установить приложение подписанное им, но трафик с этого сайта довольно не малый, так что думаю база пользователей у сайта есть и им норм
