### ISSUE TITLE
Unable to install app 1.8.4 ver 3 latest 

### ISSUE THREAD

**Issue by littlejon598** [XITRIX/iTorrent#221]
This is error I get I’m on iOS 15.1
![91099B0D-59C1-42C3-A860-CBF78903F9B2](https://user-images.githubusercontent.com/70407947/173239570-35c38f6c-499b-45a5-b9d5-ef220e5e8bb8.png)

**Comment by bgoncal** [comment]
Same here

**Comment by XITRIX** [comment]
You are not allowed to install app directly if it is not jailbroken, you should download ipa file on your PC and install it with any sideload app (i.e. AltStore)

**Comment by bgoncal** [comment]
Just did that. Thank you
