### ISSUE TITLE
iPad UI cut in half

### ISSUE THREAD

**Issue by miIktoast** [XITRIX/iTorrent#222]
App only displays on half of screen on ipad
![2EB1911C-FF2F-4B25-B5BB-6FCC6164CFEF](https://user-images.githubusercontent.com/76277835/174219136-43ee7cad-1465-4443-a3dd-ae6dd9e28b2f.png)

iPados: 15.5
iTorrent: 1.8.4-dev3
Installed via AltStore

**Comment by XITRIX** [comment]
Are you kidding? It calls split view... Download something and you'll see

**Comment by miIktoast** [comment]
Apologies, I confused your… let’s call it _unique_ design choice as a bug.

**Comment by XITRIX** [comment]
![IMG_3508](https://user-images.githubusercontent.com/9553519/174270467-db2db995-e3a6-4f3c-8bb7-b90851b5b642.PNG)

I've added app's icon to make it less confusing

**Comment by miIktoast** [comment]
My suggestion: make the left section fullscreen and have the torrent data slide into the space it currently occupies when selecting a download. 

That way the UI looks friendlier, removes the need for the scrolling tabs, files with long names would be easier to read and you could fit more metadata underneath the file name.

**Comment by XITRIX** [comment]
Do you mean that I should get rid of SplitScreen? I'm not sure that it's good idea, I think it's possible to add as an option in settings but not as default... I'm making decisions based on fact that almost every iPad app uses split screen and also it looks ugly to me when iPad's large screen shows only one view.
