### ISSUE TITLE
Can not build an application because import DeepDiff no such module. 

### ISSUE THREAD

**Issue by piroh-a** [XITRIX/iTorrent#227]
How to fix it?

**Comment by XITRIX** [comment]
1. Use ["Dev" branch](https://github.com/XITRIX/iTorrent/tree/Dev)
2. `pod install`
3. Open iTorrent.xcworkspace and try to build

**Comment by piroh-a** [comment]
Sir, may I ask you to provide little bit more details. I’m new here. Where I can find dev branch? Right into the Xcode? Or download latest version from web site? But I can’t.

**Comment by piroh-a** [comment]
<img width="1105" alt="Screenshot at Oct 24 19-10-42" src="https://user-images.githubusercontent.com/77136661/197646989-c306ad25-ce58-4971-9471-8e630f0cddd9.png">

**Comment by XITRIX** [comment]
Dev - is a git branch, better read about git basics, for now just type this into your terminal: 
`git clone -b Dev https://github.com/XITRIX/iTorrent.git --recursive`

open downloaded folder in terminal via 
`cd path/to/folder/iTorrent`

install CocoaPods - just Google it, and run
`pod install`

after that you could open iTorrent.xcworkspace file, open project's tab in project navigator, select Signs and Capabilities tab, change Team and Bundle identifier to your own, and try to run the project

**Comment by piroh-a** [comment]
Dear Daniil, thank you so much for your work and responding to me. For now, I am able to install the application onto my phone, but I can't run it. It is crashed just when I try to launch it.  Can you tell me please what I do wrong? I have IOS 16.1 Thank you so much!

**Comment by XITRIX** [comment]
Show me the crash report, I'm not an extrasensory :)

**Comment by piroh-a** [comment]
Alright I found the solution. It's was pretty much simple just follow the instructions:)

**Comment by XITRIX** [comment]
So I'll close that issue, if you'll have more questions feel free to reopen it.
