### ISSUE TITLE
paypal you money

### ISSUE THREAD

**Issue by venberk** [XITRIX/iTorrent#230]
привет. хотел задонатить через пейпол - написано не принимает платежи. как можно денег заслать

**Comment by XITRIX** [comment]
Спасибо за поддержку, если PayPal не работает, можно просто карточным переводом 
2200 7001 4500 0039

**Comment by venberk** [comment]
отправил20 нояб. 2022 г., в 19:06, Vinogradov Daniil ***@***.***> написал(а):﻿
Спасибо за поддержку, если PayPal не работает, можно просто карточным переводом
2200 7001 4500 0039

**Comment by venberk** [comment]
можт дошли уже. классный проектя поставил через альтстор. но такой вариант мне не оч нрааится. есть ли альтернативный вариант поставить?может надо купить какую то лицензию apple developer и тд. но далек от этого. сам принцип не понятен как это все ставится. если есть вариант без альтстора или сторонних аналогичных сервисов - я бы сделал. может самому скомпилировать и поставить с каким то своим сертификатом. без джейла. в appstore твое приложение есть вариант что пустят или нет?20 нояб. 2022 г., в 19:06, Vinogradov Daniil ***@***.***> написал(а):﻿
Спасибо за поддержку, если PayPal не работает, можно просто карточным переводом
2200 7001 4500 0039

**Comment by XITRIX** [comment]
Да, дошли, спасибо большое!

Что бы не пользоваться AltStore есть вариант купить аккаунт разработчика за 100$ в год и установить приложение через xCode, тогда будет работать год без каких либо ограничений

UP.
Хотя можно и без xCode обойтись, через Sideloadly например установить, принцип похож на AltStore, только с аккаунтом разработчика приложение поставится на долго
