### ISSUE TITLE
Add Support to Open magnet/torrent links/files

### ISSUE THREAD

**Issue by theMaddis** [XITRIX/iTorrent#233]
Please add support for the url scheme so I don’t have to copy each torrent/magnet url and paste it into iTorrent every time I want to download something

regex should be: /magnet:\?xt=urn:[a-z0-9]+:[a-z0-9]{32}/i

**Comment by XITRIX** [comment]
But iTorrent supports magnet link redirection from safari and opening torrent files via sharing menu...

https://user-images.githubusercontent.com/9553519/207848995-6c62c4bc-d7a2-4ac4-add4-4d774f28fa77.MP4
