### ISSUE TITLE
Update Application to a newer version that supports iOS 16

### ISSUE THREAD

**Issue by yeet227** [XITRIX/iTorrent#236]
![image](https://user-images.githubusercontent.com/51895536/209802925-1a42b1cc-494c-4937-ac6e-fcb668e2e8b3.jpeg)

**Comment by yeet227** [comment]
I tried updating it and it stayed that it was to the newest version

**Comment by XITRIX** [comment]
I forgot to build it in AppCenter, check it now

**Comment by yeet227** [comment]
What do you mean by app centre as in within the app?

**Comment by XITRIX** [comment]
[Here](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public)

**Comment by yeet227** [comment]
Ah ok thanks

**Comment by yeet227** [comment]
Would you be able to update the GitHub version?

**Comment by XITRIX** [comment]
It's not ready yet, I've messed up with versions, so it show that "new version available"

**Comment by yeet227** [comment]
Ah ok thanks I'll mark this as complete
