### ISSUE TITLE
add ar language  

### ISSUE THREAD

**Issue by x7mi** [XITRIX/iTorrent#240]
add AR translation for  the application  

[ar.lproj.zip](https://github.com/XITRIX/iTorrent/files/10551559/ar.lproj.zip)

**Comment by x7mi** [comment]
update and fix some errors
[ar.lproj.zip](https://github.com/XITRIX/iTorrent/files/10551873/ar.lproj.zip)

**Comment by XITRIX** [comment]
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/b8b03666-dda4-4013-ba95-b79cb1042f78">
Both files corrupted and cannot be used
