### ISSUE TITLE
how about making a build for macos?

### ISSUE THREAD

**Issue by blahdy** [XITRIX/iTorrent#244]
mac lacks a proper native bt client based on libtorrent.

the closest to a native expirience is our modded build of [qBittorrent](https://github.com/vit9696/qBittorrent), wich is based on bogus qt

would be really nice if you made a mac client

спасибо =0)

**Comment by egigoka** [comment]
Why do you need this? qBittorrent works fine on macOS. It's additional overhead for development without any measurable profits.

**Comment by Lorokos** [comment]
there is iTransmission, which has the cleanest native look for a torrent client that I've seen:

https://transmissionbt.com/

**Comment by Hoe2020** [comment]
Sideloadly allows you to sideload this on to a mac.

**Comment by blahdy** [comment]
> there is iTransmission, which has the cleanest native look for a torrent client that I've seen:
> 
> 
> 
> https://transmissionbt.com/

libransmission is very slow compared to libtorrent

**Comment by blahdy** [comment]
> Sideloadly allows you to sideload this on to a mac.

Not for x86

**Comment by XITRIX** [comment]
You can use qBitTorrent, I’m using this torrent on my Mac and also as a reference for several features in iTorrent

**Comment by blahdy** [comment]
> You can use qBitTorrent, I’m using this torrent on my Mac and also as a reference for several features in iTorrent 

Yes, we've even made a fork of it with vit9696 so that it is not so eyebleeding, but it suffers greatly from qt and being multiplatform. 

Hence the initial query about making your fine app native for mac.

**Comment by XITRIX** [comment]
If you'll see how iTorrent looks like on Mac, you'll need an eyes surgery :D
Touch screen UI looks not the best way on desktops, but if you REALLY want to see this, here you go:
[iTorrent-Mac.zip](https://github.com/user-attachments/files/16502845/iTorrent.zip)
It's compiled in "Designed for iPad" mode and as you understand, it was not optimised at all

Btw, my proficiency is mobile (iOS) development, I never developed apps for desktops (Macs) and I have no idea about good and bad practices in UI/UX in that part
