### ISSUE TITLE
Create a repository for RSS messages related to torrents

### ISSUE THREAD

**Issue by yeet227** [XITRIX/iTorrent#247]
Exactly as the title says as well being able to add your own

**Comment by yeet227** [comment]
As well as bug fixes for adding torrents and the app crashing and forgetting that the magnet link was added

**Comment by XITRIX** [comment]
I am not an active user of RSS so I'm not understand what you'd like to see, could you add some examples from other torrent clients as reference for future work?

Also I cannot fix crash if I cannot reproduce it, do you have specific torrent file which crashes the app? If so, could you attach it so I could reproduce and fix it?
