### ISSUE TITLE
Removing firebase analytics?

### ISSUE THREAD

**Issue by GucciGazm** [XITRIX/iTorrent#25]
Is there anyway to remove firebase? Or could I get a ipa file that doesn’t have this included?

**Comment by XITRIX** [comment]
Why would you like to remove it? It helps me to collect a debug information from all over the world and see how popular my app is. From the other side I cannot see any flaws from the user side, so I cannot understand why you asked me about it

**Comment by GucciGazm** [comment]
I’m just not a fan of firebase, don’t get me wrong I know why it’s used I just don’t like the info they collect. But again it’s your project and your decision. I was just wondering if I could get a custom build without firebase. If not I guess I could make a fork possibly without it but I’m new to all this. Thanks for the response

**Comment by XITRIX** [comment]
Please, no fork, if you will create a version without firebase, PLASE, use it ONLY for personal use. It will be a real trouble for me if it will be used by large number of people. So thanks for understanding!
