### ISSUE TITLE
Support for older IOS versions like 8.4.1 ?

### ISSUE THREAD

**Issue by pixel-hopper** [XITRIX/iTorrent#252]
Any version for older IOS like 8.4.1 and are there any plans to support older IOS by any chance ?
Great work !

**Comment by XITRIX** [comment]
iTorrent's minimum version will move to 11.0 cause latest xCode dropped the support of 9.0 and 10.0.

iTorrent uses latest features of xCode and iOS so unfortunately it will never move it's minimum supported version down, only up.

I will close this issue, cause it is impossible to implement in any way.

**Comment by monomycelium** [comment]
Which is the latest version of iTorrent supported by iOS 9.3.5?

**Comment by XITRIX** [comment]
Probably somewhere before [this commit](https://github.com/XITRIX/iTorrent/commit/54482e6737f510e88cb26c8ccd667371d2bf60ea)
