### ISSUE TITLE
Newer build

### ISSUE THREAD

**Issue by faycaltami0916** [XITRIX/iTorrent#253]
The newer app build won’t let me download on my iPad air 4 
It won’t connect to peers, and even if it did manage to connect it downloads like 5mb and restart the issue all over again but the actual files are 0kb
I tried the previous version and it worked just fine the issue is just on the newer build.
And can you explain why the app size is significantly higher now ?
Thank you

**Comment by XITRIX** [comment]
Nice question about size, I didn't notice when it happened. About downloading it sounds strange to me, like it is unable to write files or you're out of free space on device. I have iOS 16.6 and download works fine

**Comment by XITRIX** [comment]
Compared latest ipa with old one, looks like iTorrentFramework started to weight much more, probably because of migrating on 2.0 version of libtorrent

**Comment by XITRIX** [comment]
Also looks like xCode 14 started to use heavier binaries for latest Swift versions and other libs

<img width="520" alt="image" src="https://github.com/XITRIX/iTorrent/assets/9553519/98fe33b3-ffc4-4ec4-a970-d2b267cb20f3">
<img width="524" alt="image" src="https://github.com/XITRIX/iTorrent/assets/9553519/f1e5ebba-8e78-4885-89e2-b9d92e088446">

**Comment by faycaltami0916** [comment]
No I don’t think that free space is an issue there, there’s plenty of free space, yet I tried downloading a small file and it did download no problem but with heavier files let’s say 5~6gb it doesn’t connect to peers no matter how much time I give it and when I got the app storage in settings the file is there but it’s empty.
Bear with me that this is no issue on the previous build of 1.9 it was released on February something and I am on ios 16.5.

**Comment by faycaltami0916** [comment]
Fixed with the newer build.
