### ISSUE TITLE
САЛЮТ! ЭТО ВАЖНО!

### ISSUE THREAD

**Issue by Yapidor666** [XITRIX/iTorrent#256]
Здарова! А когда добавишь принудительное шифрование?

**Comment by XITRIX** [comment]
Что это? Покажи настройку на примере qBitTorrent и возможно добавлю

UP.
Думаю нашёл, попробую добавить тогда

**Comment by Yapidor666** [comment]
https://utorrent-client.com/instructions/chto-takoe-shifrovanie-protokola-v-utorrent-i-kak-ego-vklyuchit.html

Был бы збс, если добавишь. А то опсосы постоянно шейпят скорость, уже зае... (((. Спс большое заранее ))). И когда примерно ждать апдейт? Чтобы постоянно не чекать.

**Comment by XITRIX** [comment]
По поводу сроков к сожалению ничего сказать не могу, этом проектом занимаюсь исключительно в свободное время, а его у меня сейчас не много

**Comment by Yapidor666** [comment]
> 

Понял тебя. Ну, буду ждать тогда... Если не трудно, можешь маякнуть, когда будет готово?

**Comment by XITRIX** [comment]
Да, хорошо

**Comment by Yapidor666** [comment]
> Да, хорошо

От души, чел ). Если быстро сделаешь, закину бабок )

**Comment by Yapidor666** [comment]
> Да, хорошо

А можно вопрос? Ты сам какую версию юзаешь и какую рекомендуешь? Ласт самая лучшая, как понимаю?

**Comment by XITRIX** [comment]
Я сам использую самую последнюю конечно же, так как постоянно что то чиню и исправляю, как в UI так и в работе самой прилы

В последних патчах добавил прогресс разгрузки на локскрине, что как мне кажется довольно удобно

Но тут надо сделать ещё акцент на то, что как бы парадоксально это ни звучало, сам я не особо хардкорный юзер торрентов и для меня все эти типы шифрования немного чужды, так что если нужен какой то более продвинутый функционал, то лучше сразу рассказывать, где я могу его подсмотреть

**Comment by Yapidor666** [comment]
> Я сам использую самую последнюю конечно же, так как постоянно что то чиню и исправляю, как в UI так и в работе самой прилы
> 
> В последних патчах добавил прогресс разгрузки на локскрине, что как мне кажется довольно удобно
> 
> Но тут надо сделать ещё акцент на то, что как бы парадоксально это ни звучало, сам я не особо хардкорный юзер торрентов и для меня все эти типы шифрования немного чужды, так что если нужен какой то более продвинутый функционал, то лучше сразу рассказывать, где я могу его подсмотреть




А что за прогресс? Можно подробней, а то не понял. Ну, ясн ). Ну, явно в своё время много качал, раз придумал такую прилу ). Кста, у меня ощущение что ласт билд будто хуже качает, ну мб просто кажется. Какой-то чел на 4пда писал что юзает 1.7.4, пот что там типа не палит ип или что-то такое.

**Comment by XITRIX** [comment]
![IMG_5548](https://github.com/XITRIX/iTorrent/assets/9553519/7f7f5721-5399-4c07-97fc-dfb31909af0b)
Вот такой прогресс

А по поводу IP, у последних версий libtorrent есть такой прикол, что он использует все доступные сетевые порты, а не только тот который даёт операционка, по этому он может и в сотовую связь залезть даже если wifi подключен, и мимо VPN подключиться, но именно проблем с загрузкой я не наблюдал никогда, скорее наоборот работает стабильнее чем раньше, по крайней мере у меня

**Comment by Yapidor666** [comment]
> ![IMG_5548](https://user-images.githubusercontent.com/9553519/251976089-7f7f5721-5399-4c07-97fc-dfb31909af0b.jpeg) Вот такой прогресс
> 
> А по поводу IP, у последних версий libtorrent есть такой прикол, что он использует все доступные сетевые порты, а не только тот который даёт операционка, по этому он может и в сотовую связь залезть даже если wifi подключен, и мимо VPN подключиться, но именно проблем с загрузкой я не наблюдал никогда, скорее наоборот работает стабильнее чем раньше, по крайней мере у меня

У меня такого нет... А как так сделать? Или автоматом должно? Ну, ясн. Хочу почекать олд версии, мб получше будет, как знать, просто интересно стало.
Как тебе Адский рай, кста? ). Жду 2-ой, хз, сколько ждать вапще (((

**Comment by XITRIX** [comment]
Ахах, мне понравился, с удовольствием посмотрел бы проду

А прогресс доступен в версиях с AppCenter'a если поменять режим фоновой загрузки с Аудио на Геолокацию (а сейчас я это написал и не помню, а выложил ли я вообще эти изменения)

**Comment by Yapidor666** [comment]
> Ахах, мне понравился, с удовольствием посмотрел бы проду
> 
> А прогресс доступен в версиях с AppCenter'a если поменять режим фоновой загрузки с Аудио на Геолокацию (а сейчас я это написал и не помню, а выложил ли я вообще эти изменения)

Ага, думаю, будет ещё пизже ).
Явно нет, у меня нет такого.
![98E1B6D9-B931-41EA-B19D-55ECA55C0803](https://github.com/XITRIX/iTorrent/assets/138986783/eee00e55-d8a4-49d1-b698-ae798d823213)

**Comment by XITRIX** [comment]
уфф.. это 1.8.3?

Она пипец старая, посмотри более актуальные версии тут

https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public

Надо бы мне уже обновить сборку в релизах гитхаба...

**Comment by Yapidor666** [comment]
> уфф.. это 1.8.3?
> 
> Она пипец старая, посмотри более актуальные версии тут
> 
> https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public
> 
> Надо бы мне уже обновить сборку в релизах гитхаба...

Обижаешь ). 1.9, кнш. Закладос уже давно есть, спс.

**Comment by Yapidor666** [comment]
> уфф.. это 1.8.3?
> 
> Она пипец старая, посмотри более актуальные версии тут
> 
> https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public
> 
> Надо бы мне уже обновить сборку в релизах гитхаба...

Как тебе мой кастомайз? )

**Comment by Yapidor666** [comment]
> уфф.. это 1.8.3?
> 
> Она пипец старая, посмотри более актуальные версии тут
> 
> https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public
> 
> Надо бы мне уже обновить сборку в релизах гитхаба...

Зацени )
![71C32CCE-732E-472A-BEB2-4D1F6208B6F2](https://github.com/XITRIX/iTorrent/assets/138986783/0379830d-82c1-47ef-80e4-add6c2d93a79)
![1BFCFFF5-E825-481E-880A-940913ED4ECE](https://github.com/XITRIX/iTorrent/assets/138986783/e62ba792-0c5e-4a87-a41e-fedf8f4099a2)
![B0457958-776D-4ABD-9247-C2A5E6C8425B](https://github.com/XITRIX/iTorrent/assets/138986783/c5ff2c6c-28dd-4fc8-b6d6-f400fb7706fb)
![8CBC19FC-50F5-4BC8-BC25-D8C8CF06E789](https://github.com/XITRIX/iTorrent/assets/138986783/67063251-3e28-4876-8adb-d04de4539c4f)

**Comment by XITRIX** [comment]
Если честно, я не фанат такого )

Люблю натив и эпловые UI гайдлайны, а за самодеятельность я на работе коллегам обычно по рукам бью :D

А это какая версия iOS? Их же уже вроде как давно не ломали

**Comment by Yapidor666** [comment]
> Если честно, я не фанат такого )
> 
> Люблю натив и эпловые UI гайдлайны, а за самодеятельность я на работе коллегам обычно по рукам бью :D
> 
> А это какая версия iOS? Их же уже вроде как давно не ломали

Такой расцветки или кастома? ).
Какую именно?
14.3. 11 промах на 512, 2 физ сим ). Достался по большому фарту, просто оч лаки, ещё и дёшево ). Да, выше 14.8 (и то, не все девайсы, и только ковёр) нет норм джейла. На 15-15.4.1 есть Допамин, он на А12-А15, но он рутлесс, без фулл рут доступа, то есть кастрированный, для меня это детская хуйня. Но уже достаточно много твиков вышло на рутлесс, это радует. А бряком занимаюсь с 2013, ещё с 7-ой оси, где был непривяз. Сам-то давно джейлил и как к нему относишься?

**Comment by XITRIX** [comment]
Во времена iPhone 3GS всё что можно было джейлил :)

Последнее что рутовал это iPad Pro последный до редизайна который был, и iPhone 8P с iCloud локом, принесли его мне, походу краденый был, но вернуть хозяину никак не было возможности ибо принесли из аэропорта, а бывший владелец - Китаец (система на китайском была) явно уже улетел к себе.

Сейчас уже не особо в этом смысл вижу ибо почти всё что мне надо и так есть, а чего нет, либо сам сделаю либо обходными путями добьюсь

**Comment by Yapidor666** [comment]
> Во времена iPhone 3GS всё что можно было джейлил :)
> 
> Последнее что рутовал это iPad Pro последный до редизайна который был, и iPhone 8P с iCloud локом, принесли его мне, походу краденый был, но вернуть хозяину никак не было возможности ибо принесли из аэропорта, а бывший владелец - Китаец (система на китайском была) явно уже улетел к себе.
> 
> Сейчас уже не особо в этом смысл вижу ибо почти всё что мне надо и так есть, а чего нет, либо сам сделаю либо обходными путями добьюсь

Пон )
5s, потом 8+, долго с ним гонял, и вот недавно 11.  Для меня это в 1-ую очередь полная свобода, а главное это кастомайз, ибо я перфекционист и эстет. Кста, есть идиоты, которые считают что джейл нужен / юзается только для байпасса ). Всегда ору с таких ). Ну, согл, что сейчас гораздо меньше необходимость, но я джейлер до мозга костей и не терплю никаких ограничений, поэтому гейфон без джейла мне даже даром не нужен, для меня это просто звонилка. Пока есть тела на олдовых осях и жив бряк, буду юзать гейос. Уже оч привык за столько лет, ведроид никогда по серьёзке не юзал, не ходил с ним. Но рано или поздно настанет этот час и придётся ( или уже сам захочу) юзать ведро, хоть и вапще не нравится эта багофризная хуйня. Никогда не смогу смириться с драконовскими ограничениями огрызка, для меня это как тюрьма, мне некомфортно. Оч печально что джейл понемногу уже умирает...

**Comment by Yapidor666** [comment]
> Во времена iPhone 3GS всё что можно было джейлил :)
> 
> Последнее что рутовал это iPad Pro последный до редизайна который был, и iPhone 8P с iCloud локом, принесли его мне, походу краденый был, но вернуть хозяину никак не было возможности ибо принесли из аэропорта, а бывший владелец - Китаец (система на китайском была) явно уже улетел к себе.
> 
> Сейчас уже не особо в этом смысл вижу ибо почти всё что мне надо и так есть, а чего нет, либо сам сделаю либо обходными путями добьюсь

Дружище, соре, если уже заебал. Но. 1.9.3 шейпит инет, скорость стремительно падает и всё, вапще не поднимается или еле качает, а на 1.8.3 всё заебись. Как так? Раньше траблов никаких не было. Чекал несколько раз, сносил и тестил. Если не веришь, могу пруфануть.

**Comment by XITRIX** [comment]
Блин, многие про это пишут но сам на это не напарывался, вообще без понятия почему такое может быть

Мб реально что то не так с последними версиями libtorrent, попробую на самую последнюю обновить, может поможет

**Comment by Yapidor666** [comment]
> 

Значит всё-таки не у меня одного, это радует. А то уж подумал что мой опсос совсем охуел и больше не даст норм качать )
А есть ещё новей? Ну, попробуй.

**Comment by XITRIX** [comment]
2.0.8 сейчас, есть 2.0.9

**Comment by XITRIX** [comment]
А ещё у меня для тебя хорошие новости
![IMG_5550](https://github.com/XITRIX/iTorrent/assets/9553519/74445eb4-bb5f-4801-892f-155793f0d4ea)

**Comment by Yapidor666** [comment]
> А ещё у меня для тебя хорошие новости
> ![IMG_5550](https://user-images.githubusercontent.com/9553519/252057433-74445eb4-bb5f-4801-892f-155793f0d4ea.PNG)

Ух, бля ))). Сразу 2 охуенных новости ))). Чел, ты лучший ). Когда релиз?

**Comment by Yapidor666** [comment]
> 2.0.8 сейчас, есть 2.0.9

Лол, он вышел 22-ого мая, а ты релизнул 20-ого ). Эх, а так бы уже был с новым...

**Comment by XITRIX** [comment]
> > А ещё у меня для тебя хорошие новости
> > ![IMG_5550](https://user-images.githubusercontent.com/9553519/252057433-74445eb4-bb5f-4801-892f-155793f0d4ea.PNG)
> 
> Ух, бля ))). Сразу 2 охуенных новости ))). Чел, ты лучший ). Когда релиз?

Дай мне часик шлефануть переводы и отправлю на сборку в AppCenter

**Comment by Yapidor666** [comment]
> > > А ещё у меня для тебя хорошие новости
> > > ![IMG_5550](https://user-images.githubusercontent.com/9553519/252057433-74445eb4-bb5f-4801-892f-155793f0d4ea.PNG)
> > 
> > 
> > Ух, бля ))). Сразу 2 охуенных новости ))). Чел, ты лучший ). Когда релиз?
> 
> Дай мне часик шлефануть переводы и отправлю на сборку в AppCenter

Заебись ). К к, жду.

**Comment by XITRIX** [comment]
Готово, можешь идти проверять

**Comment by Yapidor666** [comment]
> Готово, можешь идти проверять

Видал, спс. Щас чекаю. А поч фоновый режим юзает гешку? Так и не понял. И явно нормас жрать будет.

**Comment by Yapidor666** [comment]
> Готово, можешь идти проверять

Бля, что за хуйня... Скорость высоко не поднимается, чо только не делал. А если даже поднялась, а это 2-3 мбайт, макс 3, то оч быстро падает. Несколько раз до 5-8 поднималась и резко вниз... Как думаешь, из-за чего может быть? Уже всю голову сломал, так и не понял.

**Comment by XITRIX** [comment]
у меня такое было в последний раз очень давно если честно, так что я вообще без понятия...

**Comment by Yapidor666** [comment]
> Готово, можешь идти проверять


Тест инета, чтобы не думал что он хуёвый. Видос из торра не заливает, ска, видимо, вес большой или хз, заебался резать, уже даже 15 сек не пускает (((. Могу дропнуть в тг, если не против. Просто заценить, какой там пиздец.

https://github.com/XITRIX/iTorrent/assets/138986783/2ae6b6b9-d563-41b7-90a0-e55a2121526f

**Comment by XITRIX** [comment]
![IMG_5559](https://github.com/XITRIX/iTorrent/assets/9553519/ab7725d0-d941-4431-bfc4-ee8e915e7408)

Только что для теста скачал что то на рандом

**Comment by XITRIX** [comment]
Да я в целом понимаю о чём ты говоришь, попробуй грохнуть прилу и запустить заново когда начнётся просадка, раньше мне это помогало

**Comment by Yapidor666** [comment]
> ![IMG_5559](https://user-images.githubusercontent.com/9553519/252105566-ab7725d0-d941-4431-bfc4-ee8e915e7408.PNG)
> 
> Только что для теста скачал что то на рандом

Хм, странно... Я-то по сети, хотя роли не должно играть. Инет до 200 разгоняется спокойно, впн быстрый, всегда с него качал. То есть, дело точно не в инете и впн. Тогда я хуй знает даже...

**Comment by Yapidor666** [comment]
> Да я в целом понимаю о чём ты говоришь, попробуй грохнуть прилу и запустить заново когда начнётся просадка, раньше мне это помогало

Это не ворк. Точнее, на несколько сек иногда помогает. Хуйня в резкой просадке скорости, она тупо постоянно падает и ничо не помогает (((. Макс 3,5-4 поднимается и так может ещё кое-как держаться, и то, постоянно скачет до 1,5-2.

**Comment by Yapidor666** [comment]
12 сек залилолось, а 15 не хочет. Чо за херня. Неужели надо ещё меньше. Или как сюда дропать эти долбанные видосы?

**Comment by Yapidor666** [comment]
https://github.com/XITRIX/iTorrent/assets/138986783/16719639-e8a6-4cdf-a45e-d098d0a9eaee

**Comment by Yapidor666** [comment]
Лол, 4 мб ограничение, походу... Ну нахрен...

**Comment by XITRIX** [comment]
4мб у впн? или у торента?

**Comment by Yapidor666** [comment]
> 4мб у впн? или у торента?

У файла. 12 сек теста скорости залился, а из торра 15 не хотел, резал до 12, тоже никак, 9 прокатило, но 2-ой раз уже нет. Хотел показать, как быстро падает скорость при любом раскладе,
А у торрента тоже около 4 мбайт потолок. Тупо не идёт выше. Это при том что раньше по 10-15 спокойно, до 28-30 даже часто было, инет позволяет. Щас буду чекать опять 1.8.3, потом ниже, если что.

**Comment by Yapidor666** [comment]
> 4мб у впн? или у торента?

1.8.4 дев 3 от 22 июл полёт заебись, как ни странно... Как так? Лёгкие просады есть, но это классика, но скорость держит уверенно уже мин 10, если не больше.

**Comment by XITRIX** [comment]
возможно реально в libtorrent 2.0. проблема, попробую откатить обратно на 1.2.х позже

**Comment by Yapidor666** [comment]
> возможно реально в libtorrent 2.0. проблема, попробую откатить обратно на 1.2.х позже

Хз, походу. На 1.8.4 как раз 1.2.х? Тогда попробуй. Ну или ниже 2.0.8.

**Comment by Yapidor666** [comment]
> возможно реально в libtorrent 2.0. проблема, попробую откатить обратно на 1.2.х позже


Мб тупой вопрос, но всё же. А PEX (Peer exchange) ведь есть?
И ещё. Можешь это добавить, если не трудно? Мб поможет.
![DB6F628A-3C14-4625-B9B1-E4A4F61918F7](https://github.com/XITRIX/iTorrent/assets/138986783/86649340-3ce1-4b1a-b3d6-9603a13d3feb)

**Comment by XITRIX** [comment]
Ха, а PeX'a то нет

**Comment by Yapidor666** [comment]
> Ха, а PeX'a то нет

Лол, а это прикол...
И он уже давно есть, кста.
![A5AF8F05-3237-4846-9F70-B8B90CFFE425](https://github.com/XITRIX/iTorrent/assets/138986783/99f3199a-7471-496a-b79d-1fc5be545953)
![4C4F9B0B-1448-48E8-A7EE-C03E16CF0194](https://github.com/XITRIX/iTorrent/assets/138986783/d6166909-01ac-4059-b9de-f415990692ba)

**Comment by XITRIX** [comment]
ну это я забыл его включить, тоже добавлю

**Comment by Yapidor666** [comment]
> ну это я забыл его включить, тоже добавлю

Спс.
Кста, уже норм вроде качает, или уже кажется, хз. Я к тому что мб нет смысла катить либ до олда.

UPD: 1.8.4 намного лучше качает всё же. Мб чекнуть 2.0.7, наеример?

**Comment by XITRIX** [comment]
[build.zip](https://github.com/XITRIX/iTorrent/files/12040825/build.zip)
Попробуй
![IMG_5670](https://github.com/XITRIX/iTorrent/assets/9553519/d24e20c9-0ac9-4919-aba5-28bed178dc11)

**Comment by Yapidor666** [comment]
> [build.zip](https://github.com/XITRIX/iTorrent/files/12040825/build.zip)
> Попробуй
> ![IMG_5670](https://user-images.githubusercontent.com/9553519/253320843-d24e20c9-0ac9-4919-aba5-28bed178dc11.jpg)

Ворк файн ). Есть 2.0.7? Надо бы прочекать самый стэйбл.

**Comment by Yapidor666** [comment]
> [build.zip](https://github.com/XITRIX/iTorrent/files/12040825/build.zip)
> Попробуй
> ![IMG_5670](https://user-images.githubusercontent.com/9553519/253320843-d24e20c9-0ac9-4919-aba5-28bed178dc11.jpg)

У тебя-то есть разница? Сравнивал?

**Comment by XITRIX** [comment]
не проверял, да и у меня и раньше нормально качало

а так я только сделать успел и залить, больше ничего не делал

все версии 2.0.х - фиксы после перехода, так что не думаю что будет хоть одна которая работает лучше чем последняя

даже qBitTorrent имеет 2 версии. на 1.2 и на 2.0

Кстати PeX всё таки был, если его не трогать он по дефолту включен

**Comment by Yapidor666** [comment]
> не проверял, да и у меня и раньше нормально качало
> 
> а так я только сделать успел и залить, больше ничего не делал
> 
> все версии 2.0.х - фиксы после перехода, так что не думаю что будет хоть одна которая работает лучше чем последняя
> 
> даже qBitTorrent имеет 2 версии. на 1.2 и на 2.0
> 
> Кстати PeX всё таки был, если его не трогать он по дефолту включен

Ну, ясн.
А где он? Мб кто-то бы захотел выкл, например.

**Comment by XITRIX** [comment]
ну вот выключить его и нельзя, позже мб добавлю

**Comment by Yapidor666** [comment]
> ну вот выключить его и нельзя, позже мб добавлю

Пон.
А что насчёт кол-ва соединений?

**Comment by Yapidor666** [comment]
> > Ха, а PeX'a то нет
> 
> Лол, а это прикол... И он уже давно есть, кста. ![A5AF8F05-3237-4846-9F70-B8B90CFFE425](https://user-images.githubusercontent.com/138986783/252288254-99f3199a-7471-496a-b79d-1fc5be545953.jpeg) ![4C4F9B0B-1448-48E8-A7EE-C03E16CF0194](https://user-images.githubusercontent.com/138986783/252288273-d6166909-01ac-4059-b9de-f415990692ba.jpeg)

Это.

**Comment by Yapidor666** [comment]
> > возможно реально в libtorrent 2.0. проблема, попробую откатить обратно на 1.2.х позже
> 
> Мб тупой вопрос, но всё же. А PEX (Peer exchange) ведь есть? И ещё. Можешь это добавить, если не трудно? Мб поможет. ![DB6F628A-3C14-4625-B9B1-E4A4F61918F7](https://user-images.githubusercontent.com/138986783/252147720-86649340-3ce1-4b1a-b3d6-9603a13d3feb.jpeg)

Это.

**Comment by XITRIX** [comment]
Пока не трогал, но лучше бы ты присылал скрины из qbittorrent, так как он использует ту же либу что и я

**Comment by Yapidor666** [comment]
> Пока не трогал, но лучше бы ты присылал скрины из qbittorrent, так как он использует ту же либу что и я

К, сейчас найду.

**Comment by Yapidor666** [comment]
> > Пока не трогал, но лучше бы ты присылал скрины из qbittorrent, так как он использует ту же либу что и я
> 
> К, сейчас найду.
![98D3F571-2820-4202-BF29-DA03B1F0991F](https://github.com/XITRIX/iTorrent/assets/138986783/92d4faae-30e4-470c-9c91-eeb5ba67e3d0)
![6FDB1728-C82B-4E57-8C82-635E8A5BCBC0](https://github.com/XITRIX/iTorrent/assets/138986783/eff8a26a-cb33-4d11-8c3a-c5f3f1fed253)

**Comment by Yapidor666** [comment]
> Пока не трогал, но лучше бы ты присылал скрины из qbittorrent, так как он использует ту же либу что и я

Салют. Соре, если уже заебал ))).
Добавишь, если не трудно? Спс заранее! А ещё можешь убрать лимит на даунлоуд 10? Можешь просто увеличить, если никак не убрать.
![1315E583-99D2-4250-8EBC-B2029C2BC9E4](https://github.com/XITRIX/iTorrent/assets/138986783/6b46f11f-2965-46fd-90ed-5d0ca9a582f3)

**Comment by XITRIX** [comment]
Найдёшь такую настройку у qBitTorrent, тогда возможно и добавлю)
А лимит в 10 ок, посмотрю что можно сделать

**Comment by Yapidor666** [comment]
> Найдёшь такую настройку у qBitTorrent, тогда возможно и добавлю)
> А лимит в 10 ок, посмотрю что можно сделать

В нём как раз нету. В transmission есть.
К, спс. Ещё бы побольше шифрования, опсос как-то палит даундоуд.

**Comment by Yapidor666** [comment]
> Найдёшь такую настройку у qBitTorrent, тогда возможно и добавлю)
> А лимит в 10 ок, посмотрю что можно сделать

Вот это.
https://github.com/XITRIX/iTorrent/issues/256#issuecomment-1634771631

**Comment by XITRIX** [comment]
> В нём как раз нету. В transmission есть.

Transmission и qBitTorrent используют разные движки, у меня тот, что в qBitTorrent (libtorrent), по этому и прошу на него референсы делать, так как я могу просто открыть его исходники и спереть пару строчек кода которые за настройку отвечают, а фичи которые есть в transmission вообще не факт что в движке libtorrent есть

**Comment by Yapidor666** [comment]
> > В нём как раз нету. В transmission есть.
> 
> Transmission и qBitTorrent используют разные движки, у меня тот, что в qBitTorrent (libtorrent), по этому и прошу на него референсы делать, так как я могу просто открыть его исходники и спереть пару строчек кода которые за настройку отвечают, а фичи которые есть в transmission вообще не факт что в движке libtorrent есть

Да я это понял уже. Просто думал что есть какой-то варик перенести.
Лимит оч мешает часто, кста. Как-то нужно было много скачать, а он на паузу ставит. И опсос стал как-то палить что качаю, хз, как вапще. Поэтому и попросил добавить ещё шифрования.

**Comment by ed2007** [comment]
> почти всё что мне надо и так есть, а чего нет, либо сам сделаю либо обходными путями добьюсь
Не в тему, но остро нехватает таймера сна для ютуба с продлением «если потрясти».
