### ISSUE TITLE
Crashes on launch IOS 15.7.7 Palera1n

### ISSUE THREAD

**Issue by galaxy-nomad** [XITRIX/iTorrent#258]
Thanks for all of your work in updating the app. For me latest release crashes on launch with palera1n (rootful), iOS 15.7.7 and iPhone 6s. Are there any tweaks required to get it running?

**Comment by XITRIX** [comment]
Try to use clean install (remove app first), it could be in case of broken resume data in libtorrent

**Comment by galaxy-nomad** [comment]
I found a newer version 1.9.2 that is not available in your releases. That version works perfectly.

**Comment by galaxy-nomad** [comment]
The only "issue" with the app overall is if you change network connection the torrent starts over from 0mb which is very frustrating after waiting hours to download a torrent🤣

**Comment by XITRIX** [comment]
Yea, there are some issues with connectivity, but to be honest I have no idea how to handle them, cause all connectivity part is under libtorrent responsibility

**Comment by galaxy-nomad** [comment]
Ok thank you for putting together this app! Why don't you make version 1.9.2 available in your releases if it is the latest version? I only see 1.8.3 which would be very old compared to 1.9.2 correct?

**Comment by XITRIX** [comment]
Yeah, I'm just a lazy ass :)

I want to put it as a release when I'll polish it, but I cannot find time to do it properly
