### ISSUE TITLE
deb release?

### ISSUE THREAD

**Issue by delon5** [XITRIX/iTorrent#26]
Is it possible to get a deb release for jailbreak?

Cheers

**Comment by XITRIX** [comment]
You can simply install IPA with jailbreak using Impactor, or whatever jailbreakers using for it, also I don't know how to create DEB files 'cause I am not jailbreak user.

**Comment by delon5** [comment]
Yeah that is what I do at the moment. If I use reprovision (impactor) everytime it reinstalls sympolic links for the torrent download directory get messed up as it is always installed to a new path.

**Comment by XITRIX** [comment]
But with jailbreak you could somehow install it without needs to reinstall it using (appsync?) and (itunes?), no?

**Comment by delon5** [comment]
filza with appsync didn’t work. Guess I will keep using it as is.

Any way to give an option to use the seeding without the backgrounding action in the app? I use a tweak to force the app to foreground however the app never seeds though the night and at some point gets killed or crashes.

**Comment by delon5** [comment]
I tried to install with appsync and filza but it didn’t allow install.

**Comment by delon5** [comment]
Was able to sign the app through terminal and then install with appsync.
