### ISSUE TITLE
Crash on launch iOS 14.4.2 ver.1.9 build 23

### ISSUE THREAD

**Issue by alian2plus** [XITRIX/iTorrent#260]
Crash log:

https://pastebin.com/raw/c5mQFJaJ

**Comment by XITRIX** [comment]
Looks like it's crashlog from download widget, it should not have any impact on main app.

There should be another crashlog related to the app itself

**Comment by alian2plus** [comment]
> Looks like it's crashlog from download widget, it should not have any impact on main app.
> 
> 
> 
> There should be another crashlog related to the app itself

I retrieved back old version of ITorrent 1.8.3 and it works smooth with no crashes . Only versions with 1.9 from first build up to build 22 sends crash notifications every time i use the app and not fully crashing, the build 23 crashes the app instantly.

I'm using Jailbreak.

**Comment by XITRIX** [comment]
crashlogs I think are from live activity extension, maybe I've missed iOS version check somewhere 

about build 23 need to check
