### ISSUE TITLE
iTorrent 1.9 not downloading from Private trackers

### ISSUE THREAD

**Issue by KingShadow-UK** [XITRIX/iTorrent#262]
@XITRIX Hello I lost my previous account and was wondering if you found a fix for the latest iTorrent that has issues with connecting to private trackers?

**Comment by XITRIX** [comment]
Added fix to SSL framework, check if issue fixed pls

**Comment by KingShadow-UK** [comment]
Yes same here no private trackers download and also if a torrent is downloading if I kill the app and go back into it the torrent download disappeared and have to redownload
