### ISSUE TITLE
App not going through the vpn

### ISSUE THREAD

**Issue by EscapeAltDelete** [XITRIX/iTorrent#263]
![image](https://github.com/XITRIX/iTorrent/assets/96600150/8c4cf8ed-f6a7-49ea-82a5-6e5602cd1f57)

**Comment by EscapeAltDelete** [comment]
Specs:
iOS 16.1.1 
iPhone 12

**Comment by EscapeAltDelete** [comment]
just read the comment from 2 years ago explaining this problem sorry for making a duplicate issue.

**Comment by EscapeAltDelete** [comment]
Does anybody know the release that won't use all network interfaces?

**Comment by socksprox** [comment]
Need help too

**Comment by XITRIX** [comment]
Should work in v2
