### ISSUE TITLE
Can’t install appcenter build

### ISSUE THREAD

**Issue by socksprox** [XITRIX/iTorrent#270]
![IMG_1375](https://github.com/XITRIX/iTorrent/assets/36358673/05bd2f91-ad41-4d0c-b449-df310df8557a)
(Logged in and registered device too)

**Comment by XITRIX** [comment]
You can install appcenter build only on jailbroken device. If it's not, you should download ipa file using PC and install using AltStore or any other sideload install method

**Comment by socksprox** [comment]
> You can install appcenter build only on jailbroken device. If it's not, you should download ipa file using PC and install using AltStore or any other sideload install method

Using appcenter, if i download the ipa on windows, it doesn’t work to install, only the built older version not from appcenter. Maybe it’s decrypted?

**Comment by XITRIX** [comment]
Should not, it is signed with my own cert so I'm able to install it to my devices, also altcenter should install even unsigned ipas so ... I'm not sure
