### ISSUE TITLE
Why not enable Chinese?

### ISSUE THREAD

**Issue by nijinekoyo** [XITRIX/iTorrent#274]
I noticed that there is already a Chinese translation in the project, why not enable it in the settings?
![image](https://github.com/XITRIX/iTorrent/assets/125987288/e41b6fb1-9177-4938-9d67-8ebf2a779167)

**Comment by XITRIX** [comment]
Hi, what do you mean "enable in the settings"?

**Comment by XITRIX** [comment]
Oh, I see there is no Chinese available while translation itself exists. I'm not maintaining languages other then Rus and Eng by myself, so I've missed this. If you are able to make a Pull request I'll be glad to merge it.

**Comment by nijinekoyo** [comment]
Sorry, I don't quite understand. I noticed that the folder [zh-Hans.lproj](https://github.com/XITRIX/iTorrent/tree/master/iTorrent/zh-Hans.lproj) already exists. Are the translation files in it unavailable?

**Comment by nijinekoyo** [comment]
I have submitted the Chinese translation file in this [commit](https://github.com/XITRIX/iTorrent/commit/1f087b8bcd4458c4e8090b43283d6daa6d6c2d05). Why can’t I still use Chinese in the settings? Do I need to provide more information?

**Comment by XITRIX** [comment]
Fixed in latest commit, check the AppCenter build in 30 mins
