### ISSUE TITLE
Private Tracker Torrents Not Downloading on Device (Works on Simulator)

### ISSUE THREAD

**Issue by pushtrue** [XITRIX/iTorrent#275]
Device: iPhone 15 Pro Max
iOS Version 17.0.3
Xcode: 15.0
Cocoapods: 1.13
iTorrent Version: Current files on GitHub as of Oct 19-2023

When adding a torrent file that is from a private tracker on a device, the torrent shows in the list, but never starts downloading. The tracker shows "Working" as the status, but no peers ever connect. This is different behavior than iTorrent 1.8.4. 

However, on the Simulator (iPhone 15 Pro Max Simulated), there are no issues.

Public tracker torrents work fine on device.

**Comment by pushtrue** [comment]
Additional information, it seems to happen when the private torrent is using SSL tracker URLs. When disabling these on the tracker end, there is no longer an issue on the device. Interestingly, simulator can still do them either way.

**Comment by SydneyUrshan** [comment]
Same here (torrents do not start downloading) for iTorrent version 1.9-dev2 (clean download from App Center), on iPhone 7 Plus, iOS 15.8. The previous iTorrent version suddenly stopped working and can no longer be installed. This is my only way to download torrents, so an update, patch, etc. (for any version) would be greatly appreciated!

**Comment by ghazel** [comment]
#262

**Comment by XITRIX** [comment]
Added fix to SSL framework, check if issue fixed pls

**Comment by ghazel** [comment]
> Added fix to SSL framework, check if issue fixed pls

Tried it, this did not seem to fix it.

**Comment by pushtrue** [comment]
Also tried this, and it also did not fix it for me. Thank you for responding! Appreciate the work you do on this app!
