### ISSUE TITLE
Cannot install app

### ISSUE THREAD

**Issue by rong-xiaoli** [XITRIX/iTorrent#277]
When I downloaded this app and clicked it, it showed that its integrity cannot be verified. 
I guess it's the platform's fault but I can only ask for help here X(
Any help would be appreciated.

**Comment by XITRIX** [comment]
You cannot install app from AppCenter if your device is not jailbroken, you need to download ipa file and install it using any available sideload method i.e. AltStore\SideStore

**Comment by mailinglists35** [comment]
@XITRIX how to download dev ipa? appcenter only shows Install button. I have trollstore so all I need is the IPA file.

or alternatively can you update the release IPA?

**Comment by XITRIX** [comment]
You could enable PC mode on the page in Safari, it will allow you to download the ipa file

**Comment by mailinglists35** [comment]
I tried using Request Desktop website on Safari, tried alternative browsers such as Brave and Zoomable (particularly zoomable gets desktop versions always), but somehow appcenter still detects I am running on mobile - do you know any mobile browser that can fully cheat appcenter to believe it is a desktop?

**Comment by XITRIX** [comment]
Hmm... You are right, I cannot open in desktop mode as well, [here is the latest version from AppCenter](https://github.com/XITRIX/iTorrent/files/15232322/iTorrent.1.ipa.zip)
