### ISSUE TITLE
Any way to install dev build?

### ISSUE THREAD

**Issue by IntangibleW** [XITRIX/iTorrent#279]
I downloaded the last dev build in AppCenter, and sideloaded using SideStore, then get following error:
![image](https://github.com/XITRIX/iTorrent/assets/43871076/7841721f-5acc-4925-a882-3132d6f75a5d)

**Comment by XITRIX** [comment]
Looks like an issue of sideloading tool, try to use AltStore or SideStore

**Comment by IntangibleW** [comment]
> Looks like an issue of sideloading tool, try to use AltStore or SideStore

I’m using sidestore

**Comment by XITRIX** [comment]
Try the latest build, should be fixed

**Comment by IntangibleW** [comment]
confirm fixed
