### ISSUE TITLE
Pre-Release 1.9 (24.0) (December 2023) Does Not Download

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#281]
This version installs fine from the App Center. However, torrents with many seeds show in the list and have activity, but they never start downloading. This problem started when I installed the July version of 1.9 (23.0) after one of the older versions expired.

Thanks!

iPhone 7 Plus, iOS 15.8

**Comment by XITRIX** [comment]
~~Did you install it from scratch? Not sure why it could happen, I'm using app quite often and it downloads fine for me~~

Found an issue with OpenSSL framework and fixed it, try the latest build pls

I'll close an issue, if still presented feel free to reopen it

**Comment by SydneyUrshan** [comment]
I just downloaded the new 1.9 (25.0) after completely deleting the old version and it's the same: Time remains is actively changing, "Seeders 0 (22), Leechers 0 (20), download status 0 B of 4.23 GB (0.00%)", etc.

I sent a DM on Patreon about testing it on my iPad Pro.

**Comment by SydneyUrshan** [comment]
A further point of interest about the latest version (Dec 17, 2023) not working for me... if hashing is attempted on a torrent, it stays in the hash mode in perpetuity.
