### ISSUE TITLE
Pre release 1.9 signing error

### ISSUE THREAD

**Issue by PCMasterRace8** [XITRIX/iTorrent#282]
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(2326): _assert(): DiskFolder::Open(Frameworks/ITorrentFramework.framework/Frameworks/ITorrentFramework.framework/Frameworks/OpenSSL.framework/Info.plist)
 15PM ios 17.2

**Comment by XITRIX** [comment]
~~How are you trying to install it?~~

Found an issue and fixed it, try the latest build pls

**Comment by XITRIX** [comment]
Found an issue and fixed it, try the latest build pls
