### ISSUE TITLE
Can't open, crashes.

### ISSUE THREAD

**Issue by ghost** [XITRIX/iTorrent#285]
A11

iOS 16.1.1

TrollStore 2.0.8

[Pre-Release 1.9 (December 2023)](https://github.com/XITRIX/iTorrent/releases/tag/v1.9-pre)

![E0164559-6BA8-4BB1-A0FD-BD012309072A](https://github.com/XITRIX/iTorrent/assets/153827846/fede4c9a-9a23-484f-981c-eadbde5a0918)

**Comment by XITRIX** [comment]
~~Did you installed app from scratch?~~

Fixed an issue with OpenSSL framework, try the latest build pls.

I'll close an issue, if it is still not solved, feel free to reopen it
