### ISSUE TITLE
Exception when installing using AltStore

### ISSUE THREAD

**Issue by nijinekoyo** [XITRIX/iTorrent#286]
![image](https://github.com/XITRIX/iTorrent/assets/125987288/f320e5eb-ab54-4ad0-9f00-da417051c6c0)

Error Log: 
```
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(2326): _assert(): DiskFolder::Open(Frameworks/ITorrentFramework.framework/Frameworks/ITorrentFramework.framework/Frameworks/OpenSSL.framework/Info.plist)
```

Installed version: [v1.9-pre](https://github.com/XITRIX/iTorrent/releases/tag/v1.9-pre)

**Comment by nijinekoyo** [comment]
iPad OS 17.1.2

**Comment by nijinekoyo** [comment]
After testing, this problem already exists in `Version 1.9 (23.0)`
`Version 1.8.4-dev.3 (21.0)` can be installed normally

**Comment by XITRIX** [comment]
Found an issue in OpenSSL building process, try to load the latest one pls, hope it will help.

I'll close the issue, if it still not fixed, reopen it pls
