### ISSUE TITLE
НА 14.3 КРАШИТ, БРАТАН.

### ISSUE THREAD

**Issue by Yapidor666** [XITRIX/iTorrent#287]
Можешь ипу дропнуть для чека? Или фиксануть? Спс заранее!

**Comment by Yapidor666** [comment]
> Можешь ипу дропнуть для чека? Или фиксануть? Спс заранее!

Пред версия ворк гуд, если чо.

**Comment by XITRIX** [comment]
какая версия крашит, какая "предыдущая ок", чуть больше инфы не помешало бы

проверь версию с AppCenter, сегодня правил один краш

**Comment by Yapidor666** [comment]
> какая версия крашит, какая "предыдущая ок", чуть больше инфы не помешало бы
> 
> проверь версию с AppCenter, сегодня правил один краш

Ласт, которая сёдня. Предыдущую ты делитнул, была неск дней назад. Кста, поч?
Краш на ласт осях? Видимо, на них закрыл, а на олдовых, как у меня, случайно открыл.

**Comment by XITRIX** [comment]
Вернул рабочую для скачивания, пока не пойму в чём дело

**Comment by Yapidor666** [comment]
> Вернул рабочую для скачивания, пока не пойму в чём дело

Спс. А поч удалял-то, кста?

**Comment by XITRIX** [comment]
Потому что я считал, что это сломанный билд который у многих крашится

**Comment by Yapidor666** [comment]
> Потому что я считал, что это сломанный билд который у многих крашится

Пон. А у меня как раз ворк.
