### ISSUE TITLE
How to install iTorrent on iOS

### ISSUE THREAD

**Issue by superbonaci** [XITRIX/iTorrent#29]
How can I install iTorrent on iOS latest version?

**Comment by XITRIX** [comment]
Without jailbreak you can use Cydia Impactor or services like appdb.
With jailbreak you can use appsync + iTunes.
Good luck!

**Comment by superbonaci** [comment]
Couldn't find any iTorrent on appdb, however I've installed iTransmission. If you still know how to accurately install iTorrent please update.
I don't have jailbreak.

**Comment by XITRIX** [comment]
You can install ipa using appdb, which you can download here:
https://github.com/XITRIX/iTorrent/releases

**Comment by superbonaci** [comment]
appdb is a website or an app? If it's a website, which is the right one, because there lots of scams on the internet?

**Comment by superbonaci** [comment]
Ok I've found it, it looks like it requires appdb PRO to allow you to install apps if you don't have a developer identity, and the pricing is 20 eur + VAT, plus the "license" is only for one device...
