### ISSUE TITLE
Every Version of 1.9 Will Not Download Torrents or Rehash

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#291]
All versions of 1.9 install from the App Center (clean install from scratch). However, torrents with many seeds show in the list and have activity, but they never start downloading. This problem started when I installed the July version of 1.9 (23.0) after one of the older versions expired.

'Time remains' is actively changing, however, "Seeders 0 (22), Leechers 0 (20), download status 0 B of 4.23 GB (0.00%)" etc., stay at zero and do not advance notwithstanding the large amount of seeders present (the 22 and 20 shown in the example above fluctuate, but the 0 stays the same).

Further, if rehash is started on a torrent, hashing keeps attempting in perpetuity until the torrent file is deleted and added again. Restarting the app alone does not fix it once a torrent gets stuck in hashing mode. Also, once a torrent starts hashing, there is no longer any activity on the particular torrent.

This issue was already raised in #281. It was closed instructing me to reopen it if the problem still presented itself.

Thank you.

iPhone 7 Plus, iOS 15.8

**Comment by SydneyUrshan** [comment]
Check Patreon.

**Comment by PCMasterRace8** [comment]
The workaround is to kill the app and start it again then it will start downloading. As for the "hash" is completely broken no workarounds for this.

Edit 
He downgraded Libtorrent library to 1.2.19 [](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public) give it a try...

**Comment by SydneyUrshan** [comment]
The new Libtorrent fixed everything and I've been running it for a while now without even a single crash! This issue can be safely closed.

**Comment by XITRIX** [comment]
Unfortunately it's not "new" it's old libtorrent version, and that means that I cannot upgrade libtorrent to v2, with new features like hashv2. Hope it will be fixed in future releases of libtorrent v2

**Comment by SydneyUrshan** [comment]
Thanks for the clarification. I've been meaning to ask... will the current working version ever expire? If so, when?

I understand that it's not 'new' but things are working really smooth without a single crash on iPhone and iPad Pro and I hope to run them at least until the 'real' new version that you refer to is released.

**Comment by SSpaZioMilano** [comment]
> Thanks for the clarification. I've been meaning to ask... will the current working version ever expire? If so, when?
> 
> The version I refer to is Version 1.9 (25.0) released on January 25, 2024.
> 
> I understand that it's not 'new' but things are working really smooth without a single crash on iPhone and iPad Pro and I hope to run them at least until the 'real' new version that you refer to is released.

Hi how is possible to have the Jan 25 2024 version?
Thanks

**Comment by XITRIX** [comment]
> Hi how is possible to have the Jan 25 2024 version? Thanks

Hi, in [ReadMe Download](https://github.com/XITRIX/iTorrent?tab=readme-ov-file#download) section, open [AppCenter](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public) link, there you can find all development builds, use PC to download ipa files, don't try to install them directly on you iPhone\iPad

**Comment by SSpaZioMilano** [comment]
Thanks just installed with sideloadly and for now work very good.Envoyé de mon iPhone 15Pro MaxLe 10 févr. 2024 à 08:45, Vinogradov Daniil ***@***.***> a écrit :﻿

Hi how is possible to have the Jan 25 2024 version? Thanks

Hi, in ReadMe Download section, open AppCenter link, there you can find all development builds, use PC to download ipa files, don't try to install them directly on you iPhone\iPad

**Comment by SSpaZioMilano** [comment]
Hi, just downloaded the new 2.07.-5 on my iPhone 15 pro max on iOS 18 beta3 and is not possible ton add a .torrent in the app, is absolutely don’t work.Envoyé de mon iPhone 15Pro MaxLe 14 juill. 2024 à 16:06, Vinogradov Daniil ***@***.***> a écrit :﻿
Closed #291 as completed.

**Comment by SSpaZioMilano** [comment]
﻿Hi, just downloaded the new 2.07.-5 on my iPhone 15 pro max on iOS 18 beta3 and is not possible ton add a .torrent in the app, is absolutely don’t work.Envoyé de mon iPhone 15Pro MaxLe 14 juill. 2024 à 16:06, Vinogradov Daniil ***@***.***> a écrit :﻿
Closed #291 as completed.

**Comment by SSpaZioMilano** [comment]
﻿﻿Hi, just downloaded the new 2.07.-5 on my iPhone 15 pro max on iOS 18 beta3 and is not possible ton add a .torrent in the app, is absolutely don’t work.Envoyé de mon iPhone 15Pro MaxLe 14 juill. 2024 à 16:06, Vinogradov Daniil ***@***.***> a écrit :﻿
Closed #291 as completed.
