### ISSUE TITLE
Not work background downloads

### ISSUE THREAD

**Issue by mmm286** [XITRIX/iTorrent#30]
Hi
I have iOS 12.1 and iPhone Xr.
It seems background downloads not working. When I change to other application without close downloads stops
Thanks and sorry for my English

**Comment by XITRIX** [comment]
Hi, have you enabled background downloading in the settings?
It should work on any iOS version, tested by me from 9.3 to 12.3 dev1

**Comment by mmm286** [comment]
Thanks for your fast answer!
Yes, I try disable "enable background" setting  and then enabled and same problem. I tried close de app and reopen app and same problem.
I've installed your ipa by "Ignition" sideload. I don't know if the problem could be for that way.

**Comment by XITRIX** [comment]
Hmm... I have not known about that service earlier, thanks for that :) But it’s a little bit strange, I dunno if they changed something in code of my app, to make sure, you can install my ipa from release page using cydia impactor, which 100% must have working background downloading and if the problem remains... it shouldn’t :). So if it will work, just try any another sideload service, appdb for example.
Hope it will help, good luck!
