### ISSUE TITLE
Ограничение

### ISSUE THREAD

**Issue by Tatarin96** [XITRIX/iTorrent#300]
Какое-то ограничение стоит на объем скачиваемого файла, больше 5гб уже не может качать. А полтора гига за просто.

**Comment by XITRIX** [comment]
Какая версия приложения?

**Comment by Tatarin96** [comment]
> Какая версия приложения?

1.9 dev2 2.0.9.0

**Comment by Tatarin96** [comment]
Пару килобайт качает и тут же обнуляется, в файлах в папке itorrent показывает файл и полный размер, и место выделяется под файл, но не качает, а файлы ~1.5гб качает без проблем. IOS 17.3 15 pro max

**Comment by XITRIX** [comment]
Попробуй последнюю сборку в AppCenter 1.9 (25.0), скажи поможет или нет

**Comment by Tatarin96** [comment]
> Попробуй последнюю сборку в AppCenter 1.9 (25.0), скажи поможет или нет

Сразу его ставил(

**Comment by XITRIX** [comment]
> 1.9 dev2 2.0.9.0

Тут указана другая версия, должна быть 1.9 dev2 | v1.2.19.0

**Comment by Tatarin96** [comment]
> > 1.9 разработчик 2 2.0.9.0
> 
> Тут указана другая версия, должна быть 1.9 dev2 | v1.2.19.0

А как сам файл скачать отдельно, просто он устанавливается, но версия не меняется, если удалить и установить с нуля то требует сертификата.

**Comment by Tatarin96** [comment]
Всё, заработало, спасибо большое)
