### ISSUE TITLE
Dynamic Island background progress not working

### ISSUE THREAD

**Issue by mido830** [XITRIX/iTorrent#302]
1.9 release note list this feature:

> Dynamic Island background progress

But I'm not seeing progress in the dynamic island.
Video showing the problem:

https://youtube.com/shorts/e6ZEgRNwWTU?si=1oObTrahCXnzU7Xg

**Comment by XITRIX** [comment]
That's strange, cause on you video I literally see how app "sucks" into dynamic island moving your screen recording bubble to the right, do you have the activity widget with progress in notification centre?

**Comment by mido830** [comment]
Nope
https://youtube.com/shorts/e6ZEgRNwWTU?si=IQtK7qimKs3F6ozg

**Comment by XITRIX** [comment]
How did you installed the app? Dynamic Island is an app extension that some sideloaders could break during installation. 

And according to your another opened issue your installation is definitely broken

**Comment by mido830** [comment]
I installed the IPA file using [Sideloadly](https://sideloadly.io/)

**Comment by XITRIX** [comment]
I think I had issues with app extensions installed with Sideloadly, but I'm not 100% sure about it

**Comment by PCMasterRace8** [comment]
same thing for me here installed using sideloadly and the extensions wont work (latest dev build)
Iam using "Background mode" "Location"!

**Comment by XITRIX** [comment]
You should use "Background mode - Location" to make it work

**Comment by XITRIX** [comment]
Should work in v2
