### ISSUE TITLE
Signing error while installing 1.9 (25) (jan 25)

### ISSUE THREAD

**Issue by PCMasterRace8** [XITRIX/iTorrent#303]
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(2326): _assert(): DiskFolder::Open(Frameworks/ITorrentFramework.framework/Frameworks/ITorrentFramework.framework/Frameworks/openssl.framework/Info.plist)

**Comment by yerseg** [comment]
It seems like dev builds from AppCenter cannot to be installed with AltStore...
