### ISSUE TITLE
Cant find files

### ISSUE THREAD

**Issue by sukoshiotokonoko** [XITRIX/iTorrent#304]
When i open up the files app, then go to "On My iPhone" there is no itorrent folder.

**Comment by sukoshiotokonoko** [comment]
The files also appear in iphone storage when i click on the app just no folder for it in the files app

**Comment by XITRIX** [comment]
try open them from iTorrent using "Show in Files" button

**Comment by sukoshiotokonoko** [comment]
Doesnt work
https://github.com/XITRIX/iTorrent/assets/69873721/b571865c-2e1b-424d-ab11-1ba4e6907498

**Comment by sukoshiotokonoko** [comment]
Oh and i am on the newest dev build. I also used to have it and then deleted and this is the reinstall from last night. If any of that means anything to do with this problem

**Comment by sukoshiotokonoko** [comment]
I ended up extracting them using imazing on my pc

**Comment by sukoshiotokonoko** [comment]
Ok not even the slightest clue on how, but it appeared? mabye because i deleted the files from the app after i downloaded through my computer.

**Comment by XITRIX** [comment]
I have no idea as well, from my side it's just a flag "should Files app show content of app or not", looks like iOS bug
