### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by yeet227** [XITRIX/iTorrent#307]
Create a Search Function in the RSS area of the app make it easier to search for things

**Comment by XITRIX** [comment]
For now you can search through RSS on main page in the same search bar where torrents are. Also iTorrent app is currently on complete rework from scratch and if you are talking about such search as on screenshot below, than it is already implemented and will be available in future version

![IMAGE 2024-05-01 10:31:58](https://github.com/XITRIX/iTorrent/assets/9553519/79963f7e-124e-4f8b-ae0c-70b7df533a9b)
