### ISSUE TITLE
Missing Add To Gallery.

### ISSUE THREAD

**Issue by blackwing182** [XITRIX/iTorrent#31]
It would be nice to have an option to save movies/videos to ios Gallery app. Other than that itorrent is fine! Good job!

**Comment by XITRIX** [comment]
Hi, once I have tried to implement it, but don’t know why, tap on “add to gallery” button causes app crash, so I gave up with that idea :)
Thanks for feedback!

**Comment by XITRIX** [comment]
Added in Release 1.8
