### ISSUE TITLE
Bind to VPN

### ISSUE THREAD

**Issue by Hoe2020** [XITRIX/iTorrent#310]
This has likely been brought up a hundred times but the ability to bind to a VPN like qbittorrent would be AMAZING!

**Comment by XITRIX** [comment]
iTorrent v2 will be released soon, it will have ip leak protection feature

**Comment by Hoe2020** [comment]
THANKS SO MUCH!

**Comment by XITRIX** [comment]
Now should works fine with iTorrent v2

**Comment by kert-g** [comment]
How you enable it? / How does it work?

**Comment by Hoe2020** [comment]
It is auto-enabled

**Comment by Hoe2020** [comment]
It binds to your Iphone’s VPN features.
