### ISSUE TITLE
The storage space occupied is not released normally

### ISSUE THREAD

**Issue by nijinekoyo** [XITRIX/iTorrent#311]
If you select `Yes but keep data` when deleting a download, and then delete the data in the `Files` app, the occupied storage space will not be released.
![image](https://github.com/XITRIX/iTorrent/assets/125987288/fa1da7c5-1c7f-470f-a3e5-8a622f9417c6)
![image](https://github.com/XITRIX/iTorrent/assets/125987288/9c69e80d-614a-4730-807c-69b2bc5f7b92)
![image](https://github.com/XITRIX/iTorrent/assets/125987288/53c6a558-d7aa-4367-a6f4-7f0e135356b0)

**Comment by XITRIX** [comment]
Not related to iTorrent, it's Files app issue, try to check "Recently Deleted" folder, otherwise reinstall Files app, sometimes it could help

**Comment by nijinekoyo** [comment]
thx！It is indeed in the recent deletion.
