### ISSUE TITLE
Dynamic island stays open even when i close the app

### ISSUE THREAD

**Issue by officiallor** [XITRIX/iTorrent#314]
I added a torrent to download and after a while I removed it and its data. After that I just closed the app but the dynamic island is still there.
It seems that it is related to the notification not being dismissed from the lock screen.

Latest version 2.0.7-2

![IMG_0668](https://github.com/XITRIX/iTorrent/assets/8017707/81c577e0-b0c2-458e-bcde-034fb7f9157a)

**Comment by PCMasterRace8** [comment]
Same issue here I killed the app and it still shows up on Dynamic Island

**Comment by XITRIX** [comment]
It’s bug, I forgot to notify services about torrent deletion so they stuck it latest reported state
Btw, app cannot send “close” event on app termination, so probably I will not be able to close Dynamic Island on app close
Also v2 is still in beta, I didn’t released it completely yet

**Comment by officiallor** [comment]
I added some easy to spot issues. I hope that you don't mind even if it's beta.

**Comment by XITRIX** [comment]
Of course no, beta exists to find bugs in it :D 
I just noted that to not expect everything to work properly

**Comment by SubhamSubhasisPatra** [comment]
With the latest version also Dynamic Island is not working

**Comment by XITRIX** [comment]
What do you mean "not working", be more specific please

**Comment by SubhamSubhasisPatra** [comment]
> What do you mean "not working", be more specific please

No not working at all , while a download is going on and I minimize the app no download progress indicators is showing in the Dynamic Island.

**Comment by XITRIX** [comment]
It's not app related issue, how did you installed the app?

**Comment by SubhamSubhasisPatra** [comment]
> It's not app related issue, how did you installed the app?

I installed from AltStore.

**Comment by XITRIX** [comment]
Did you selected "Keep App Extensions"? 
![IMG_2543](https://github.com/user-attachments/assets/b0618e59-1964-4791-b49f-6bd359e4891a)

**Comment by SubhamSubhasisPatra** [comment]
> Did you selected "Keep App Extensions"? 
> 
> ![IMG_2543](https://github.com/user-attachments/assets/b0618e59-1964-4791-b49f-6bd359e4891a)
> 
> 

Yes

**Comment by XITRIX** [comment]
No idea then, try to reinstall it ...
Did you allowed it in the settings?

**Comment by SubhamSubhasisPatra** [comment]
> No idea then, try to reinstall it ...
> 
> Did you allowed it in the settings?

Will keep u posted after trying

**Comment by XITRIX** [comment]
Check this one as well
![IMG_2544](https://github.com/user-attachments/assets/08a9184e-a78c-41f6-8343-a737f9a45ab7)

**Comment by SubhamSubhasisPatra** [comment]
> Check this one as well
> 
> ![IMG_2544](https://github.com/user-attachments/assets/08a9184e-a78c-41f6-8343-a737f9a45ab7)
> 
> 

That is also enabled for me. What's the version u r currently on ?. Mine is `v2.0.8-1`

**Comment by XITRIX** [comment]
Just installed fresh ipa v2.0.8-1 from GitHub releases with AltStore, DynIsland works fine for me
![IMG_2545](https://github.com/user-attachments/assets/1f288cfb-b882-4065-83f8-5c7299da064d)

**Comment by SubhamSubhasisPatra** [comment]
> Just installed fresh ipa v2.0.8-1 from GitHub releases with AltStore, DynIsland works fine for me
> 
> ![IMG_2545](https://github.com/user-attachments/assets/1f288cfb-b882-4065-83f8-5c7299da064d)
> 
> 

I downloaded the previous version and it worked for me 2.0.7-5![image](https://github.com/user-attachments/assets/a4e2ff69-5a28-428b-950b-faca2fd0bd7d)

**Comment by XITRIX** [comment]
v2.0.8-1 is exactly the same as v2.0.7-5, I just increased version to see crashlytics data separated by versions (there was crash in *.7-2 which was fixed in *.7-5, but crashlytics could not close it because there was no new version)
<img width="311" alt="image" src="https://github.com/user-attachments/assets/8fb34900-d261-4386-b230-d7b54ffa32fc">
Here is git history, there is only code analysis and altstore generator fixes

So it's definitely something wrong with your local installation

**Comment by SubhamSubhasisPatra** [comment]
> v2.0.8-1 is exactly the same as v2.0.7-5, I just increased version to see crashlytics data separated by versions (there was crash in *.7-2 which was fixed in *.7-5, but crashlytics could not close it because there was no new version)
> 
> <img width="311" alt="image" src="https://github.com/user-attachments/assets/8fb34900-d261-4386-b230-d7b54ffa32fc">
> 
> Here is git history, there is only code analysis and altstore generator fixes
> 
> 
> 
> So it's definitely something wrong with your local installation

I'm suspecting the same , let me delete it and do a clean install

**Comment by XITRIX** [comment]
Fixed in 2.0.13
