### ISSUE TITLE
Background downloading broken ?

### ISSUE THREAD

**Issue by PCMasterRace8** [XITRIX/iTorrent#316]
When I switch to another app or while in home screen background downloading stops but when I switch to itorrent again it starts downloading again immediately.

**Comment by XITRIX** [comment]
Provide more details please, are you talking about new v2 release? If yes, it should work

**Comment by PCMasterRace8** [comment]
> Provide more details please, are you talking about new v2 release? If yes, it should work

Signed using altstore device is 15 PM IOS 17.5.1 itorrent 2.07.3
The app becomes laggy like its overloading because it gets hot and battery drains quickly even though it's not downloading so I guess this means itorrent is not optimized for the latest hardware?

**Comment by XITRIX** [comment]
I have 15PM, iOS 18 beta, app works smoothly and device temp is ok'ish during download and cold in idle. Does it lags immediately on app launch? Do you have lots of torrent? Any details, please, which could help me to locale the problem

**Comment by PCMasterRace8** [comment]
> I have 15PM, iOS 18 beta, app works smoothly and device temp is ok'ish during download and cold in idle. Does it lags immediately on app launch? Do you have lots of torrent? Any details, please, which could help me to locale the problem 

If i have an active torrent then yes it lags immediately plus when i tap on it to go the where you see all the information of the current torrent it takes about 5 seconds or so to show up .
Tried downloading only a single torrent to see if it only  happens while downloading 2-3 torrents and it is the same.
In other words the only way i can fully download a torrent is to remain on the itorrent app while the device remains unlocked.

**Comment by XITRIX** [comment]
If it's ok for you, could you share this torrents which causes lags for you?

**Comment by PCMasterRace8** [comment]
> If it's ok for you, could you share this torrents which causes lags for you?

It doesn't matter the torrent 

I chose randomly from x1337 site specifically from "Most Popular Torrents this week" the ones with the most seeds just to test the app .

**Comment by PCMasterRace8** [comment]
> > If it's ok for you, could you share this torrents which causes lags for you?
> 
> It doesn't matter the torrent 
> 
> I chose randomly from x1337 site specifically from "Most Popular Torrents this week" the ones with the most seeds just to test the app .

Edit: i wanted to let you know that I installed I transmission to monitor the behavior of background downloading and to my surprise I encountered the exact same bug. So there is nothing wrong with Itorrent , maybe it's a bug with ios 17 or a setting...
Thank you for time i guess you can close this "isue"

**Comment by XITRIX** [comment]
Looks like there are tons of different issues if app was signed incorrectly, the only tested and verified by myself way to install iTorrent without any issues is AltStore, and probably SideStore (because it's basically the fork of AltStore)
