### ISSUE TITLE
[iTorrent 2] Crash when you click to see more details when the torrent is still downloading metadata

### ISSUE THREAD

**Issue by freebritney132** [XITRIX/iTorrent#317]
Easy to reproduce by adding a torrent with basically no seeders

**Comment by freebritney132** [comment]
Also itorrent2 works so much better than 1.7.4 Like before I never saw download speeds above 5mb/s now I'm seeing 18mb/s

**Comment by XITRIX** [comment]
Yes, reproduced crash, thanks, going to fix it

**Comment by XITRIX** [comment]
Check v2.0.7-3, should be fixed now

**Comment by freebritney132** [comment]
Can confirm its fixed!
