### ISSUE TITLE
Open links from safari

### ISSUE THREAD

**Issue by SlightlyPeckish** [XITRIX/iTorrent#32]
The app works amazingly but the ability to open magnet links from safari and other browsers straight to the itorrent app would be great
![Like you can with other apps](https://user-images.githubusercontent.com/21175434/56436837-26cc7380-62d5-11e9-9e9d-9f7322c67fe0.png)

**Comment by XITRIX** [comment]
Hi, thanks for suggestion, but iTorrent already could do that:)

P.S. You could have a problem with it, if you have another torrent app on your phone

![3D957337-B414-4658-AE73-461F061ACF95](https://user-images.githubusercontent.com/9553519/56439610-5e481980-62ef-11e9-9ff3-7b77e9b7e423.png)
![418BD40C-BEF8-4327-8E41-707B6F2E0240](https://user-images.githubusercontent.com/9553519/56439611-5e481980-62ef-11e9-98ba-7b3ae785fb5b.png)

**Comment by SlightlyPeckish** [comment]
That doesn't show up for me it automatically tries to open it in a different app not itorrent

**Comment by XITRIX** [comment]
As I said, there could be a problem, if you have another app, which can open .torrent files, remove it and try
