### ISSUE TITLE
Minimum IOS version

### ISSUE THREAD

**Issue by Megatro-nn** [XITRIX/iTorrent#320]
Please make the app available for IOS 15 because it crushes on IOS 15 ![image](https://github.com/user-attachments/assets/f474a1e1-bd0a-4b07-b5e1-f68003e1d8a7)

**Comment by XITRIX** [comment]
App does not support iOS 15, it utilise a lot of SwiftUI APIs that appeared only in iOS 16 and have no alternatives for iOS 15, so it will not work on it
