### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by Deci8BelioS** [XITRIX/iTorrent#321]
I would like to add the Spanish language for the new version but I can't find the localizable.strings in the repository, I have the translated file working in the last recently released versions.

**Comment by XITRIX** [comment]
Hi, thanks a lot! You could find it in 
`iTorrent/Core/Assets/Localizable.xcstrings`

Highly recommend to use xCode to open and work with it

**Comment by Deci8BelioS** [comment]
Can't the .strings file be implemented directly?

**Comment by XITRIX** [comment]
No, it's outdated format

**Comment by Deci8BelioS** [comment]
But if you still generate the translation file in .strings

**Comment by XITRIX** [comment]
What do you mean? iTorrent do not use .strings format anymore, it's obsolete format

**Comment by Deci8BelioS** [comment]
![image](https://github.com/user-attachments/assets/0d77683d-8f0f-4d7d-9ab0-bda8da67145f)

**Comment by XITRIX** [comment]
It's not the same, it's compiled translation inside the ipa. The only way to translate app now, is to translate xcstrings file

**Comment by Deci8BelioS** [comment]
I have translated the .strings from English to Spanish and it works by adding the file to a folder called es.lproj.

**Comment by XITRIX** [comment]
I really cannot understand how you was able to translate something like this
![image](https://github.com/user-attachments/assets/d447f9c7-60e0-4dc0-bdf3-a1ee7107ad0e)
Anyway, if you want to translate the app, you need to translate xcstrings file, there is no other way to add new translation into the project

**Comment by Deci8BelioS** [comment]
opening the file with Filza and copying it to a .txt file for editing in Windows.

However, if there is no other way to add the translation, I don't think I will do it with the new way of doing it.

![IMG_0661](https://github.com/user-attachments/assets/e8f7f438-b2b0-4d52-9ada-472cb3f78a1c)
