### ISSUE TITLE
external storage issue

### ISSUE THREAD

**Issue by googlme123** [XITRIX/iTorrent#323]
formatted to exFAT and plugged in, shows up on Files app but when I go to add it as a storage location, pressing open or creating a folder inside the storage and pressing open doesn't mark it as a storage option in the app

**Comment by XITRIX** [comment]
I did not really get how you tried to add the new storage. To add new storage, you need to open

iTorrent -> Preferences -> Storage Preferences -> Agree with warning -> Storages Add more

iOS directory picker will open, there select the folder you’d like to use as a new storage (your external drive)

Done, next time you’ll try to add a new torrent, in the bottom right corner you’ll be able to select storage to download

**Comment by googlme123** [comment]
> I did not really get how you tried to add the new storage. To add new storage, you need to open
> 
> iTorrent -> Preferences -> Storage Preferences -> Agree with warning -> Storages Add more
> 
> iOS directory picker will open, there select the folder you’d like to use as a new storage (your external drive)
> 
> Done, next time you’ll try to add a new torrent, in the bottom right corner you’ll be able to select storage to download

Ya so iOS directory picker opens like normal but then when I click on my external storage it just opens my blank storage and tried adding a folder incase, here is a video it just nothing happens.

https://github.com/user-attachments/assets/aed0759f-bf07-4470-8bea-d66e15d4120c

**Comment by XITRIX** [comment]
Could you add any torrent with “Add from Files”? If no, it could be signing issue, looks like some signing services breaks something inside app and system file picker stops working. The only guarantee way to install app without any issues is AltStore

**Comment by googlme123** [comment]
> Could you add any torrent with “Add from Files”? If no, it could be signing issue, looks like some signing services breaks something inside app and system file picker stops working. The only guarantee way to install app without any issues is AltStore

your 100% right, i tried signing through Esign and MapleSigner but none of them worked, tried through Altstore and worked completely fine and was able to select storage and "add from files"
