### ISSUE TITLE
[BUG] Crashes on launch on iOS 15.0

### ISSUE THREAD

**Issue by korboybeats** [XITRIX/iTorrent#326]
The app crashes on launch every time on iOS 15.0 iPhone 13 Pro Max.

Crash log:

Incident Identifier: 8D3AC656-FE94-4C76-82AD-295DF360CF03
CrashReporter Key:   a246ac53fd9e23796d41b686df0a7d8785f2d091
Hardware Model:      iPhone14,3
Device Model:        D64AP
Process:             ProgressWidgetExtension [18867]
Path:                /private/var/containers/Bundle/Application/F8613720-C4EB-4FF8-B013-4756230BAD59/iTorrent.app/PlugIns/ProgressWidgetExtension.appex/ProgressWidgetExtension
Identifier:          com.xitrix.iTorrent2.ProgressWidget
Version:             2.0.8 (1)
Code Type:           ARM-64 (Native)
Role:                Background
Parent Process:      launchd [1]
Coalition:           com.xitrix.iTorrent2.ProgressWidget [1287]

Date/Time:           2024-07-22 13:12:12.7201 +0900
Launch Time:         2024-07-22 13:12:12.7122 +0900
OS Version:          iPhone OS 15.0 (19A346)
Release Type:        User
Baseband Version:    1.00.03
UDID:                00008110-000E54E92E82801E
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: DYLD 1 Library missing
Library not loaded: /System/Library/Frameworks/ActivityKit.framework/ActivityKit
Referenced from: /private/var/containers/Bundle/Application/F8613720-C4EB-4FF8-B013-4756230BAD59/iTorrent.app/PlugIns/ProgressWidgetExtension.appex/ProgressWidgetExtension
Reason: tried: '/System/Library/Frameworks/ActivityKit.framework/ActivityKit' (no such file)

Triggered by Thread:  0

Application Specific Information:
Library not loaded: /System/Library/Frameworks/ActivityKit.framework/ActivityKit
Referenced from: /private/var/containers/Bundle/Application/F8613720-C4EB-4FF8-B013-4756230BAD59/iTorrent.app/PlugIns/ProgressWidgetExtension.appex/ProgressWidgetExtension
Reason: tried: '/System/Library/Frameworks/ActivityKit.framework/ActivityKit' (no such file)

Thread 0 Crashed:
0   dyld                          	       0x104eec198 0x104ea4000 + 295320
1   dyld                          	       0x104ef1d5c 0x104ea4000 + 318812
2   dyld                          	       0x104ef1d90 0x104ea4000 + 318864
3   dyld                          	       0x104ec22b4 0x104ea4000 + 123572
4   dyld                          	       0x104ebf578 0x104ea4000 + 111992
5   dyld                          	       0x104ebda04 0x104ea4000 + 104964

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b2d2ca0   x3: 0x00000000000000ec
    x4: 0x000000016b2d28a0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000240
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x00000002144a6c29  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x0000000104ee6830  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b2d28a0  x21: 0x00000000000000ec  x22: 0x000000016b2d2ca0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016b2d3678  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016b2d2870   lr: 0x0000000104ef1d5c
    sp: 0x000000016b2d2830   pc: 0x0000000104eec198 cpsr: 0x00000000
   far: 0x0000000104c6c000  esr: 0x56000080  Address size fault

Binary Images:
       0x104ea4000 -        0x104efbfff dyld arm64e  <444f50414d494e45444f50414d494e45> /usr/lib/dyld

Filtered syslog:
None found

EOF

**Comment by egigoka** [comment]
iOS 15 is no longer supported
