### ISSUE TITLE
Unable to add torrent file, magnet links work fine

### ISSUE THREAD

**Issue by dafaqboooom** [XITRIX/iTorrent#332]
Cant add torrent files by clicking or even sharing, the only stable build is the 1.9 one im using from before 2.0
[

https://github.com/user-attachments/assets/8614234d-b215-4e4c-9fd2-d0b2f2566ac4

](url)

**Comment by officiallor** [comment]
#315

**Comment by XITRIX** [comment]
Duplicate of #315
