### ISSUE TITLE
Remote transmission server access

### ISSUE THREAD

**Issue by Skawtnyc** [XITRIX/iTorrent#333]
I don’t suppose there’s any chance of having the option to have remote control of a transmission server with a mobile Safari extension for one-click magnet adding? The iOS shortcuts that used to work via share sheet no longer function properly (probably started with one of the recent iOS 18 beta releases).

**Comment by officiallor** [comment]
I don't know if I understood your question but this could help https://github.com/6c65726f79/Transmissionic

**Comment by Skawtnyc** [comment]
> I don't know if I understood your question but this could help https://github.com/6c65726f79/Transmissionic

Unfortunately no. Remote management isn’t the issue, it’s being able to add torrents and/or magnet links to the transmission server on my NAS by clicking on a torrent/magnet link in the Safari browser on my iPad/iPhone. I also have iTorrent on my devices, but I prefer to save that for when I’m not home and using a VPN.

**Comment by XITRIX** [comment]
Sorry, I did not understand your question at all. Could you try to rephrase it a bit, may be with some examples, please? Also, why are you mentioning transmission? iTorrent does not relate to transmission in any terms

**Comment by Skawtnyc** [comment]
> Sorry, I did not understand your question at all. Could you try to rephrase it a bit, may be with some examples, please? Also, why are you mentioning transmission? iTorrent does not relate to transmission in any terms

Sorry about that. I was looking for a way to add a torrent to my transmission server automatically by clicking on a magnet link, just like iTorrent does. I used to have an iOS shortcut that performed this task by adding a Share Sheet entry, but it seems to have broken recently. However, I did actually find an older variant that works on torrent files instead of magnet links. By long pressing on the torrent link it allows me to select Share, and then “Add Torrent”. https://workflow.is/workflows/5d7355eb9878435c84b6762e7fa7552c

My request was probably too ambitious. I was hoping for a way for iTorrent have the option of remotely controlling a transmission server, and when clicking on a magnet link it would send the RPC request to the Transmission server instead of the local iTorrent client.

**Comment by XITRIX** [comment]
I think it’s a topic about creating an another separate app, not just a feature for iTorrent 😅

**Comment by Skawtnyc** [comment]
> I think it’s a topic about creating an another separate app, not just a feature for iTorrent 😅

As I said, my request was too ambitious, and yeah, it would require either a separate app or adding functionality that would double the complexity of your app. Fortunately I found the older shortcut script that works with torrent files instead of magnet files. I originally asked because iTorrent has the ability to intercept clicking on a magnet link to send it directly to iTorrent, which is a rarity for iOS.
