### ISSUE TITLE
Sequential Download

### ISSUE THREAD

**Issue by isorropisths** [XITRIX/iTorrent#34]
Hi there, not really an issue, but are we expecting Sequential Download any time soon? This will enable opening a video we're currently downloading in Sequential Order to be opened through the Files app as the download takes place..

Thanks

**Comment by XITRIX** [comment]
I’d like to add it, but with full time job it’s a little bit difficult to find time for my own projects, so it will be as soon as possible for me

**Comment by isorropisths** [comment]
Lovely, at least it's in the plans! Good to know. Keep up, you're only one who keeps this alive!

**Comment by mygregstuff** [comment]
I support adding the feature of sequential downloads too! QbitTorrent is an open source project with sequential downloads. https://github.com/qbittorrent/qBittorrent

**Comment by XITRIX** [comment]
But... I already added it in 1.7 version...

**Comment by isorropisths** [comment]
Yea, he did add it, and it works wonders. Well done. Warning: Not all video Players support this live file change. Use VLC or nPlayer.
