### ISSUE TITLE
(Suggestion) Feature

### ISSUE THREAD

**Issue by yeet227** [XITRIX/iTorrent#341]
Could you implement in the sorting part of the application for name, size. ETC, maybe add a progress function so it sorts by percentage completed.

Just figured I'd ask, all g if you think it's a waste of time

**Comment by XITRIX** [comment]
Current sorting types are all "static", app need to sort it once and not waste CPU resources on it anymore, but sorting by progress will require app to resort everything on every progress update (several times per second) which could make app waste a lot of CPU resources for nothing, I could think if I can do anything about this (like throttle amount of updates per second) but I'm not sure for now
