### ISSUE TITLE
(Issue) Application Crashes

### ISSUE THREAD

**Issue by yeet227** [XITRIX/iTorrent#342]
So if I leave the app in the background doing it's downloading every now and again I'll open the app to chalk progress whether it's an app in the background or if I've locked the phone with the app open directly, and it will either reload the torrents up to the point it crashed, or it will crash the application and I have to open it again, to get the downloads to continue.

Some details:

Phone Type: IPhone 11
Background refresh, is enabled for the app
Power save mode: Sometimes enabled in cases to save battery, which I am aware does disable background app refresh for the duration of it being active.
App Version: latest from GitHub
iPhone Version: 17.5.1

**Comment by XITRIX** [comment]
Thanks for report, currently I have some crash reports in Crashlytics which comes from LibTorrent, but their crash logs make no sense to me, I've asked some questions in LibTorrent repo but they still unanswered.
I'll try to find the way fix such issues in future updates

**Comment by PCMasterRace8** [comment]
> Thanks for report, currently I have some crash reports in Crashlytics which comes from LibTorrent, but their crash logs make no sense to me, I've asked some questions in LibTorrent repo but they still unanswered.
> 
> I'll try to find the way fix such issues in future updates

In the last 24h the app crashed like 20 times !!!!
What's going on 
15PM 
18.1.1

**Comment by XITRIX** [comment]
Improvement work was done in release 2.0.13
Now background download should work more stable
