### ISSUE TITLE
cant download .torrent file

### ISSUE THREAD

**Issue by 78ltephem** [XITRIX/iTorrent#343]
i try to click on .torrent files on iphone 15 and nothing happens and #315 solution does not work

**Comment by XITRIX** [comment]
It could happen if you installed app using dev certificate (not with AltStore). iOS sandboxing protection will work incorrectly with apps installed this way, and the only workaround is to use build from issue you've attached and add .torrent files from the app itself ('+' -> 'Add from Files')
The only "real" solution is to install app with AltStore or any other sideloading tool that use your AppleID account to sign the app

**Comment by thefakesound** [comment]
На самом деле, так тоже не работает. Я в последней версии вообще никак не смог добавить торрент, все способы - ноль реакции. В старой с яркой красной иконкой - норм. Установка с аппдб

**Comment by XITRIX** [comment]
Should be partially fixed in v2.0.11
