### ISSUE TITLE
(Feature request) Support for adding list of github public BitTorrent trackers

### ISSUE THREAD

**Issue by Saber-CC** [XITRIX/iTorrent#345]
I like iTorrent, it's great but it has a few small drawbacks for my area
This feature can greatly improve my download experience, as the BitTorrent download tool I use on my PC can easily import both items, updated daily, so my download experience is very good and I can quickly communicate with the tracker server. However, when I used iTorrent on iOS, I often couldn't communicate with the trackers that came with Torrents, causing the download speed to be stuck at 0kb/s and unable to download. If I can import the trackers of these two projects, I think my download experience will be greatly improved. Thanks
For example,I can add the following two github project trackers
https://github.com/ngosang/trackerslist
https://github.com/XIU2/TrackersListCollection
This is a screenshot of the BitTorrent download tool on my PC, maybe it will help you
<img width="705" alt="image" src="https://github.com/user-attachments/assets/b2d47642-0c29-4d0b-8a29-027f581ce28e">

**Comment by XITRIX** [comment]
It's a really nice feature to implement, I'll definitely try to implement it when I'll have some time

**Comment by XITRIX** [comment]
Feature was implemented in v2.0.11
You can find it in Preferences -> Trackers sources
