### ISSUE TITLE
iTorrent Does Not Work on Background

### ISSUE THREAD

**Issue by rom-19** [XITRIX/iTorrent#346]
When I leave iTorrent on background it does not keep working. Sometimes it closes itself immediatly and sometimes after several minutes. Older versions that I used dont have that issue. 

iPad Pro 2022
iOS 18.0

**Comment by ssobii2** [comment]
I am still using older version for this reason 😅 but the new version also has bugs for me like it does not work with magnet urls and doesn't let me add download torrent files as well 😅

**Comment by XITRIX** [comment]
@ssobii2, issues you described has nothing to do with app itself, 99% that you installed it using thirdparty dev certificate, this installation method breaks app's sandbox and not allow iOS to properly send torrent files to the app

**Comment by XITRIX** [comment]
@rommel4r, the way how background mode works is an enormous hack in iOS to make it possible to run app in background and show Life Activity. 
Probably I need to make possible to disable Life Activity because it should make background mode more stable

**Comment by XITRIX** [comment]
Should be fixed in 2.0.13
