### ISSUE TITLE
iTorrent folder not showing in Files app

### ISSUE THREAD

**Issue by ssobii2** [XITRIX/iTorrent#347]
Ok after I updated to ios 18, the folder just disappeared but I already had downloaded stuff and they were using the storage as seen from the iPhone Storage section. Before ios 18 it was working fine. Also, I am using older version of the app because for me the latest version didn’t worked with magnet urls, and also when you download the torrent and add it, that also does not work, it just does nothing so I just kept using older version.
![IMG_7021](https://github.com/user-attachments/assets/c5ef817d-274a-495b-9c8c-8f095d217be7)

**Comment by ssobii2** [comment]
One more thing, I went to the torrent details and from the share section pressed Open in Files and it showed the files, which I moved to another location, but when I went back the folder is still not there. So right now this workaround works.

**Comment by ssobii2** [comment]
One last thing is that, I downloaded and installed the latest version as well but the folder was not showing in Files for that too. Also, I installed using appDB but I don’t think that should be the cause of the problem.

**Comment by XITRIX** [comment]
Files folder issue has nothing to do about iTorrent itself, it's iOS issue, try to reboot your device.

Also issue with adding torrents could happen only if you installed app using thirdparty dev certificate, the only supported installation method is AltStore or anything else that uses your AppleID account to resign the app

**Comment by ssobii2** [comment]
> Files folder issue has nothing to do about iTorrent itself, it's iOS issue, try to reboot your device.
> 
> Also issue with adding torrents could happen only if you installed app using thirdparty dev certificate, the only supported installation method is AltStore or anything else that uses your AppleID account to resign the app

Already tried rebooting but didn’t worked

**Comment by XITRIX** [comment]
Just to proof that it's not iTorrent issue, I have both iTorrent apps (legacy and v2) installed and I see them both in Files app list, I'm on iOS 18.1 beta 4

![IMG_4830](https://github.com/user-attachments/assets/613276e7-fd13-4653-8d87-e6c0caf5636b)

**Comment by gotzlotz** [comment]
It might be how iTorrent is installed. I notice that the files app acts differently when you compile it yourself or install the ipa.

**Comment by ssobii2** [comment]
> Just to proof that it's not iTorrent issue, I have both iTorrent apps (legacy and v2) installed and I see them both in Files app list, I'm on iOS 18.1 beta 4
> 
> ![IMG_4830](https://private-user-images.githubusercontent.com/9553519/369687710-613276e7-fd13-4653-8d87-e6c0caf5636b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjUxMjQsIm5iZiI6MTcyNzAyNDgyNCwicGF0aCI6Ii85NTUzNTE5LzM2OTY4NzcxMC02MTMyNzZlNy1mZDEzLTQ2NTMtOGQ4Ny1lNmMwY2FmNTYzNmIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTcwNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzAwZTcxYzYwNjYyYzI0ZTAwYjQxN2NhOWQ1OWE2M2ZkMTRiZDRmYjYwM2NiYjk2MTg2Njc5MDJiZTMyMGY2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hGxVTMGS5PmuuNggwf2w4L8bLuLh9qIusxXr46bCZYY)

I see you using sidestore. Does it require one time setup from pc and never again?

**Comment by ssobii2** [comment]
@XITRIX Hey, I used sidestore and now the folder is showing so I am closing the issue. Thanks for replying :)
