### ISSUE TITLE
Torrent file adding not working on iOS 13 Beta; stuck on Obtaining Metadata on Magnets

### ISSUE THREAD

**Issue by MickeyKieu** [XITRIX/iTorrent#35]
Cannot download torrents using Torrent files from Files or after they were downloaded on Safari. (Trying to download from a private site that doesn’t have magnets.)

Also stuck on Obtaining Metadata on magnet files (with 1k+ seeders).

**Comment by XITRIX** [comment]
Can you pin this torrent file and magnet link to test? 
Also app works on my iPhone 8 Plus and iPad Pro 10’ with iOS 13, but with broken dark theme. I already fixed it, and will publish update soon

**Comment by LampPrinter** [comment]
Same issue. If I open a magnet link in safari, then the download works fine though. 
But opening a .torrent file from files app does nothing. Just opens the app. Torrent is not added.

**Comment by XITRIX** [comment]
If you have Mac, you can build “Dev” branch by yourself, otherwise just wait for final release with fixes

**Comment by LampPrinter** [comment]
> If you have Mac, you can build “Dev” branch by yourself, otherwise just wait for final release with fixes

Just providing feedback. I will wait for your release :).

**Comment by gotzlotz** [comment]
Do you have to have Xcode 11 to build?

**Comment by XITRIX** [comment]
Yes, I used some new iOS13 apis to fix theme problems, so you must build dev branch with XCode 11

**Comment by gotzlotz** [comment]
Just Build it with Xcode 11. its crashes on opening.

**Comment by XITRIX** [comment]
Don’t know, iPad Pro 10’, iPhone 8 Plus, both on ios13, works fine, no crashes.
Maybe you can attach any logs?

**Comment by gotzlotz** [comment]
I have iPhone X . Been trying to build for a couple of hours now. How to send logs?

**Comment by XITRIX** [comment]
Do you build Dev branch?
On running app, XCode should attach debugger to your iPhone, so on crash it should show you a crash log, send it here.
Or anyway I’ll release new version in several days, so you can wait a bit

**Comment by gotzlotz** [comment]
Is this it?
[Blank.pdf](https://github.com/XITRIX/iTorrent/files/3303214/Blank.pdf)

**Comment by XITRIX** [comment]
Yes, it is, but I cannot understand anything in it, just wait for final release :D

**Comment by gotzlotz** [comment]
Is there an eta on the release?

**Comment by gotzlotz** [comment]
Tried the resent dev build. same problem.

**Comment by LeoBwell** [comment]
Yeah, just tried downloading a torrent on iOS 13 Public Beta. No luck at all. Torrent will not send to iTorrent. Will this be able to be fixed? I’ve heard iOS 13 moving forward will be jailbreak proof. Maybe this is part of that new security. I can’t get it to open at all.

**Comment by XITRIX** [comment]
I see, after I reinstalled an app, I got this problem too.
An error message: 
Error Domain=NSCocoaErrorDomain Code=257 "Не удалось открыть файл, так как у Вас нет разрешения на его просмотр." resolving bookmark fileprovider:com.apple.FileProvider.LocalStorage/did=2870 
it tells that "Cannot open file. You have no permissions to view it"
Google tells nothing about it, so I don't know what to do now, but magnets work fine.

**Comment by XITRIX** [comment]
And no, iTorrent have nothing similar with jailbreak, it just an app like another 1M apps in App Store, so it could be because they added some more security levels in file opening process, or something else. Anyway it could be fixed, but now, I don't know how :(

**Comment by sharksharkk** [comment]
> And no, iTorrent have nothing similar with jailbreak, it just an app like another 1M apps in App Store, so it could be because they added some more security levels in file opening process, or something else. Anyway it could be fixed, but now, I don't know how :(

If you use the Chrome app to download the .torrent file and choose “Open In” and select iTorrent, this will work. However this will not work from Safari (it will no longer even download the .torrent file on beta 3), nor will it work if you save to Files app and then try to open in iTorrent. Tested on iPadOS 13b3.

**Comment by gotzlotz** [comment]
I’ve notice when I can get it to show up in the share sheet and it say “Copy to iTorrent” it work. Not sure how to get it in there permanently. Hope that help some out.

**Comment by XITRIX** [comment]
Same thing when I try to open MKV video in VLC, if it says “copy to VLC”, nothing happens, but sometimes, it says “open in VLC”, and then it works well, so I think it could be a bug

**Comment by gotzlotz** [comment]
Any luck on getting the open to/copy to working? Also, still having trouble building the app. I tried the most resent Dev build and still crashes on launch.
[Log.docx](https://github.com/XITRIX/iTorrent/files/3413457/Log.docx)

**Comment by XITRIX** [comment]
No, nothing.
The only workaround is to use Google Chrome, it could successfully open torrent file in iTorrent.

**Comment by gotzlotz** [comment]
I use 2 signing services. Appdb and iPAWiND. When I install with iPAWiND It installs it and changes it to copy to in share sheet and able to open torrent files from the download manager and files app. Not sure why it works. But it won’t open magnet links.

**Comment by XITRIX** [comment]
It’s strange, cause the only thing which works for me are magnets and torrent files from chrome, I’ll check your idea with iPAWiND, but I still think that it is an iOS 13 bug, and it will be ok in the final release of iOS

**Comment by sharksharkk** [comment]
> It’s strange, cause the only thing which works for me are magnets and torrent files from chrome, I’ll check your idea with iPAWiND, but I still think that it is an iOS 13 bug, and it will be ok in the final release of iOS

Can you give iTorrent the option to open torrent file from Files app?
Right now it only has open from magnet and URL. This would be really helpful. Thanks.

**Comment by XITRIX** [comment]
iOS 13 beta 6, reinstalled app from scratch, files starts to open without any problems, as I thought, it was an iOS bug.
Also added filepicker inside the app.

**Comment by sharksharkk** [comment]
Thank you
