### ISSUE TITLE
How to compile? Error 'boost/config.hpp' file not found

### ISSUE THREAD

**Issue by matti157** [XITRIX/iTorrent#350]
Cloned the repository, configured the parameters for signing, but when I compile it goes to error because it can't find the boost/config.hpp file

Error at line of code “#include <boost/config.hpp>” inside export.hpp

There is a building guide? I use Xcode 16

**Comment by XITRIX** [comment]
You need to install Boost and OpenSSL:
`brew install boost openssl`

Then run:
`./submodules/LibTorrent-Swift/make.sh`

Now you can try building app

**Comment by Skawtnyc** [comment]
> You need to install Boost and OpenSSL: `brew install boost openssl`
> 
> Then run: `./submodules/LibTorrent-Swift/make.sh`
> 
> Now you can try building app

I see there is an ios.yml file in the workflow directory, but it doesn’t activate when I try to run it. Is there any way to get that working so we could run a compile process within GitHub itself if we fork the repository?

**Comment by XITRIX** [comment]
Workflow contains a lot of "Secrets" so you'll need to set them up for yourself as well (certificates, provision profiles, appstore connect key, etc).
Also in current state it runs only on tag push, you'll probably need to modify it first

**Comment by Skawtnyc** [comment]
> Workflow contains a lot of "Secrets" so you'll need to set them up for yourself as well (certificates, provision profiles, appstore connect key, etc). Also in current state it runs only on tag push, you'll probably need to modify it first

That’s probably a lot more involved than I want to get. The app works fine for me right now even on iOS 18.1b5, so I can wait until your next compile/release cycle.

**Comment by XITRIX** [comment]
I'll close this issue, feel free to reopen if needed

**Comment by takasurazeem** [comment]
Hi,

I tried running the make.sh file and I get the error below, is there by chance a missing file?

```CMake Error: The source directory "/iTorrent/submodules/LibTorrent-Swift/Thirdparty/libtorrent" does not appear to contain CMakeLists.txt.```

**Comment by XITRIX** [comment]
you need to clone submodules as well
