### ISSUE TITLE
Disable screen dimming when application is open

### ISSUE THREAD

**Issue by puddingsoda** [XITRIX/iTorrent#357]
I think disabling screen dimming would be useful as an option when the app is open. Reason being that turning off the screen will likely stop longer torrents from downloading.

**Comment by MinhThanh03** [comment]
Hi
"Keep the screen on" would be a great feature in some cases.
But for now, you can turn off "Auto-Lock" in Settings if you really need it.
- Go to Settings -> Display & Brightness -> Auto-Lock -> change to Never.
- Don't forget to change it back after you done.
Thank you.

**Comment by XITRIX** [comment]
It's workaround, not a solution. I'll do my best to fix background downloading, not creating hacks for it
