### ISSUE TITLE
一直在获取元数据怎么办

### ISSUE THREAD

**Issue by evei0402** [XITRIX/iTorrent#358]

**Comment by MinhThanh03** [comment]
Hi.
Can you give more details or screenshots what issue did you get?
Thank you.

**Comment by evei0402** [comment]
![image](https://github.com/user-attachments/assets/c206eb22-8af0-4a5d-8e62-6cdd70e9fe70)

**Comment by evei0402** [comment]
一直这个状态是什么原因

**Comment by XITRIX** [comment]
As I can see on your screenshot, you are using 5G connection.
By default iTorrent avoid using Cellular connection, you can change it in `Preferences -> Network Settings -> Interfaces -> Cellular` and enable the toggle there

**Comment by XITRIX** [comment]
I'll close this issue, if you'll have any questions, feel free to reopen it
