### ISSUE TITLE
can you help me use your framework?

### ISSUE THREAD

**Issue by chenpark** [XITRIX/iTorrent#36]
hi,XITRIX,.I want to use my itorrent.framework to write a demo. After I put it into my project, it compiles successfully. Unfortunately, I can't use the method in itorrent.framework. Always prompt method not found. May I ask what I need to configure in xcode? Thank you very much, I hope you can reply to me.

**Comment by chenpark** [comment]
sorry， its ：Always prompt method not found

**Comment by XITRIX** [comment]
So, do you mean that you want to use my itorrent.framefork in your demo project? Or you made some changes in it, and cannot see them?

**Comment by chenpark** [comment]
yes，I put your framework file into my project, there is no problem compiling, but I can't use the methods in your framework.May I ask what I need to configure in xcode?

**Comment by XITRIX** [comment]
You need to add iTorrent-Bridging-Header.h into build settings in your project like here:
<img width="814" alt="Снимок экрана 2019-06-11 в 21 55 30" src="https://user-images.githubusercontent.com/9553519/59298765-db5e9200-8c93-11e9-9a4b-129ecab4ac95.png">

**Comment by chenpark** [comment]
Thank you very much for your help, now I can use your framework perfectly.




------------------ 原始邮件 ------------------
发件人: "Vinogradov Daniil"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 凌晨2:57
收件人: "XITRIX/iTorrent"<iTorrent@noreply.github.com>;
抄送: "风之伤陈攀）"<1120627616@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [XITRIX/iTorrent] can you help me use your framework? (#36)




You need to add iTorrent-Bridging-Header.h into build settings in your project like here:
