### ISSUE TITLE
Use default port not working as expected

### ISSUE THREAD

**Issue by officiallor** [XITRIX/iTorrent#361]
When you set an alternative port by disabling the "Use default port" option and then enable "Use default port", it keeps using the port that you previously set and not 6881.
I tried this without re-launching the app. It might have the correct behavior once you reopen it.

v2.0.11-3

**Comment by XITRIX** [comment]
I checked, you are right. Enabling "Use default port" do not update Core with correct setting. I'll try to fix it asap

**Comment by XITRIX** [comment]
Fixed in v2.0.12
