### ISSUE TITLE
Question on parallel downloading. 

### ISSUE THREAD

**Issue by Lolagatorade** [XITRIX/iTorrent#362]
“Parallel connection could increase download speed, but will leak your IP address in case of using VPN.“

does this mean the use of a VPN defeats the purpose of anonymity? Does the ISP see what you are downloading ect? It’s confusing and should elaborate… 

it’s confusing as to what’s leaking the devices ip? Not the spoofed one from the vpn? 

Would be nice to have manual on GitHub or better examination otherwise this setting would be a permanent off for me but I turn it on assuming I M protected  by the vpn

**Comment by XITRIX** [comment]
Parallel connection means that you will allow iTorrent to use all networking interfaces available on you device. That means that even if you have VPN connected, iTorrent will use both interfaces - direct WiFi AND VPN (and Cellular as well, if you'll allow it).
