### ISSUE TITLE
Unable to add Trackers sources

### ISSUE THREAD

**Issue by senina4** [XITRIX/iTorrent#363]
```
Using IPad (9 Gen).
IPadOS version: 17.6.1
ITorrent version: v2.0.12-1
Using LiveContainer to run iTorrent.
```
Video: https://github.com/user-attachments/assets/5f74d5b5-b0a5-4231-8430-afb2d4f0f73d

**Comment by XITRIX** [comment]
It's not what you suppose to do. "Remote source" is a txt file with list of trackers urls inside. To manually add tracker URL, you need to create "Local source" and add it there

**Comment by senina4** [comment]
> It's not what you suppose to do. "Remote source" is a txt file with list of trackers urls inside. To manually add tracker URL, you need to create "Local source" and add it there

Sorry I am new to torrent.

**Comment by XITRIX** [comment]
No problem at all! Not every torrent client has such feature, if need any help you are free to ask
