### ISSUE TITLE
Opening torrent files

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#38]
1.7 wont open torrent files from safari download manager in iOS 13.

**Comment by XITRIX** [comment]
iOS 13 beta 6, reinstalled app from scratch, files starts to open without any problems, as I thought, it was an iOS bug

**Comment by gotzlotz** [comment]
Mine still don’t open.

**Comment by XITRIX** [comment]
It’s strange, my iPad also had this problem, but yesterday, I reinstalled iTorrent, and file import start to work
