### ISSUE TITLE
Downloads limits 

### ISSUE THREAD

**Issue by BrownXx** [XITRIX/iTorrent#39]
Could u add limit for files .. its keep on downloading any file i add .. but gonna be useful if u set some limits .. thx btw :)

**Comment by mygregstuff** [comment]
Could you add 0kb/s download limit? I often use a VPN, however, peer discovery works much better without a VPN. I would like to throttle my downloads to zero while adding peers and then connected to my VPN. is there another way this can be done without download limits?

**Comment by XITRIX** [comment]
Zero limit equals to no limit, so technically, it already is :)
But really I don’t know if I can suggest you something in your situation, does you have some flaws if files downloads without VPN? Is FBI watching you? :)

**Comment by BrownXx** [comment]
Man could u plz just add how many torrents to start in same time ..

**Comment by XITRIX** [comment]
Ok, I think I’ll add it
