### ISSUE TITLE
Git cruft removal

### ISSUE THREAD

**Issue by ideologysec** [XITRIX/iTorrent#4]
Hello! I love iTorrent, and I've been downloading it to learn Swift and help improve an app that I use fairly often. I've submitted a pull request to update the gitignore and remove a dependency (I'm not a fan of podfiles), but I can't rewrite your git history. Please consider rewriting your repo information to remove the Pods, Podfile.lock, and .DS_Store files, using something like this:

```
# Make a fresh clone of YOUR_REPO
git clone YOUR_REPO
cd YOUR_REPO

# Create tracking branches of all branches
for remote in `git branch -r | grep -v /HEAD`; do git checkout --track $remote ; done

# Remove DIRECTORY_NAME from all commits, then remove the refs to the old commits
# (repeat these two commands for as many directories that you want to remove)
git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch DIRECTORY_NAME/' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d

# Ensure all old refs are fully removed
rm -Rf .git/logs .git/refs/original

# Perform a garbage collection to remove commits with no refs
git gc --prune=all --aggressive

# Force push all branches to overwrite their history
# (use with caution!)
git push origin --all --force
git push origin --tags --force
```

**Comment by XITRIX** [comment]
Thanks for the instructions, but I am not a pro in Git, so I think it is a little bit dangerous for me to use this commands, so at first I'll experiment with them, and after that I'll use them on that project
