### ISSUE TITLE
Не скачиваются торренты. Помоги)

### ISSUE THREAD

**Issue by ezikk** [XITRIX/iTorrent#40]
Привет, при загрузке торрентов с любых сайтов у меня всегда одна и та же проблема. Прикрепил скриншот. Пробовал скачивать на Айпад Аир, и на айфон 7+, везде одинаково. На обоих iOS 12.3.1. Непосредственно скриншот - https://imgur.com/a/ZKwKzQU

**Comment by XITRIX** [comment]
Привет, скачал этот же торрент, действительно не загружает, в трекерах находится единственный трекер и пишет что он не активен, однако скачал торрент со вторым сезоном ванпанча и он начал загрузку, хотя так же имеет только один неработающий трекер.
Попробую понять почему именно его не качает «хотя для начала проверю, качается ли он вообще через какой нибудь utorrent».
Всегда качаю с анилибрии, на ней ни один торрент не заедал))

**Comment by ezikk** [comment]
> Привет, скачал этот же торрент, действительно не загружает, в трекерах находится единственный трекер и пишет что он не активен, однако скачал торрент со вторым сезоном ванпанча и он начал загрузку, хотя так же имеет только один неработающий трекер.
> Попробую понять почему именно его не качает «хотя для начала проверю, качается ли он вообще через какой нибудь utorrent».
> Всегда качаю с анилибрии, на ней ни один торрент не заедал))

о, с анилибрии качается) Спасибо))
