### ISSUE TITLE
Overall ratio 

### ISSUE THREAD

**Issue by Zombiekat** [XITRIX/iTorrent#42]
https://imgur.com/a/5XDFrX8

Hello sir, Most important thing thank you for your contribution/work. Very glad individual developers, volunteers who working on open source projects without ads, trackers, data mining. I’ve been using your app for long time, glad that you added features, compatibility and keeping it up to date. And this is all for free. Truly great full. 
Issue: As you can see from the screenshots, how the upload and download amount calculated is little different. When we use the app the amount of data that downloaded and uploaded in that session is calculated (screenshot 1). Once we close and reopen the app the downloaded and uploaded amount is again counted from zero (screenshot 2). In this process we lose how much total amount of data we uploaded and we lose overall ratio of the torrent. 
  If you can’t understand, there is this app called transmission (screenshot 3), in this app download is total amount of data that has been downloaded. Upload data is total amount of data that has been uploaded. They aren’t calculated per session. There are total amount of upload and download data on that torrent, please add ratio tab too. 
     Sorry for my English, thank you.

**Comment by XITRIX** [comment]
Hello, thank you for your remarks, I know that this info calculates a little bit wrong.
As the core of this app I am using libtorrent, whom calculates it by himself, and I don’ know why it is not saving this status in fastresume data set.
I think I’ll try to fix it in the future, but now I have no idea how to do it.
Also if I’ll fix it, I’ll add ratio info too!)

**Comment by Zombiekat** [comment]
https://imgur.com/a/Xw5Meyb

Thank you for your reply, don’t want to annoy you but just wanted to let you know these small other things I noticed. 
 Torrents from this specific website (rarbg) always stalls at zero (screenshot 1). Screenshot 2 is how it’s showing it’s tracker list. When we add another torrent from another website it downloads perfectly. Then if we resume the first one it downloads perfectly fine. Screenshot 3 is torrent from another website, screenshot 4 is its tracker list. 
 If I disable state sections, there’s a small space left in between header and torrents. 
 Status bar in dark mode is not visible. iOS 12.4, iPhone 5s.

**Comment by XITRIX** [comment]
Thank you, have not noticed about header without sections, never disabled it after it was implemented:)
Status bar was killed when I adopted it to ios 13, already fixed it on my local build. I will publish it soon.
About downloading... I cannot tell you anything about it, cause I am also don’t know what is going on, I hope it will be fixed when I’ll update libtorrent to the latest version

**Comment by Zombiekat** [comment]
We’re counting on you CAP.  You’re only one who keeps this alive.
