### ISSUE TITLE
iOS 13 Public beta 5 Persistent Hashing

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#43]
After upgrading to iOS 13 Public beta 5, iTorrent only works while the app is open. Once closed and reopened (after a few minutes,) everything starts hashing again. I hope after this is resolved, the incoming call hashing issue is fixed too. Thanks!

iTorrent 1.6.1, iPhone 7 Plus, iOS 13 Public beta 5

**Comment by XITRIX** [comment]
Fixed in 1.7.3
