### ISSUE TITLE
1.7.2 Update Causing New Issues

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#46]
I installed 1.7.2 and here are some new issues that happened as a result:

Whenever I start a new torrent, I save the (torrent) file in case I need to delete/upgrade iTorrent and start over without remembering and compiling all the files again. When I upgraded to 1.7.2, I can no longer export torrent files from Dropbox to iTorrent (iTorrent no longer appears *anywhere* after selecting Export on a file in Dropbox).

Now for no apparent reason, Seeders and Peers (of all torrents running), go from many to zero. Sometimes when I open a file to check the status (of Seeders/Peers), they drop to zero while the window open—sometimes right away, sometimes after a while, and sometimes not at all (they sometimes zero out from the front page too).

Btw, currently I have to click on MORE/Files to see how many Seeders/Peers there are. It would be nice to see that info on the front page with a sort option showing how much time is left to finish (I always used this option on Mac clients).

I will be adding issues individually as we discussed, but for now I wanted to get these to you right away.

Thanks for the great upgrade!

iTorrent 1.7.2, iPhone 7 Plus, iOS 13 Public beta 6

**Comment by XITRIX** [comment]
Don't know why, but 1.7.2 was really broken, now I'm working on new version with updated core libs, now I'll spend much more time for testing before release it

**Comment by XITRIX** [comment]
Version 1.7.3 was released, a lot of bugs were fixed
