### ISSUE TITLE
1.7.2: File size is always 1024mb when adding torrent

### ISSUE THREAD

**Issue by fomalsd** [XITRIX/iTorrent#47]
When opening a torrent and file picker pops up, almost all files look like they are 1024mb, even though they're not (total size counter at the bottom confirms that)
Tested on 1.7.2, iPadOS 13.0 17A5565b
![RPReplay_Final1566579964 2019-08-23 20_10_42](https://user-images.githubusercontent.com/10403536/63610413-1cebb180-c5e2-11e9-9c84-f65f0de65751.gif)

**Comment by XITRIX** [comment]
Yes, somehow I broke it, thanks for report, I’ll fix it

**Comment by XITRIX** [comment]
Oh god, I know, I forgot to bind a real data to it, “1024 mb” is just a placeholder...

**Comment by XITRIX** [comment]
Fixed in dev branch
