### ISSUE TITLE
Не могу импортировать торрент файл.

### ISSUE THREAD

**Issue by kotusenka** [XITRIX/iTorrent#49]
На предыдущей версии все работало даже из сафари, сейчас просто напросто не могу ничего сделать.
Добавляя по ссылке торрент не скачивается, а размер файлов неправильный.
Заранее спасибо!
IPhone XS Max, IOS 12.4.1

**Comment by XITRIX** [comment]
Про то что торрент не добавляется на ios 12 я слышу впервые, даже не знаю что тут сказать.
Некоторые торренты действительно не скачиваются, советую попробовать другой трекер.
Неверный размер файлов при добавлении - это баг, он уже исправлен в Dev ветке.

**Comment by kotusenka** [comment]
Они впринципе не добавляются, любые

**Comment by kotusenka** [comment]
Могу прислать видео в мессенджер, куда удобно?

**Comment by fomalsd** [comment]
Вероятно, речь про то же, что было описано в #45
Но у меня не воспроизводится, т.к. я не ставил ipa через Impactor, а собирал сам

**Comment by kotusenka** [comment]
Я устанавливал через appvalley, так как нахожусь за бугром и не имею доступа к пк.

**Comment by XITRIX** [comment]
Пришли пожалуйста видео в telegram
@XITRIX

**Comment by anabios99** [comment]
Такая же проблема, телефон xs, ios 13, в меню поделиться просто нет иконки вашего приложения, соответсвенно добавить файл не получается, через магнитную ссылку добавить удалось, но загрузка не началась.  Немного дополню, спустя пару часов удалось добавить пару торрентов за загрузку через ссылки, но через файлы и через сам сафари не выходит, как описано выше.

**Comment by XITRIX** [comment]
Знаю об этой проблеме, в ближайшее время выпущу обновление с кучей исправлений

**Comment by anabios99** [comment]
Кстати, если торрент файл переместить в папку конфиг то при старте программы, он автоматом начнёт скачиваться, но когда из приложения выходишь дальше не качает пока снова не зайдёшь.

**Comment by kalantar28** [comment]
А приблизительно когда выйдет обновление?

**Comment by XITRIX** [comment]
Обновление будет в ближайшее время, однако в нём не будет исправления импорта файла, так как я пока не понял как это можно исправить.
Проблема импорта файла - в переподписи приложения. Если собрать приложение с сертификатом для своего устройства и установить, всё будет работать, но если установить ipa через импактор, то ios 13 будет запрещать ему доступ к внешним файлам, так что единственный выход какой я вижу на данный момент, создать мне корпоративный аккаунт и распространять приложение через него, однако приложение не приносит достаточно денег, что бы данная затея полностью окупила себя и я попросту могу уйти в минус

**Comment by XITRIX** [comment]
Версия 1.7.3 релизнута, множество багов исправлено

**Comment by kalantar28** [comment]
Большое спасибо. Вы молодец👍🏻
