### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ideologysec** [XITRIX/iTorrent#5]
I'de love to implement a dark/black mode for iTorrent; I don't know what's on your roadmap, but I've started adding custom code to all the view controllers to autoswitch (and it will use true black on iPhone X, which I'm detecting using screensize).

If you've already started this, great! Please let me know, so we don't duplicate effort.

**Comment by XITRIX** [comment]
No, now I am implementing sorting files by directories in file viewers, so It will be great if you'll add an option to switch theme on dark one.

**Comment by ideologysec** [comment]
I'm working on this (though not for the next few days), but I have to teach myself how UI ControllerView and UIColor work in the process, so it might be fairly slow going.

**Comment by XITRIX** [comment]
Hello, there was nothing to do for me today, and I tried to do a dark theme, and ... I have done it on 90%...
![img_88c801d8c66c-1](https://user-images.githubusercontent.com/9553519/41823916-2ce90e6e-7810-11e8-8abd-b019f6930dde.jpeg)

**Comment by ideologysec** [comment]
Very nice! Sorry it took me so long. :)

**Comment by XITRIX** [comment]
Function has been implemented in Release 1.4

**Comment by XITRIX** [comment]
Check it please, does it works correctly at all

**Comment by ideologysec** [comment]
I can't build it; I'm having this issue:
https://forums.developer.apple.com/thread/103670

I can't really run Mojave even for testing - it would be great to revert to having this build on Xcode 9.4.1, since it's at least decently well tested (but the Iterator class, etc, aren't available in < Swift 4.2)

**Comment by XITRIX** [comment]
But I already implemented one feature from swift 4.2, so it is impossible now to build it in Xcode 9.
At first I tried to install XCode 10 on new Mojave Beta, but I easily installed it also on my PC with High Sierra
