### ISSUE TITLE
ios 13.1 beta 2 break backgrounding

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#50]
Just updated to 13.1 beta 2 and this is the first thing I checked. It doesn’t run in the background when I swipe out the app.

**Comment by XITRIX** [comment]
When you swipe it out from multitasking?

**Comment by gotzlotz** [comment]
Nope, when I minimize. I have a iPhone X so I swipe from the bottom to go to the home screen and when I open it back up hash checks it.

**Comment by gotzlotz** [comment]
[](url)

**Comment by gotzlotz** [comment]
https://www.dropbox.com/s/h946dxhlgiws0cm/RPReplay_Final1567621545.MP4?dl=0

**Comment by XITRIX** [comment]
Oh, I see.
A lot of weird bugs appears in the last versions.
Now I’m working on a new version, which hopefully will fix most of that bugs. Also I’ve updated versions of all core frameworks, so hope it will work much more stable than now...

**Comment by XITRIX** [comment]
Updated my device to beta 2, sure, app crashes on reopen. On beta 1 it was ok.
I’ll try to find a reason of it to fix

**Comment by gotzlotz** [comment]
UPDATE. Just use the latest dev build and backgrounding works and I got open from safari and files app working. but only when building with Xcode. if I side load it, I backgrounding and opening don't work. iOS 13.1 beta 3

**Comment by XITRIX** [comment]
Yes, I fixed backgrounding in dev branch. But where you can side load latest dev build? Backgrounding should work in any way, cause it was bug in a code which I fixed.
Files opening works if app was installed using XCode, don't know about any other ways of install

**Comment by Davoncci** [comment]
The app is literally unusable on iOS 13.1 as the background downloading is broken.

**Comment by XITRIX** [comment]
Dev branch contains all the fixes, I will release it, when it will be finished

**Comment by XITRIX** [comment]
Fixed in 1.7.3
