### ISSUE TITLE
Add .torrent file does not work

### ISSUE THREAD

**Issue by pirlav** [XITRIX/iTorrent#51]
I can not add .torrent file to iTorrent.
I’m using an iPad Pro 2nd gen with the last Beta of iOS 13.1

**Comment by Davoncci** [comment]
Yes...same here. I complained about this too

**Comment by petermhyung** [comment]
iPadOS 13.1.1   iPad Pro 10.5. iTorrent 1.7.2
1. Long file name with multiple full stop inside the file name string could not download.  I shortened the file name to “xxxxxx.torrent” and it successfully download a 10gb video.
2. Torrent file show downloading but no percentage proceed.  Click on the file on the Apps left panel the App crashed and quit unexpectedly.  The torrent file name and the download video file name contains Chinese characters, is it the cause of Apps iTorrent crash?
Attachment Link
https://drive.google.com/file/d/17y7H0TdFBAhVrLWOQ41uzJgjHj6UrEtT/view?usp=drivesdk 
Torrent file causes the Apps crash.  Please check what’s the problem 
Thank you

**Comment by pirlav** [comment]
Hi Petermhyung. 
Thanks for the answer. I have changed the name of my torrent file as explained. 
I can still not add it to iTorrent.
 Nothing happened.

**Comment by XITRIX** [comment]
iOS 13 prevents open files if app was resigned (by Impactor for example), you should build app by your self, if you want it work. But you can add torrents by url, or just put torrent file to _Config folder directly.

Petermhyung, thanks for information, this torrent file causes crash, I’ll try to fix it in the further updates

**Comment by pirlav** [comment]
XITRIX thanks for the follow up.
Can u tell me where and how can I access to the _config folder ? I will try this way.

**Comment by XITRIX** [comment]
Open Files app, find iTorrent folder, there should be _Config folder (if not, create it), technically it is system folder for storing already added  torrent files, but it can also be used in this way)

**Comment by pirlav** [comment]
It’s working, and perfectly !
Thank you XITRIX, and good job ;)

**Comment by XITRIX** [comment]
Petermhyung, fixed it, there was a problem with 0 bites file sizes.
Thank you for help with bugfixing :)

**Comment by ToniaDemchuk** [comment]
Still not working((( Cannot open .torrent file
IPad Air (4th generation)
IOS 14.7.1
iTorrent 1.8.3

**Comment by XITRIX** [comment]
It's the problem of incorrect application signing, if you'll compile it with xCode by yourself it will works fine

**Comment by ToniaDemchuk** [comment]
I built it with my signature, but error still occurred at this line. File name has short name with letters.
``` Swift
        guard let hash = TorrentSdk.getTorrentFileHash(torrentPath: dest) else {
            Dialog.show(title: "Error",
                        message: "Torrent file opening error has been occured")
            return
        }
```
I also tried to use file path instead of a hash, but that throwed runtime error:
```
libc++abi: terminating with uncaught exception of type boost::system::system_error: expected value (list, dict, int or string) in bencoded string
```

**Comment by XITRIX** [comment]
Could you attach this torrent file to test it by my self?
