### ISSUE TITLE
Can u please update your app in app valley it’s using 1.6.1 it has problems on ios13

### ISSUE THREAD

**Issue by banta01** [XITRIX/iTorrent#53]
Please update your app

**Comment by banta01** [comment]
I beg please update your app on app valley

**Comment by banta01** [comment]
😩

**Comment by XITRIX** [comment]
I am not responsible for uploading my app on any apps sideloading services, so I cannot update it there, all you can do, it’s find another service or download ipa file from “releases” folder and install it using impactor

**Comment by banta01** [comment]
Can u please tell with service is using the latest version

**Comment by XITRIX** [comment]
I am not using such a services, but I think Ignition.fun has latest version (but I’m not sure)
