### ISSUE TITLE
ipados

### ISSUE THREAD

**Issue by sharar82** [XITRIX/iTorrent#55]
Hi,

the app stops running in background after updating my ipad pro 12.9 to ipados

**Comment by XITRIX** [comment]
Hi, release or Dev branch?

**Comment by sharar82** [comment]
release 13.1.2 (17A860)

**Comment by XITRIX** [comment]
I mean of application

**Comment by sharar82** [comment]
I'm sorry, app version 1.7.2 that I downloaded from iBuilds store. So, I guess release?

**Comment by XITRIX** [comment]
Yes, it has broken background mode for iOS 13.1, I fixed it in Dev branch

**Comment by sharar82** [comment]
excellent, great work.
