### ISSUE TITLE
Downloads won’t start

### ISSUE THREAD

**Issue by joek1ng4312** [XITRIX/iTorrent#56]
I’m running iOS 12.4, iPhone X. Torrents don’t download, have restarted the app numerous times and re added torrent, still won’t start

**Comment by XITRIX** [comment]
Some torrents not starts, try to find on another tracker

**Comment by joek1ng4312** [comment]
Is this going to be a permanent thing? Or will eventually be fixed?



On 5/10/2019, at 9:15 PM, Vinogradov Daniil <notifications@github.com<mailto:notifications@github.com>> wrote:


Some torrents not starts, try to find on another tracker

**Comment by XITRIX** [comment]
I’m just using libtorrent library for torrent processing, so I cannot be 100% sure if it is library’s problem, or it is cause I made wrong configurations.
You can send me a link to broken torrent file, so later I could try to find the reason of his inoperability.
