### ISSUE TITLE
Background download issue

### ISSUE THREAD

**Issue by LukaszTe** [XITRIX/iTorrent#59]
Iphone 11 Pro Max, IOS 13.1.2
* Background downloading is no longer available. 
File is hashing itself once you ‚minimalize’ the apk.

Feature was unavailable since the beginning (IOS 13.0). Was working with IOS 12+ IPhone Xs Max.  The only torrent that was working in the background.. Fingers crossed! 🤞

**Comment by XITRIX** [comment]
Have you installed latest 1.7.3 version?

**Comment by LukaszTe** [comment]
Had 1.7 on my phone. Solved 👍

**Comment by abhishekprasad001** [comment]
Not fixed.

Kindly fix the issue of not downloading in background once app is minimised. Every time it starts hashing.

Checked every iTorrent version.

iPhone XS Max, iOS 13.1.3

**Comment by XITRIX** [comment]
Are you sure you have version 1.7.3?
I have no any problems with background downloading on my iPhone 8 Plus, iOS 13.1.3
