### ISSUE TITLE
Select All

### ISSUE THREAD

**Issue by ideologysec** [XITRIX/iTorrent#6]
This is a "Roadmap" ticket.

I'd like to implement an Edit button in the main view, to allow for mass selection + deletion of torrents. I have not started this; if you have, please let me know so we don't duplicate effort.

This ought to be pretty easy, just another button in the main view (on the bottom in the middle, perhaps?), that transitions to a "Select All" "Deselect All" + Checkbox list.

**Comment by XITRIX** [comment]
I think "Edit" button can be placed in left upper conner, and after click on it, edit mode of tabelview will be enabled, and also buttons in toolbar will be replaced on "Select All", "Deselect All" + "play, pause, trash bin icon"

**Comment by XITRIX** [comment]
I finished all what I wanted to do in 1.3 version, so I will implement this feature by my self

**Comment by XITRIX** [comment]
Feature has been implemented

**Comment by ideologysec** [comment]
Awesome. I'm busy the next few days, but I'll rebase my dark mode fork on this.
