### ISSUE TITLE
How to download without pc

### ISSUE THREAD

**Issue by Quackin** [XITRIX/iTorrent#60]

**Comment by Quackin** [comment]
How do i download without a pc pls tell me

**Comment by mark-rozen** [comment]
You can use tools like this [web app](https://www.diawi.com/)

**Comment by XITRIX** [comment]
I am not providing any side load solutions yet, but you can try to find such services in google, like ignition.fun or appvalley.vip
But I am not responsible for problems that may arise from using such services.
