### ISSUE TITLE
Crash after add torrent which include folder

### ISSUE THREAD

**Issue by BJJFly** [XITRIX/iTorrent#61]
after add torrent which include folder detail , then open TorrentDetails , will Crash,
have some bug in 
Files get_files_of_torrent_by_hash(const char* hash)

**Comment by XITRIX** [comment]
Can you attach that torrent file please?

**Comment by anabios99** [comment]
Как скачать новую версию ? А то устал подписки отключать, которые активирует твоё приложение

**Comment by XITRIX** [comment]
Я не понял что за подписки, но вы можете скачать новую версию из раздела “Releases”: https://github.com/XITRIX/iTorrent/releases

**Comment by anabios99** [comment]
А в эппвалли появится приложение ? Отсюда я так понимаю какой то хитрый способ установки ?

**Comment by XITRIX** [comment]
Я предоставляю лишь чистый ipa файл, для дальнейшего самостоятельного подписывания и установки. Решений по сторонней загрузке я пока что не предоставляю, хоть и имеются подобные планы на будущее.
Сервисы на подобии AppValley сами добавляют приложения в свою базу и я с ними никак не сотрудничаю. Можете попробовать обратиться к ним через обратную связь с просьбой обновить приложение.

**Comment by anabios99** [comment]
Понял, спасибо.

**Comment by anabios99** [comment]
Ещё один тупой вопрос, а есть какой либо мануал как это сделать? Вопросом просто не владею от слова совсем.

**Comment by XITRIX** [comment]
Можно в гугле найти по запросу «установка ipa на ios»

**Comment by BJJFly** [comment]
I took the last time
iTorrent.framework/iTorrent, found that the problem has been fixed
