### ISSUE TITLE
Provision problem with ipad pro 2018

### ISSUE THREAD

**Issue by saifsaif95** [XITRIX/iTorrent#63]
Hello,
I tried installing the app through Diawi.com and it says the provision dosent include my ipad UDID. So what should I do?
![30DF873B-C544-4BD3-A96A-28ED3C254132](https://user-images.githubusercontent.com/56605956/66858149-5f51bf00-ef91-11e9-84bb-789b210a9f6f.jpeg)

**Comment by XITRIX** [comment]
You should add your device's UDID to that profile using apple's developer console, or contact with person whom sold it to you. It is not the problem which I can solve.

**Comment by gotzlotz** [comment]
Where can you buy them from?
