### ISSUE TITLE
App is not downloading in background

### ISSUE THREAD

**Issue by abhishekprasad001** [XITRIX/iTorrent#64]
Not fixed.

Kindly fix the issue of not downloading in background once app is minimised. Every time it starts hashing.

Checked every iTorrent version.

iPhone XS Max, iOS 13.1.3

**Comment by XITRIX** [comment]
Are you sure you have version 1.7.3?
I have no any problems with background downloading on my iPhone 8 Plus, iOS 13.1.3

**Comment by abhishekprasad001** [comment]
Just checked again. Yes, i have iTorrent Version 1.7.3

iTorrent 1.7.3
iOS 13.1.3
iPhone XS Max

- Abhishek

**Comment by abhishekprasad001** [comment]
Sorry, i think this issue was on my side. Somehow app was not updating.

Deleted and installed again, now its working in background. ☺️

Thanks a lot 👍🏻

**Comment by XITRIX** [comment]
Haha, I’m glad to hear that. :)
