### ISSUE TITLE
[REQUEST] No upload

### ISSUE THREAD

**Issue by Maxmad68** [XITRIX/iTorrent#65]
Hi,
Could you please consider the option of adding a "0 kbps" option to the upload limit picker?
I tried to add one by myself, but the only I could have done is limiting to 1kbps (because of the 0 meaning "Unlimited") :(
Sorry for my bad english :S

**Comment by XITRIX** [comment]
Hi, I’ll check libtorrent documentation for the possibility of that option. If it is possible I’ll try to add it in next updates :)

**Comment by Maxmad68** [comment]
Hi,
Thank you for your answer,
I really hope this is something that can be done!
Have a nice evening,

**Comment by XITRIX** [comment]
Duplicate of #126
