### ISSUE TITLE
Not working with private torrent sites.

### ISSUE THREAD

**Issue by LampPrinter** [XITRIX/iTorrent#66]
I have tried Torrentleech and IPTorrents. It stays stuck on “time remaining - infinity”
Downloading from rarbg website works fine.
I am on latest iTorrent version on iOS 13.

**Comment by XITRIX** [comment]
I have no possibility to test private torrents, cause I have no any private tracker account.
If you’ll suggest any tracker with easy registration, I’ll try to check and solve that problem.

**Comment by LampPrinter** [comment]
I can send you a Torrentleech invite and you can check the problem yourself. Is there a way to send message in GitHub? Or you can just leave email here temporarily.

> I have no possibility to test private torrents, cause I have no any private tracker account.
> If you’ll suggest any tracker with easy registration, I’ll try to check and solve that problem.

**Comment by XITRIX** [comment]
I don’t think it is, so you can send it on my email:
xitrix@bk.ru

**Comment by LampPrinter** [comment]
Sent invite.

**Comment by XITRIX** [comment]
Got it!

**Comment by Jekecy** [comment]
> Got it!

Any update on this? All I use are private torrents, so this prevents me from using the app. I’ve tested a few public torrents and confirmed they perform as intended on latest iTorrent and iOS version.

**Comment by XITRIX** [comment]
Sorry, but no progress at all, unfortunately I have not enough time to carry out the necessary tests to understand the reason of that problem.
I'll try to do it as soon as I can, but not now, and again, take my apologies :(

**Comment by XITRIX** [comment]
Found and fixed the problem. Next update will support private torrents and all https connections!
![IMG_1422](https://user-images.githubusercontent.com/9553519/75617401-a969c480-5b6f-11ea-9a16-b362ff272f43.jpg)

**Comment by 141** [comment]
Glad there's an update coming, there will still be the issue on highly restrictive private sites. iTorrent seems to give it's name as a generic Libtorrent 1.2.2, or something like that. It could be in the blocklist if other bad clients use that generic name. The best way to deal with the issue is create a good reply to the client name and then get private trackers to okay the client.

**Comment by XITRIX** [comment]
Thanks for suggestion, I’ll change client name to proper one
