### ISSUE TITLE
Download won’t Start

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#67]
I’ve notice on iOS 13.2, that a torrent won’t start downloading if the app was in a suspended stat. I have to force close the app and reopen. Then it will start automatically.
Build with Xcode.

Update
All the tracker say inactive. But if I force quit and open back up they say working.

Update
It seem that it is only torrents from rarbg.to.

**Comment by gotzlotz** [comment]
Is anyone else having this problem?

**Comment by XITRIX** [comment]
Added support for https trackers, it should fix a lot of problems with downloading

**Comment by gotzlotz** [comment]
Just notice that this is still a problem. Does it on rarbg and Nyaa

**Comment by XITRIX** [comment]
Just downloaded torrent from nyaa.si. Works fine, in case it have no https trackers:
![92F42A78-8243-4C6F-AEE7-57F2C26AA689](https://user-images.githubusercontent.com/9553519/80319743-bbd44780-881a-11ea-8e67-ebcbb80a71a9.png)
![5139D2AF-7318-490D-9570-66DEFC6457D4](https://user-images.githubusercontent.com/9553519/80319747-c098fb80-881a-11ea-8f7b-c165e3ebc0d2.png)

**Comment by gotzlotz** [comment]
Tired Nyaa again and it worked but rarbg doesn’t.

**Comment by gotzlotz** [comment]
![5BEA08E1-6F0C-44DE-9D3D-DCFFFBFE22DC](https://user-images.githubusercontent.com/16293689/80320137-70de1400-87c9-11ea-9b73-208ccc84599f.png)
![8207A560-F5F3-4D06-9189-4505979F0B96](https://user-images.githubusercontent.com/16293689/80320138-750a3180-87c9-11ea-83f0-dbd3338f4738.png)

**Comment by XITRIX** [comment]
Also works, I’m in Russia, and lots of torrent trackers are blocked here, so I use VPN, may be your network also has such problems? Try to use some sort of VPN, or try to run it on PC, just to check, will it work on another torrent client
![7415978A-A213-47F0-878D-DB2766E1B95D](https://user-images.githubusercontent.com/9553519/80320469-3acb7f00-881f-11ea-85d5-5db5af52ea14.png)
![567B224B-D22D-4C87-B687-76DF489E4FC6](https://user-images.githubusercontent.com/9553519/80320471-3c954280-881f-11ea-9499-691c7e3758a7.png)

**Comment by gotzlotz** [comment]
The problem only happens when the app has been left open for 3-5 minutes. So if open the app from a closed stat it will start like normal. But if I open from a suspended or background stat it won’t start until I close the app and re open.

**Comment by XITRIX** [comment]
Ok, I'll try to figure out what is that, also, could you give me your email or any other way to contact with you?

**Comment by gotzlotz** [comment]
GotzLotz@iCloud.com
