### ISSUE TITLE
Download not working in the background

### ISSUE THREAD

**Issue by GamErik13** [XITRIX/iTorrent#69]
Hello!
I just downloaded your application and installed it by enabling it from the settings, it is on version 1.7. I am using an Ipad Pro 11 with IOS 13 and although I have background downloading enabled, anytime I open another app while leaving the torrent open it stops, because when I come back to it it says hashing. Could anyone help me, do I need to an additional something to have the background download functionality? Thanks,

**Comment by XITRIX** [comment]
Hi, of course it is not working, it was fixed for iOS 13 only in version 1.7.3

**Comment by GamErik13** [comment]
I see, could you please tell me how to download it, I see the 3 assets, but after downloading them the app does not pop up nor is there a option to enable it in the settings, thank and you and sorry for making you write down the probably obvious.

**Comment by XITRIX** [comment]
You should download .ipa file and install it using Impactor (you could find detailed instructions for it in google), if you have no access to computer, you could try to find some side load services like “ignition” or “tutuapps”, but there is no guarantee they have latest version of app
