### ISSUE TITLE
Reading downloading files

### ISSUE THREAD

**Issue by Michaelvilleneuve** [XITRIX/iTorrent#7]
Hey, thank you very muck for this app, it works wonderfully 👍 !
Just a quick question, not completely relevant to this app. I can't manage to read the downloaded file (a .mkv), do you have any suggestion on how to read it ? 

I click on the file, share it, and then I've tried : 
- vlc 
- other player
- some app to cast on tv

None seem to be able to access the file once shared.
Thanks in advance

**Comment by XITRIX** [comment]
Hi, thanks for using my app! 
I am also tried to share a video to VLC, but it does not work even from Files app, so I think it is VLC's problem. I just copied the file into VLC's folder using Files app and app sees it perfectly, but it is possible only on iOS 11 or higher (I hope you have it).
In unknown future I am planning to implement media player inside my app (may be I'll use VLC kit), but now it is the only suggestion I could to give.
Good Luck!

**Comment by ideologysec** [comment]
don't implement a media player!

Or at least if you do, offer a lighter-weight/simpler version that doesn't have it. I can understand why that would be helpful, and iTransmission did something similar, but it adds unnecessary functionality IMHO. Needless complexity and dependencies in a torrent client, which I would only use for downloading files.

**Comment by XITRIX** [comment]
Ok, if it will make app much heavier, I will refuse this idea
