### ISSUE TITLE
Background download not working 

### ISSUE THREAD

**Issue by faycaltami0916** [XITRIX/iTorrent#70]
I’m having the same issue as most of people here
Whenever i put the app in the background the app crashes everytime don't know why
I got a 6s running iOS 12.4 
And am not thinking of updating my device to iOS 13 since It’s  jailbroken 
So can you please help me with the issue or just give me a clue :/

**Comment by XITRIX** [comment]
What is the version of app you use?

**Comment by faycaltami0916** [comment]
I’m on 1.7.3

**Comment by faycaltami0916** [comment]
I just downgraded to 1.6.1 and it’s working flawlessly!
You somehow managed to break the code in later versions .

**Comment by XITRIX** [comment]
It was fixed for iOS 13, I have not checked backward compatibility, maybe it’s true that it is not working in previous iOS versions, I’ll try to check it

**Comment by rluvaton** [comment]
Model: iPhone 7
iOS Version: 13.1.3
App version: 1.7

Background downloading not working

**Comment by XITRIX** [comment]
Stop asking the same thing, latest version is 1.7.3 and ONLY on that version background downloading works with iOS 13

**Comment by rluvaton** [comment]
> Stop asking the same thing, latest version is 1.7.3 and ONLY on that version background downloading works with iOS 13

So close this issue
