### ISSUE TITLE
iTorrent 1.7.3 kills iOS devices battery capacity

### ISSUE THREAD

**Issue by MobileDeepFixFinland** [XITRIX/iTorrent#71]
The all new iTorrent 1.7.3 is drain not only battery % but killing battery life (capacity). Only with 10GB download my new iPhone XS Max has dropped from 100% to 96% capacity. Also with 15 minutes of usage with iPad Air 2 iTorrent suck the battery life (capacity) from 85,80% to 84,56%. Please stop using the new version of iTorrent 1.7.3. You have been warned!

**Comment by XITRIX** [comment]
How do you think it is possible?
Application cannot do nothing with battery capacity, battery is self destructing with time.
It is absolutely impossible to lose 1% of battery capacity because of 15 minutes using any kind of application, it could just drain it’s charge, not capacity. 
Go to Apple service and change you iPad’s dead battery!

**Comment by MobileDeepFixFinland** [comment]
Yes it is possible to poor designed individual apps to kill idevice battery capacity. Did yo read what I wrote? (My NEW iPhone XS Max AAAAND iPad Air 2. It is not that the battery is ”bad”, but it is because this iTorrent app (1.7.3) suck so much current that it indeed kills batteries. I can send video about that capacity drain only when iTorrent 1.7.3 is actively downloading. But you can use it If you want.

**Comment by MobileDeepFixFinland** [comment]
[IMG_0106.TRIM.zip](https://github.com/XITRIX/iTorrent/files/3811117/IMG_0106.TRIM.zip)

**Comment by XITRIX** [comment]
Ok, I’ll check amount of battery usage with debugging tools

**Comment by jadelazar** [comment]
If you go into iOS settings you can see your actual battery health. Try that instead. These apps can be buggy

**Comment by XITRIX** [comment]
![BF82144F-7097-46B8-935E-88AC0822FF47](https://user-images.githubusercontent.com/9553519/70446455-2b38dd00-1aae-11ea-9258-8d3e32ad2f20.png)
2,5 years old iPhone 8 Plus, using iTorrent everyday.
82% is good enough for device, which runs “battery’s killer app” for 2 years of it’s developing

**Comment by jadelazar** [comment]
Exactly. It wasn’t you who I was replying to lol but you’ve helped prove my point haha 😊

**Comment by XITRIX** [comment]
Haha, ok ;)
