### ISSUE TITLE
Trusted Wifi Networks

### ISSUE THREAD

**Issue by lonkelle** [XITRIX/iTorrent#73]
There should be a place to add a trusted network and not download or upload unless connected to it (also cellular would be its option).

**Comment by syto203** [comment]
You can restrict cellular from iOS itself; However, a notification you are on cellular might be useful though.

**Comment by lonkelle** [comment]
That's true. But I'm really trying to restrict WIFI here. Only trust certain wifi networks.

I already have iTorrent turned off in my cellular data settings so I don't use up any data. But my home network is the only network I want to "trust."

**Comment by lonkelle** [comment]
Any further looking into this since then?

**Comment by XITRIX** [comment]
Sorry, no progress.

**Comment by lonkelle** [comment]
@XITRIX What about if your app makes sure that one is on WiFi, that a VPN is turned on? That would also solve the issue. :)

**Comment by XITRIX** [comment]
Could you paraphrase it? Do you mean that app need to check if iOS connected to VPN or not?

**Comment by lonkelle** [comment]
Yes, a setting for "refuse connection if not connected to a VPN" is a huge thing for torrenting given the privacy and security implications that come with direct peer to peer connections like this protocol is. 

Basically, if that setting is on (off by default) – your code would check that your phone is connected to a VPN and looks like it's decently easy to check with a simple function, full code provided here:

https://medium.com/@alessandrofrancucci/checking-vpn-connection-on-ios-swift-9748d733e49d

**Comment by XITRIX** [comment]
Thanks for code reference, I'll try to implement such feature.
