### ISSUE TITLE
Download using cellular

### ISSUE THREAD

**Issue by jeffzainal** [XITRIX/iTorrent#74]
Hi. Currently iTorrent can only download using wifi. Can we have an option to download using cellular as well?

**Comment by XITRIX** [comment]
Hi. It is not true. I am always use cellular to download my torrents, BUT my provider forbid torrenting, so I use my own home vpn connection as workaround. 
May be your provider also have any kind of torrent blocking?

**Comment by jeffzainal** [comment]
Oh ok. Thanks for the info. I’ll try to use vpn then
