### ISSUE TITLE
iOS 13.3.1 and issue with embedded frameworks

### ISSUE THREAD

**Issue by josh-rogan** [XITRIX/iTorrent#79]
I’ve been using iTorrent with the help of [Altstore](https://altstore.io/) and there seems to be a universal bug in iOS 13.3.1 with side loading apps with non-developer IDs only if they contain embedded frameworks - they do not open. Is there a possibility of using static libraries which would help solve this issue?

**Comment by mygregstuff** [comment]
xcode errors for ios 13.3.1


dyld: Library not loaded: @rpath/FBLPromises.framework/FBLPromises
  Referenced from: /private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/iTorrent
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises: code signature invalid for '/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises'

	/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises: code signature invalid for '/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises'

	/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises: stat() failed with errno=1
	/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises: code signature invalid for '/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises'

	/private/var/containers/Bundle/Application/CD3431AD-187F-48B4-96BC-ACA5BB1E607A/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises: stat() failed with errno=1
(lldb)

**Comment by JPRosenberg** [comment]
Apparently iOS 13.3.1 broke frameworks for non-developer IDs. If you link all frameworks as static libraries (by commenting the line `use_frameworks!` in the Podfile and then `pod update`, `pod install`) a lot of the problems go away. 

Still, the iTorrent framework can't load. You can bypass the error by setting iTorrent.framework as optional but that obviously breaks the app anyway. I don't know how to load the iTorrent.framework as a static library.
