### ISSUE TITLE
Backgrounding

### ISSUE THREAD

**Issue by gotzlotz** [XITRIX/iTorrent#8]
Torrent either auto pauses or stops downloading when phone is locked. On iOS 12 with iPhone X.

**Comment by XITRIX** [comment]
![img_2853](https://user-images.githubusercontent.com/9553519/42295857-67dd2034-7ff7-11e8-934c-19e22200c9f4.PNG)
I think that crash report was from your phone, so it was not just a "pause" or "stop", app has crashed, and it crashed in C++ piece of code, so I cannot see the main reason of this crash, I have not changed this save_fast_resume functions in the last few updates, and it worked pretty well I think, so I hope that was one-time problem, that will never appears in future (of course it will)
If you'll find that problem regularity, and understand how to reproduce it, please, tell me about it and so I will fix it

**Comment by gotzlotz** [comment]
It’s seem that the download doesn’t stop it just slows down. I was happen on the 1.4.1 update also I was waiting it out to see if it was my device. 1.4 works fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by XITRIX** [comment]
If it was not crash or stop/pause, and it was just a slow down, so I don't know what to say about it, cause I implemented speed limitation only in the last update, and it applies only on app's starting and on changing that setting, so it cannot be applied on app goes to background.
I will close that issue now, but if you'll get more information about this problem, be free to reopen it

**Comment by gotzlotz** [comment]
It has something to do with iOS 12. Downgraded to 11.4 and it works fine.

**Comment by XITRIX** [comment]
I am also using iOS 12 on iPhone 8 Plus, and I have not seen any problems like that
