### ISSUE TITLE
Inbox directory inaccessible

### ISSUE THREAD

**Issue by 141** [XITRIX/iTorrent#80]
I can see the Inbox directory getting filled up with torrent files, as it appears in iTunes and I can download the contents. However the "Files" app can not see that directory and there's no way to simply clear it in the app. 

Latest version used, sideloaded on ios 12.4.4

**Comment by XITRIX** [comment]
Inbox is a system-side folder which iOS creates and uses, I can do nothing with its visibility in Files app
