### ISSUE TITLE
File download choices not saved

### ISSUE THREAD

**Issue by 141** [XITRIX/iTorrent#81]
Since I often have many torrents waiting and have selected to not download a potion of files each torrent contains, that data is not saved throughout crashes or memory kills.

**Comment by XITRIX** [comment]
I will try to come up with it, but now I have no idea, how to call save function on application crash

**Comment by XITRIX** [comment]
Solved it by simple, but stupid way, now app saves states on leaving file manager view

**Comment by 141** [comment]
Nothing needs to be saved upon a crash, just save the file selections per torrent once the file section is closed. Also make sure those selections are restored at startup. Thanks

**Comment by XITRIX** [comment]
It would be grate if it was so easy, but there is a problem, file selection stores in .fastresume file which generates by libtorrent, and if I initiate saving process while torrent in downloading state, it will stuck, so I cannot call the save method until all torrents stop

**Comment by XITRIX** [comment]
Fixed in 1.8.2
