### ISSUE TITLE
Option to turn off iCloud sync?

### ISSUE THREAD

**Issue by HAOOFE** [XITRIX/iTorrent#83]
Hi,
Thanks the great works first of all.
Just found a issue, not sure if it’s my own problem.
I’m on iPhone X, 256g, iOS version 13.3 jailbroken. Installed the latest version of iTorrent last night.

After a night downloading 10, 20g of video. My iCloud (5g default free storage) is starting to claim that there is not enough room for backing up the iPhone today.. I not sure if it because of iTorrent is syncing iCloud automatically as a default setting. However I could not find a way to turn the sync of iTorrent off..  Please have a look for me..
William

**Comment by gotzlotz** [comment]
> Hi,
> Thanks the great works first of all.
> Just found a issue, not sure if it’s my own problem.
> I’m on iPhone X, 256g, iOS version 13.3 jailbroken. Installed the latest version of iTorrent last night.
> 
> After a night downloading 10, 20g of video. My iCloud (5g default free storage) is starting to claim that there is not enough room for backing up the iPhone today.. I not sure if it because of iTorrent is syncing iCloud automatically as a default setting. However I could not find a way to turn the sync of iTorrent off..  Please have a look for me..
> William


Setting app
User/iCloud/Manage Storage/Backups/The Device

Turn off backups for iTorrent

**Comment by XITRIX** [comment]
As said @gotzlotz, you can disable it in your iCloud backup settings.
My backup weights only 1Gb, while my iTorrent contains 107Gb
![IMG_0015](https://user-images.githubusercontent.com/9553519/76335872-377b4300-6306-11ea-8879-e56f02214658.jpg)
![IMG_0016](https://user-images.githubusercontent.com/9553519/76335775-14509380-6306-11ea-8d85-12eab6883d18.jpg)
