### ISSUE TITLE
Background downloading is not working

### ISSUE THREAD

**Issue by DSS3113** [XITRIX/iTorrent#85]
Background downloading isn’t working even though I have enabled it. When I turn off the app and open it after 15 seconds or so, the download speed goes from 900 KB/s to 0 B/s.

**Comment by XITRIX** [comment]
Need more info: device/ios version/app version

**Comment by DSS3113** [comment]
> Need more info: device/ios version/app version

Device: iPhone 8 64GB
iOS version: 13.3.1
App version: 1.7.4

**Comment by XITRIX** [comment]
I cannot reproduce it, can you make a video of your problem like that?

https://drive.google.com/file/d/19m2-5j4ygjl1ew0an7S-O9GY_MYWLJR9/view?usp=sharing

**Comment by DSS3113** [comment]
Sure 
https://drive.google.com/file/d/1fAwNQshMaLNJQ99zQPmaeBbzIizJyIcp/view?usp=drivesdk

**Comment by XITRIX** [comment]
On the video, your speed would become 0 also without closing app, cause you stopped torrent by disabling files, and it needs some time to gain speed again, so this video cannot provide any information for me.
Try to make video where I could see stable high speed of downloading for several seconds, like on mine, then close and reopen app, it would be more informative than that one.
Thanks

**Comment by DSS3113** [comment]
Sorry, is this better?
https://drive.google.com/file/d/1rbAhknlvOvTHpISmkSlX46ZXeyqmTG05/view?usp=drivesdk

**Comment by XITRIX** [comment]
Your download speed is just awesome)
It is really something strange, as I send you earlier my screen record earlier, you can see that it works great, also I have several ipads and iphones, with and without jailbreak, on different ios versions, and background downloading works fine on them for me.
I can try to make some more research, but for it I need to know some mode details:
1) Why your download speed so low? Is it your network connection, or tracker problem?
2) If it is tracker, can you send me torrent file for it?
3) How did you installed app, by cydia impactor, or from sideload resource (if it, give me a link)?
4) Enable "Zero speed limit" in settings for 1 minute, and try to wait a notification about low download speed. Will it appear?

**Comment by Maatje36** [comment]
I had the same problem when I disable "Zero speed limit" in settings.

When I enable "Zero speed limit" in settings again (at 1 minute), background download work again.

iPhone XS 64GB, iOS 13.3, Jailbreak Unc0ver 4.3.1, iTorrent 1.7.4

**Comment by DSS3113** [comment]
This fixed it! Thanks!

**Comment by XITRIX** [comment]
@Maatje36, wow, that’s strange, thanks! I’ll try to find out why it’s working like that.

**Comment by Maatje36** [comment]
@XITRIX, You're welcome. And thank you for the great itorrent app!
