### ISSUE TITLE
Application closes when trying to open

### ISSUE THREAD

**Issue by Sambalinski** [XITRIX/iTorrent#86]
The application does not start on ios 13.3.1 Tested on iPad pro 2018 and iPhone XR. Worked on 13.2

**Comment by XITRIX** [comment]
What version of app?
My iPad Pro 10.5 iOS 13.3.1 and iPhone 8+ iOS 13.4 - works fine.
Try to install it by cydia impactor

**Comment by Sambalinski** [comment]
Latest release (March 2020)
My installation steps:
1. Open Xcode
2. Login to my developer account
3. Open ios signer and sign ipa file
4. Xcode -> devices -> choose my device -> add signed ipa to my device.

**Comment by XITRIX** [comment]
Can you try to install it by cydia impactor? It is the only way I know should work for 100%

**Comment by Rikfc** [comment]
Same problem for me. I can't use Cydia Impactor because I get this error: file: provision.cpp; line: 81; what:

ios/listAllDevelopmentCerts = 3018
Please update to Xcode 7.3 or later to continue developing with your Apple ID

I used NullxImpactor

**Comment by Sambalinski** [comment]
I have the same problem, when I'm trying to install iTorrent by Impactor.

**Comment by Rikfc** [comment]
> Same problem for me. I can't use Cydia Impactor because I get this error: file: provision.cpp; line: 81; what:
> 
> ios/listAllDevelopmentCerts = 3018
> Please update to Xcode 7.3 or later to continue developing with your Apple ID
> 
> I used NullxImpactor

With NullxImpactor I’m able to install iTorrent but app crashes when trying to launch. IPAD Pro 12.9 inches 2th generation with iOS 13.3.1

**Comment by rullinoiz** [comment]
same here, iphone 11 ios 13.3.1, sideloaded with altstore and nullximpactor. it just closes when i try to launch it

**Comment by Rikfc** [comment]
Sideloaded with AltStore. Now it works.!

**Comment by mygregstuff** [comment]
@XITRIX can you test using Xcode, with a non paid Apple developer account? I would prefer not using altstore and other applications written by third parties. I believe last time I looked into this, there was some pod that only worked with a paid dev account. (Again, I’m not sure, but that appeared to be the issue)

**Comment by gotzlotz** [comment]
I test it with Xcode and I don’t have a pod developer account. You can use it for 7 days then you have to install again.

**Comment by XITRIX** [comment]
@mygregstuff, you told impossible case, there is no difference in paid and free developer accounts, just 3 app limitation and 7 days of them working. Also with paid account you can create certificates with extra permissions, like push notification or iCloud usage, but iTorrent don't use any of them. And yes, I checked, works perfectly.
I found crash on start application: if there is corrupted torrent file in _Config folder, app will crash, I already fixed it in Dev branch, but I think it isn't your case.

**Comment by XITRIX** [comment]
I'll close it cause this is about app signing, not about the app itself
