### ISSUE TITLE
"Save Video" Crash.

### ISSUE THREAD

**Issue by syto203** [XITRIX/iTorrent#88]
iPhone X iOS 13.3
iTorrent 1.7.4 Hotfix

Using the share menu to save a video to the camera roll via the "Save Video" menu items crashes the app.

**Comment by XITRIX** [comment]
I think I did not add such action for share menu, maybe it appears by default and have to use permission to add files to pictures folder. For now use Files app to manipulate with your downloaded files, I'll try to add this permission in the future updates

**Comment by XITRIX** [comment]
Fixed in Release 1.8
