### ISSUE TITLE
Using TestFlight to distribute app

### ISSUE THREAD

**Issue by LampPrinter** [XITRIX/iTorrent#90]
Have you thought about using TestFlight? I have seen a lot of apps on TestFlight which would otherwise never be allowed on AppStore.
This would also solve the issue of opening .torrent files directly from Files app. This is at present broken (when using any 3rd party signing services).

**Comment by XITRIX** [comment]
Yes, I thought about it, testflight could submit apps that will never be allowed on AppStore, but they still follows to apple guidelines, so apps which breaks them also will not be accepted.
If I had my own account, I could try to distribute it there, but I don't have one, and spend 100$ to try is not good idea for me, cause if they will refuse it, I'll spend them for nothing, cause I have developer account from my job, for all my development purposes
