### ISSUE TITLE
Full size ad even when disabling ads in settings

### ISSUE THREAD

**Issue by hellobrother222** [XITRIX/iTorrent#91]
On the latest version, I disabled ads in iTorrent’s settings, but I still sometimes get a full screen ad when launching the app . I’ve since downgraded the app and I don’t face this issue anymore. Great app btw

iPhone Xr, iOS 12.4

**Comment by XITRIX** [comment]
Hi, that "disable ad" option left me with 1$ per month, cause everyone disable it, without even donating a cent... So I add 1 time on launch ad without an option to remove it, I thought about removing "disable ads" option, but I decide to do like that. 
Sorry if this is inconvenient, but I would like to buy at least a big mac with coffee for my work :(

**Comment by hellobrother222** [comment]
Would there be a way for you to disable it if we donate? I'm ready to pay $3 for it

**Comment by XITRIX** [comment]
I can make a build specially for you :) But seriously, I tried to find out the way how to disable ads by donation, if it could possible to use app store, it could be much easier to do ...
But later, I think I'll try to do something

**Comment by MdFurman** [comment]
Уж лучше сделай пусть постоянно банер с рекламой висит, это видео при открытии нереально раздражает, отбивает желание пользоваться приложением, наихудший вид рекламы.

**Comment by XITRIX** [comment]
я подумаю над тем, что бы переключатель выключал только фуллскрин рекламу

**Comment by suyashbansal** [comment]
Hey.. why don't you use something like Patreon to link the subscription with some fee?

**Comment by 141** [comment]
One time payment, get a code, enter it and get no ads and maybe an extra feature, like colors. That would be the goal hopefully. Also the disable ads could only be valid for a week, where they have to disable again while seeing the opportunity to pay. Minor inconveniences are to be expected in a free app, but when they always take up valuable screen space or make noise, that's when an app gets hated--that's why a disable banner ads is essential.
Now that I'm finally jailbroken again, I can go back to transmission, but I like this app.

**Comment by XITRIX** [comment]
I heard you, in next updates I'll allow to disable it. Later, I'll try to add some "donate" button with key generation to turn ads off, but now I don't know where to start, trying to find out if PayPal donate button can do such a functionality

**Comment by XITRIX** [comment]
> Hey.. why don't you use something like Patreon to link the subscription with some fee?

Haven't thought about that way, I'll try to check if it is possible

**Comment by XITRIX** [comment]
Disabled fullscreen ads, implemented Patreon integration to disable bottom bar ads
