### ISSUE TITLE
Settings App size reports downloaded files after moving them

### ISSUE THREAD

**Issue by axeleszu** [XITRIX/iTorrent#94]
In settings ios reports app used space as all the torrents downloaded, even after moving files to other folders.

**Comment by XITRIX** [comment]
It's an iOS problem, Files app have a really bad file management, sorry, but I cannot help you with it. Sometimes I have to reinstall Files app to fix some memory issues, you can try to do the same.

**Comment by XITRIX** [comment]
Or may be you are right. I found that system's tmp folder stores a lot of useless files (60gb in my case), I added a cleaning function on application start, so it should fix the problem.
