### ISSUE TITLE
Download location 

### ISSUE THREAD

**Issue by 3nad90** [XITRIX/iTorrent#97]
Can you please add choice to where I can download torrent file on my ipad or my external drive 
thanks

**Comment by XITRIX** [comment]
I think it is a good idea, I'll try to make some research if iOS can have such functionality

**Comment by 3nad90** [comment]
Thanks I hope you can

**Comment by Murfi99** [comment]
Thankyou for the awesome app 
I have this same problem on my ipad pro 64GB even though i have 25gb free space it only shows 6GB available in iTorrent to download to

I have an external SSD hard drive  which works great with iOS13.5 on EXFAT system with 800GB free space but I cannot use it with iTorrent

The ability to chose where the downloads go would be a game changer and i really would not need to use windows laptop anymore for torrents

Thankyou

**Comment by XITRIX** [comment]
Hi, now I'm implementing an RSS system into iTorrent, so all my free time I spend on it. Also I have no Lightning to USB connector yet, so when I'll finish with RSS I'll buy it and will make some experiments with it.

**Comment by XITRIX** [comment]
I bought apple's lightning to USB adapter, and I think this feature is impossible for now, even Documents app doe's not support external drive while it is the best file manager for iOS.
