### ISSUE TITLE
iTorrent not showing up in Files app

### ISSUE THREAD

**Issue by dungarzaleel** [XITRIX/iTorrent#98]
iTorrent isn’t showing up in the Files app. I’m using iOS 13.4.1.

**Comment by XITRIX** [comment]
What version of app? How do you installed it?

**Comment by dungarzaleel** [comment]
Version 1.8 installed using AltStore

**Comment by XITRIX** [comment]
Have you downloaded anything? Try to move any file from your system into iTorrent folder, it could appear in moving menu, sometimes, if it is empty, it could not appear.

**Comment by dungarzaleel** [comment]
Just did. It won’t show if I try moving apps in the files app. Yes, I have
downloaded stuff from the app. For now I’m just transferring the files to
whichever app I want using the share option

**Comment by XITRIX** [comment]
It's really strange, I have 2 iDevices which I not use as development tools, and they have iTorrent installed from AppCenter (not by xCode) and they have no such problems...
I really don't know what to suggest...
Try to reinstall app, or use another method of installing...
Do you have another device just to check if problem will reproduce there?

**Comment by dungarzaleel** [comment]
Have any guide or walkthrough on how to sideload through Xcode?

**Comment by dungarzaleel** [comment]
I’ll check on another device, thanks for helping out

**Comment by XITRIX** [comment]
Yes, there is [Build guide](https://github.com/XITRIX/iTorrent#build) in ReadMe file

**Comment by XITRIX** [comment]
I'll close it for now, if you'll have any updates, feel free to reopen it
