### ISSUE TITLE
Adding multiple trackers

### ISSUE THREAD

**Issue by ghost** [XITRIX/iTorrent#99]
It would be really cool to add multiple trackers at the same time and not one by one.

**Comment by XITRIX** [comment]
Do you mean like separated by comma, or how?

**Comment by ghost** [comment]
I mean like trackers seperated line by line like:
www.tracker1.com
www.tracker2.com

**Comment by XITRIX** [comment]
Default textview inside alert controller is not support multiline, so to implement that I have to write an whole new UI element just for that feature, I'm afraid that I have no enough time now to implement that

**Comment by ghost** [comment]
Ok anyway, thank you for your time to at least respond.

**Comment by XITRIX** [comment]
I'll add it in my "feature request" list, if I'll have enough time, may be I'll make it.

**Comment by ghost** [comment]
Hey @XITRIX! I kinda implemented this feature in iTorrent, all by myself. It is mostly working. Would you want to see it?

**Comment by XITRIX** [comment]
Yes, of course

**Comment by ygzo** [comment]
Actually I don't consider myself as a developer and I'm lacking to know how to use GitHub properly. Is there a way to upload my project without intercepting with the pull request that I created for translation? It would be good if I could discuss this with you through another platform actually.

**Comment by ghost** [comment]
Check it out https://github.com/ygzo/iTorrent/commit/aed8f2ed797011197f0549e841748964296320dc

**Comment by XITRIX** [comment]
I checked your solution, it works but it looks ugly, I think I'll use it as reference, but I should beautify it before adding into release version, thanks for your work!

**Comment by ghost** [comment]
> I checked your solution, it works but it looks ugly, I think I'll use it as reference, but I should beautify it before adding into release version, thanks for your work!

Yeah it's really ugly LOL! But it does it job pretty well for me at this time. I hope I see a whole-new beautified version of it from you. Thanks for initially making iTorrent.

**Comment by SydneyUrshan** [comment]
Adding multiple trackers was also on my wishlist. A few days ago I decided to enter numerous trackers one by one on all my running torrents. However, when the app crashed, it lost all the work. On crashes, the torrents also lose other settings like the sequential download button and various (de)selected files on multi-file torrents.

**Comment by ghost** [comment]
> Adding multiple trackers was also on my wishlist. A few days ago I decided to enter numerous trackers one by one on all my running torrents. However, when the app crashed, it lost all the work. On crashes, the torrents also lose other settings like the sequential download button and various (de)selected files on multi-file torrents.

You can build the repo on my [fork](https://github.com/ygzok/iTorrent) to use it until there is an official one. It looks like this right now. ![image](https://user-images.githubusercontent.com/25876327/83298440-20f5d100-a1fd-11ea-9b90-0b5d67522ad0.jpeg)

**Comment by XITRIX** [comment]
@SydneyUrshan, yes, crashes is the most awful problem which cause some changes lost, you could force quit from app to save the changes, in case there was lots of them and you afraid to lost them.

**Comment by SydneyUrshan** [comment]
@XITRIX, if I quit the app or restart the phone, I lose everything. I even try pausing the torrents and then quitting the app before restarting and still lose, though that technique did work on previous builds. As far as the trackers, it would be convenient if each one was copyable to be able to paste them to other torrents (one by one). Or even being able to copy the entire list though when pasting, that puts us back to adding multiple trackers, but at least the list could be saved for future reference...

**Comment by SydneyUrshan** [comment]
@ygzok, yeah I saw that. It looks pretty cool. I can't use it though because I have a specific installation problem requiring the current release. Also, it looks like it's based on a previous build and I would lose other benefits as well provided by the current version. I do look forward to @XITRIX building off your code in a future release!

**Comment by mahee96** [comment]
PR #269 should add support for multi-line trackers add (bulk).
